### ISSUE TITLE
Parsing from remote host. Wrong files search.

### ISSUE THREAD

**Issue by kkolotyuk** [darold/pgbadger#197]
During parsing logs from a remote server with command:

``` console
./pgbadger -v -f stderr -r my_host --ssh-user my_user -b '2014-09-26 04:48:01' -e '2014-09-26 04:54:00' /path_to_log/*
```

if there is not empty /path_to_log folder on a local server then pgbadger tries to find my local files from /path_to_log on the remote server. And outputs something like this:

> ls: cannot access /path_to_log/local_file.log: No such file or directory
> FATAL: you must give a log file as command line parameter.

If I remove all files from /path_to_log locally then it works fine.

P.S. pgBadger version 6.0

**Comment by satyamsaksham** [comment]
Hi,

I tried this command and it's generating out.html too, but no content within.

./pgbadger -v -f stderr -r 148.251.54.50 --ssh-user citium -b '2014-09-26 04:48:01' -e '2014-09-26 04:54:00' /var/log/postgresql/postgresql-9.1-main.log.1
DEBUG: Looking for remote filename using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey my_user@my_host "ls /var/log/postgresql/postgresql-9.1-main.log.1"
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Starting to parse remote log file: my_host:/var/log/postgresql/postgresql-9.1-main.log.1
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey my_user@my_host "ls -l /var/log/postgresql/postgresql-9.1-main.log.1" | awk '{print $5}'
DEBUG: Remote file size: 463989
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey my_user@my_host " cat /var/log/postgresql/postgresql-9.1-main.log.1" |
DEBUG: Starting reading file my_host:/var/log/postgresql/postgresql-9.1-main.log.1...
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey my_user@my_host "ls -l /var/log/postgresql/postgresql-9.1-main.log.1" | awk '{print $5}'
DEBUG: Remote file size: 463989
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey my_user@my_host " cat /var/log/postgresql/postgresql-9.1-main.log.1" |
cat: /var/log/postgresql/postgresql-9.1-main.log.1: Permission denied
cat: /var/log/postgresql/postgresql-9.1-main.log.1: Permission denied
DEBUG: Start parsing at offset 0 of file /var/log/postgresql/postgresql-9.1-main.log.1 to 463989
[>                        ] Parsed      0 bytes of 463989 (0.00%), queries: 0, events: 0
DEBUG: the log statistics gathering took: 6 wallclock secs ( 0.00 usr  0.01 sys +  0.15 cusr  0.02 csys =  0.18 CPU)
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.01 usr +  0.00 sys =  0.01 CPU)
DEBUG: the total execution time took:  6 wallclock secs ( 0.01 usr  0.01 sys +  0.15 cusr  0.02 csys =  0.19 CPU)
