### ISSUE TITLE
Evolution of metrics over time

### ISSUE THREAD

**Issue by tsn77130** [darold/pgbadger#305]
Hi,

It would be a great improvement for us to have the possibility to follow metrics reported overt time, with graphes (for example, evolution of total duration, evolution of duration by user, evolution of queries by user, etc...)
For now, we use incremental mode, and we compare across reports values, but we can't see easily trends.

Do you thing it would be possible to do something like this ?

**Comment by bersace** [comment]
Hi @tsn77130 thanks for the suggestions ! Can you specify each graph you have built with custom tools ?

e.g. Do you mean cumulative count of queries per user or a graph of queries count / week per user  ?

Regards,

**Comment by dan-aksenov** [comment]
Also it would be nice to "compare" 2 stat pages and auto analyze differences.

ie. day1 - 100 connections, day2 - 200, diff 100.

Something like Oracle awr snapshot compare.

**Comment by tsn77130** [comment]
Hi @bersace , sorry I didn't see before your last comment.
What I want to say is generation of new graphes based on daily metrics, in grafana style for example.
It is not for 'direct' cumulative usage, but more for be able to see anormal metrics quickly in curves.
For example, always on grafana example, one point per day, with total duration. with that, we could easily point of anormal behaviors

**Comment by darold** [comment]
This already exists, in incremental mode pgBadger generate weeks reports that can be used to follow usage day after day and see potential abnormal metrics. You have an example here: http://dalibo.github.io/pgbadger/demov6/index.html

In incremental mode pgBadger generate a main index file with a monthly calendar to access directly to the metrics of a day or to the cumulative metrics for a week. There is no month cumulative view.

Regards,
