### ISSUE TITLE
monthly or custom period report ? combining certain weeks?

### ISSUE THREAD

**Issue by hvisage** [darold/pgbadger#336]
Good day,

 Though I use this package for reporting, the one pain I have is to do a monthly report, to aggregate/average the values over a month period.

Is there anyway to generate a report for a calendar month, or perhaps even beter, for a specifice porting period?

**Comment by darold** [comment]
Hi,

At this time no, the only cumulative view is based on a single week. It might be possible to compute reports over a month but not by default because it will takes lot of time and resources. I've not planed to work on it but I'm not closed on including such feature.

Regards,

**Comment by hvisage** [comment]
Yes, I understand the processing time (am seeing it at present for the system I'm using pgBadger for that takes ~1hour just to update a days stuf into the daily/weekly stuff), and was hoping for a separate way to run that monthly/custom summary at the end of the month/period under review, rather than to have it updated as the logs gets processed and summarized for the daily/weekly runs

**Comment by dorbodwolf** [comment]
any progress on this feature request?

**Comment by darold** [comment]
Unfortunately I don't have enough time to work on this feature and it is not flagged in high priority in my todo list. Don't expect any work on it before summer.

**Comment by darold** [comment]
Commit 34869d2 adds this feature. 
```
    Add new configuration option --month-report to be able to build monthly
    incremental reports.
    
    By default pgBadger in incremental mode only compute daily and weekly reports.
    If you want monthly cumulative reports you will have to use a separate command
    to specify the report to build. For example to build a report for August 2019:
    
        pgbadger --month-report 2919-08 /var/www/pg_reports/
    
    this will add a link to the month name into the calendar view of incremental
    reports to look at monthly report. The report for a current month can be run
    every day it is entirely rebuilt each time. The monthly report is not built by
    default because it could take lot of time following the amount of data.
    
    Like with --rebuild option, if you use per database report you must add
    the -E option to the command.
```

**Comment by hvisage** [comment]
Need to ask about this:

Do I run this after my daily processing?

My current workflow is to feed the day’s postgresql logs (which I rotate daily @00:00) into pgbadger,  and then move those files away to an archive. 
It *seems* that it only reads the binary data for those period(s) of the last pgbadger run… does that then gets updated/appended on that daily basis to provide a monthly summary?
Hoe should I handle month end/beginning roll-over?

**Comment by darold** [comment]
You have to execute pgbadger for monthly summary after the daily call to pgbadger and log rotation. Monthly reports doesn't use the log files. This is only possible when pgbadger is run daily in incremental mode. See documentation about explanation of this mode.
