### ISSUE TITLE
Very long queries causing problem on the "Top" tab

### ISSUE THREAD

**Issue by LloydAlbin** [darold/pgbadger#372]
I have been having several problems with both 9.1 & 9.2 on the "Top" tab that shows the query times. 

Sometimes the query code overlaps on the page.
![2017-09-28 overlapping queries](https://user-images.githubusercontent.com/8635587/30993639-ba81f1da-a464-11e7-848a-18a4c5b40ea0.png)

But all the time, I can get to the end of the page and the queries are cut off.
![2017-09-28 query cut off in display](https://user-images.githubusercontent.com/8635587/30993757-45e71f52-a465-11e7-9cc7-56511aa9176e.png)

Lloyd

**Comment by pgiraud** [comment]
@LloydAlbin would it be possible for you to provide an example of a log trace? Even a small subset would be enough I presume. This would be appreciated and would help find a fix for this usecase.

**Comment by julmon** [comment]
@LloydAlbin I can't reproduce it. Which web browser and version is it ?
