### ISSUE TITLE
Documentation on bind/prepare/execute/usual ?

### ISSUE THREAD

**Issue by marksievers** [darold/pgbadger#381]
My sincere apologies for creating an issue, I've tried my level best to discover the answer by myself (pg mail archives, pgbadger documentation, pgbadger code) and find the best forum in which to ask.

The best information on this topic I could find was a user asking the same question on [pg_performance](https://www.postgresql.org/message-id/D83E55F5F4D99B4A9B4C4E259E6227CD0149D1B5%40AUX1EXC01.apac.experian.local).

My questions are:
* The best forum / method for general questions?

* `Ratio between prepared and "usual" statements:` why is this expressed as a percentage and not as a decimal like `Ratio of bind vs prepare`. This makes me think I've missed something in its meaning. For instance I have a value of 98% - I interpret this to mean for every prepare statement I have close to one usual statement.

* `Ratio of bind vs prepare` with a value of 35.1, I can interpret as 35 uses of every prepared statement?

* I can't make sense of "Percentage of prepare" in  `General Activity > Prepared Queries` - it seems to add up to more than 100% for all hours.

Thanks in advance and again apologies if this is the wrong forum. Wonderful product by the way, has assisted highlighting many problems.

**Comment by darold** [comment]
Commit a2ec1bc fix `Ratio between prepared and "usual" statements` that was wrongly expressed in %. For all your interpretation you were right. Sorry for the insane response delay.
