### ISSUE TITLE
Wrong number of session for pgbouncer ?

### ISSUE THREAD

**Issue by ioguix** [darold/pgbadger#385]
Hi,

While parsing a pgbouncer file, I have some trouble interpreting the "Simultaneous sessions" graph and its key value. See:
* pgbadger-num-session-per-min.png
  ![pgbadger-num-session-per-min](https://user-images.githubusercontent.com/16266/34441046-96e62172-ecb9-11e7-90cb-bb0067d23293.png)

* the key values in the report are 
  ~~~
  Session Peak
  580 sessions
  2017-12-21 12:04:17 Date
  ~~~
When parsing myself the log looking for session login/closing, I found another graph. See log-num-session-per-min.png

![log-num-session-per-min](https://user-images.githubusercontent.com/16266/34441045-96c08796-ecb9-11e7-9fc5-c8a8246232ef.png)

Is this a bug ? A misunderstanding on my side ?

Thanks,

**Comment by darold** [comment]
Commit 20cb253  changes the title "Number of sessions (1 minute average)" into  "Number of sessions/second (1 minute average)". The statistic represent an average perl second of all session opened during the interval, here 1 minute and 5 minutes by default. I think this is the reason of the misunderstanding.

Min and Max are the minimal and maximum number of sessions opened at a second during the interval.
