### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devrimgunduz** [darold/pgbadger#390]
Hi,

Are you considering a new release? I see a lot of commits since 9.2 -- and it may be good for the people to update pgbadger along with Thursday releases.

Regards, Devrim

**Comment by bersace** [comment]
Hi @devrimgunduz thanks for the point. It's a bit late for me :-) I let @darold  decide.

**Comment by darold** [comment]
Hi @bersace you know that I'm no more the pgBadger maintainer for more than 6 months now, if you want to publish a new release you can do it without my approval. IMHO there is too much pending issues that need to be solved before a new release, but outside cosmetics changes I see Wesley Bowman's commit about `--include-time` option that should be published. I don't know what else to say.

**Comment by skabashnyuk** [comment]
Hi. Any progress on a new release?

**Comment by darold** [comment]
@dalibo when do you planned to publish a new release? Latest one is one year old !

**Comment by darold** [comment]
Version 10.0 release today.
