### ISSUE TITLE
Incorrect duration when log_statement is "mod" and log_min_duration_statement is enabled

### ISSUE THREAD

**Issue by acedevuser** [darold/pgbadger#401]
I've been using latest master revision of pgbadger (48b814695b4836d7df71f79559c5bf3b374f4171) with the following settings in postgres:
`log_statement = "mod"`
`log_min_duration_statement = "100"`
with csv logging enabled

Why I use it in this way is I want to track long duration queries + have all modification queries to get precise restore point just in case.

I'm note sure if this is a valid case for pgbadger, so please tell me if it's not so I will find another way.

I supposed pbgadger will process duration of queries where it exists and leave rest of them as is.
But looks like what happens is pgbadger doesn't clean t_duration key and use previous one, so if I use attached file I get 134.418 as a duration for each of update records, like

`duration: 134.418 ms  execute <unnamed>: select * from test where name = $1`
`134.418`
`execute <unnamed>: update test set name = $1`
`134.418`
`execute <unnamed>: update test set name = $1`
`134.418`

I believe it's required to initialize
`$prefix_vars{'t_duration'} = '';`
in process_file procedure, csv block ot avoid this, but I'm not so familar with pgbadger yet.

[postgresql-pgbadger.csv.log](https://github.com/dalibo/pgbadger/files/1860728/postgresql-pgbadger.csv.log)

**Comment by darold** [comment]
Commit 20712f8 fixes this issues.
