### ISSUE TITLE
Incorrect count for temporary files ?

### ISSUE THREAD

**Issue by LaetitiaAvrot** [darold/pgbadger#402]
Hi,

I have a treatment that generate large temporary files. It's ok, it's part of the process. I log temporary files on postgresql.log.PostgreSQL write several lines for the same temporary file when it's large enough (just to say, "so far I've written that").

I have the impression that when badger write the report about temporary files, it assumes each line means a new file whereas as I explain earlier it's not the case. When you look at the "Queries generating the most temporary files (N)" table, it seems the "count" column count each time this query is written in the log file instead of each time this query generated a temporary file.

It can lead to large misinterpretation and huge time consumption, trying to understand why this query has so many executions while actually it doesn't.

But maybe I misunderstood the goal of the "count" column...

Have a nice day,

Lætitia

**Comment by darold** [comment]
Hi,

First of all really sorry for the response delay. You are right, a temporary file can not exceed 1GB so it is not uncommon to see several temporary files for the same query. This is the case in this example:
```
2018-09-02 13:53:36 CEST [17847]: LOG:  temporary file: path "base/pgsql_tmp/pgsql_tmp17847.0", size 1073741824
2018-09-02 13:53:36 CEST [17847]:  STATEMENT:  insert into t4 select * from generate_series(1, 100000000);
2018-09-02 13:53:36 CEST [17847]: LOG:  temporary file: path "base/pgsql_tmp/pgsql_tmp17847.1", size 326258176
2018-09-02 13:53:36 CEST [17847]: STATEMENT:  insert into t4 select * from generate_series(1, 100000000);
2018-09-02 13:53:36 CEST [17847]: LOG:  duration: 108343.781 ms  statement: insert into t4 select * from generate_series(1, 100000000);
```
and pgbadger, with current development code, reports:
```
Number temporary files: 2
Max size of temporary files: 1.30 GiB
Average size of temporary files: 667.57 MiB

- Queries generating the most temporary files (N) ---------------------------

Rank   Count   Total size    Min/Max/Avg size    Query
1)   1 - 1,400,000,000 - 1,400,000,000/1,400,000,000/1,400,000,000.00 - insert into t4 select * from generate_series(?, ?);

- Queries generating the largest temporary files ----------------------------

Rank   Size    Query
1)   1,400,000,000 - 2018-09-02 13:53:36 - insert into t4 select * from generate_series(1, 100000000);
```

So as you said, pgbadger here count 2 temporary files which is the real count of files created on disk. Also pgbadger count only one query that generates 1.4GB of temp file.

I'm closing this issue, if you still found an issue, please reopen the issue with a log example.

Best regards,
