### ISSUE TITLE
Incorrect count on ERROR log lines ?

### ISSUE THREAD

**Issue by jcarnu** [darold/pgbadger#403]
Hi,
I've got a large log files from syslog. I've launched pgBadger with a JSON (300MB) output reporting the following counts  (json key : logs_type): 
  * LOG : 5648773
  * STATEMENT : 121438
  * DETAIL : 54689
  * CONTEXT : 19072
  * ERROR : 68120
  * HINT : 184
  * FATAL : 1

With `grep` + `wc -l` against  the same log files we've got :
   * LOG : 5701745
   * STATEMENT : 121438
   * DETAIL : 54689
   * CONTEXT : 19072
   * ERROR : 15149
   * HINT : 184
   * FATAL : 1

Whereas DETAIL, CONTEXT, HINT, FATAL and STATEMENT are the same, ERROR and LOG differs.

IMHO, some lines counted in ERROR have to be reported to LOG : badger.LOG + (badger.ERROR - grep.ERROR) = grep.LOG

Semantically I assume that 1 error count is only one error report (not multiple lines). One error may have a CONTEXT and a STATEMENT that may be count such as.

Here's the shell line to count log lines FWIW
<code bash>
for ST in "LOG" "STATEMENT" "DETAIL" "CONTEXT" "ERROR" "HINT" "FATAL"; do echo -n "  * ${ST} : "; cat $(find . -name "postgresql.log*") | grep "${ST}:" | wc -l ; done
</code>

**Comment by bersace** [comment]
Salut @jcarnu , can you split the file and maybe find some sample lines not properly counted ?

**Comment by jcarnu** [comment]
Hi Etienne,
I'll do asap. Maybe by the end of next week. I'm quite busy right now.

**Comment by jcarnu** [comment]
Hi @bersace ,
after some dig in the code, it appears that you change log level for messages in `change_log_level` function. For the log processed (I cannot file here), there's a lot of advisory lock matching the following line : `return 1 if ($msg =~ /still waiting for/);` 

The lines matched by "still waiting for..." is a `LOG` line and not an `ERROR` line. When called, `change_log_level` comments tells us its only a temporary log_level change but these lines are still counted as `ERROR` at the end of the script.

You will find here the json key I use to query pgbadger JSON output
```
jq .logs_type /tmp/out.json
{
  "ERROR": 1,
  "STATEMENT": 2,
  "DETAIL": 1,
  "LOG": 45
}
```

I'm quite confused by the way LOGs lines may be counted as ERRORs (even as temporary).

There might be a good reason to change log_level at a time (for programmatic reason) but IMHO, waiting for locks is what PostgreSQL says : a LOG, not an ERROR.

**Comment by darold** [comment]
Commit 20712f8 might fix this issue.
