### ISSUE TITLE
Doubling the number of requests when using prepared statements

### ISSUE THREAD

**Issue by vadv** [darold/pgbadger#405]
I use pgbadger, and use parameters in queries.
The pgbadger report has queries without parameters, although they do not exist in postgresql log.
For example, the query from application: `select * from table where col = $1` I see doubling in the report:
* one query type is grouped as: `select * from table where col = ?`
* and other type of query as: `select * from table where col = ''`

like this: 
![image](https://user-images.githubusercontent.com/539450/39394194-b16a0672-4ad7-11e8-99bf-f31bb226770a.png)

my PostgreSQL config:
```
# log
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%a.log'
log_truncate_on_rotation = on
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_min_duration_statement = 1
log_autovacuum_min_duration = 0
track_io_timing = on
log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '
shared_preload_libraries = 'pg_stat_statements, auto_explain, pg_buffercache'
pg_stat_statements.max = 10000
pg_stat_statements.track = all
auto_explain.log_min_duration = 1s
auto_explain.log_verbose = on
auto_explain.log_nested_statements = on
auto_explain.log_analyze = off
auto_explain.log_buffers = off
auto_explain.log_triggers = off
auto_explain.log_timing = off
```

when I run pgbadger:
`/usr/local/bin/pgbadger -I -O /var/www/pgbadger/ /var/lib/pgsql/9.6/data/pg_log/postgresql-*.log`

**Comment by darold** [comment]
Commit 20712f8 fixes this issue.
