### ISSUE TITLE
CamelCased object names are all lower cased

### ISSUE THREAD

**Issue by NikolayS** [darold/pgbadger#407]
I have a database of one project which was migrated from another DBMS, and it has column names like `"userId"`, `"updatedAt"` and table name like `"TableName"`. Such naming is not common for Postgres, but it's a valid naming (camel cased names are valid if double quotes are used with them).

pgBadger reports all contain lowercased values – `"userid"`,`"updatedat"`, `"tablename"`. I checked HTML and JSON output.

This significantly complicates the use of pgBadger by a human and also makes practically impossible to process pgBadger's results by a machine (because queries from JSON don't match to real queries).

**Comment by NikolayS** [comment]
Created a trivial PR #420 to solve this.

**Comment by darold** [comment]
Commit 20712f8 fixes this. Object names with double quote will be kept untouched, others will be forced to lower case.

**Comment by NikolayS** [comment]
Great news, thanks!
