### ISSUE TITLE
Got "Max. recursion depth with nested structures exceeded ..."

### ISSUE THREAD

**Issue by cthart** [darold/pgbadger#409]
Max. recursion depth with nested structures exceeded at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Storable.pm line 328, at /usr/bin/pgbadger line 12106.

Our command line: pgbadger -q --start-monday -I -R 2 -f csv -O /storage/_pgbadger/out -r db /var/log/postgresql/postgresql-`date --date="yesterday" +%F`_000000.csv

pgBadger version 9.2

**Comment by darold** [comment]
Sorry for the response delay, one of the binary file is probably corrupted. I guess that the responsible file have been removed since this time. Use latest development code and reopen the issue to report the new error if it still occurs.
