### ISSUE TITLE
Getting "Wide character in print" in 9.2

### ISSUE THREAD

**Issue by cthart** [darold/pgbadger#410]
According to the Changelog this was supposedly addressed prior to version 4.1, but we're getting it in pgBadger 9.2

"Wide character in print at /usr/bin/pgbadger line 11110."

**Comment by darold** [comment]
Sorry for the response delay, please use latest development code and reopen the issue to report the new error if it still occurs.

**Comment by cthart** [comment]
Still getting this issue in 10.1 (installed from the official PG APT repository.)

If you want some data from me, let me know; we keep all of our PG .CSV log files for quite a while.

**Comment by darold** [comment]
Please send me a log file to be able to reproduce the issue.

**Comment by cthart** [comment]
The compressed CSV log file is 174Mb... The error message from
pgbadger says "Wide character in print at /usr/bin/pgbadger line
11311." Is that line 11311 in the code? How can I identify the lines
in the log file? I can make the whole file available to you if you
want -- I can put it somewhere for you to download. What's your
private email address?

**Comment by darold** [comment]
Thanks, send a link to download the log at < gilles AT darold DOT net >

**Comment by cthart** [comment]
Before I send you the whole file, can I use eg verbose mode to get
information about which line(s) or query/queries in the CSV file are
causing the problem?

**Comment by darold** [comment]
No there's no such debug information, but what you can do is splitting the uncompressed log file using:
```
split --lines=`wc -l postgresql-11.0.log | awk '{print $1/10}'` postgresql-11.0.log
```
and find which of the ten 10 file parts is generating the error. This will reduce the size of the file to send.

**Comment by cthart** [comment]
Thanks!

Do you expect a new release soon? We install from the Postgres APT repository so if a new release is coming soon I won’t install and test separately.

Thanks again,

/Colin

**Comment by darold** [comment]
Yes, I will try to get it out this weekend.
