### ISSUE TITLE
With auto_explain, plan shows mixed with query SQL

### ISSUE THREAD

**Issue by zam6ak** [darold/pgbadger#413]
I have auto explain turned on
```
auto_explain.log_min_duration = '250ms'
auto_explain.log_analyze = on
auto_explain.log_buffers = on
auto_explain.log_timing = on
auto_explain.log_triggers = on
auto_explain.log_verbose = on
auto_explain.log_format = 'text'
auto_explain.log_nested_statements = on
```

And in 'Top' section queries are showing with plan "mangled" with SQL itself.
IThe query itself shows` Query Text: ` following query for first few lines but then bits and pieces of the actual plan are being mixed with other parts of SQL...

Also there is no "submit" button for https://explain.depesz.com/ (previous issues indicate there should be one?)

**Comment by zam6ak** [comment]
BTW, if I switch back to `log_destination = 'stderr'` , the issue goes away
So it seems to be related to `csvlog`

However, with 'stderr'` the queries under 'Top' / Slowest individual queries' are duplicated
For the same query, there is an entry with query only and another separate entry with query and explain plan...

**Comment by darold** [comment]
Commit 20712f8 fixes this issue.
