### ISSUE TITLE
Generate compressed files

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgbadger#425]
Just an idea: 
As an option, compress the HTML, JSON... generated file. 

Use case: reports generated on the server that will be immediately transfered away to be read.

I suppose that detecting an extension like .html.bz2 or .json.gz should be enough. And/or add a --compress-result flag to gzip.

Obviously, this is a luxury option to spare a pipe. That could be handy for people without command line knowledge though.

**Comment by darold** [comment]
I think it is trivial to do that at command line, for example:
```
pgbadger /var/log/postgresql/postgresql-10.log && gzip out.html
```
The effort to add automatic compression following the output extension is not trivial compared to the command line above. I won't do that myself but if someone want to develop this feature the patch will be accepted.
