### ISSUE TITLE
parsing of vacuum / analyze system usage for PostgreSQL 10 (and a patch to solve it)

### ISSUE THREAD

**Issue by achix** [darold/pgbadger#426]
Here is a patch that solves this.
[pgbadger_pgsql10_vacuum_analyze_patch.txt](https://github.com/dalibo/pgbadger/files/2149142/pgbadger_pgsql10_vacuum_analyze_patch.txt)

**Comment by achix** [comment]
BTW, I sent this as an issue cause I couldn't create a new pull request.

**Comment by darold** [comment]
Thanks for the patch, applied in commit 20712f8.
