### ISSUE TITLE
minimum log_line_prefix requirements and documentation

### ISSUE THREAD

**Issue by blogh** [darold/pgbadger#431]
Hi, 

I was checking if the log_line_prefix provided by Azure PostgreSQL PaaS is compatible with pgbadger and I noticed that the information provided on the web site about the minimum log_line_prefix requirements are inexact:
- The main page and the POSTGRESQL CONFIGURATION part of the documentation page says says %t %p %l are requiered. 
- The DESCRIPTION part of the documentation page says %t %p
- A commit added %m %p
- I tried %t %c, it works. (It's pretty cool since %c is %p %s hex'ed)

I propose to update the requirement with something like 

> pgBadger supports any custom format set into the log_line_prefix directive of your postgresql.conf file as long as it at least specify a time escape sequence (%t or %m) and a process related escape sequence (%p or %c).

For the configuration part, I am not sure about what to propose because of '%l'. 
- Is it possible to rely on the time and process number to reorder a sequence of messages without the %l escape sequence ? Is %l just used to match the default prefix for "stderr" ?

Benoit.

**Comment by darold** [comment]
Applied in commit 20712f8. `%l` is no more mandatory in default prefix and reference to it have been removed from documentation. Here is the new behavior:

```
pgBadger supports any custom format set into the log_line_prefix directive of
your postgresql.conf file as long as it at least specify a time escape sequence
(%t, %m or %n) and the process related escape sequence (%p or %c).
```
