### ISSUE TITLE
Small issue with SQL beautifier (":=" becomes ": =")

### ISSUE THREAD

**Issue by NikolayS** [darold/pgbadger#433]
For named parameters in functions, like this:

```sql
select somefunc("param" := 'value');
```

in sample queries listed in "Top ** queries" we see:
```sql
select somefunc("param" : = 'value');
``` 

which is not a valid SQL for Postgres because of extra space.

**Comment by darold** [comment]
Commit 095a355 replaces SQL::Beautify with v3.0 of pgFormatter::Beautify, this should fix the issue.
