### ISSUE TITLE
homebrew bottle ownership

### ISSUE THREAD

**Issue by hunleyd** [darold/pgbadger#436]
Will you be taking over the pgbadger bottle in homebrew? As of now, it still shows version 9.2 and Dalibo.

**Comment by darold** [comment]
I don't know what you call homebrew, do you have an URL?

**Comment by hunleyd** [comment]
sorry, https://brew.sh/

**Comment by darold** [comment]
Oh ok, this is a mac installer. I don't know who maintain this repository, it need investigation.

**Comment by hunleyd** [comment]
```
doug@ReturnOfTheMac ~> brew info pgbadger
pgbadger: stable 9.2 (bottled), HEAD
Log analyzer for PostgreSQL
https://dalibo.github.io/pgbadger/
/usr/local/Cellar/pgbadger/9.2 (7 files, 1.4MB) *
  Poured from bottle on 2018-03-29 at 11:30:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgbadger.rb
```

I think you can submit a pull request against that formula and all should be well

**Comment by SteveNewson** [comment]
I have submitted a PR for the change to 10.0 in homebrew. However the use of "sed -i" in the Makefile is problematic for OSX.

https://github.com/Homebrew/homebrew-core/pull/31987

Currently fixed with a replace but they won't merge unless this is fixed in pgbadger.

**Comment by darold** [comment]
Thanks, I will fix it.  There will be a new release in few days, the incremental mode is broken. This is fixed in development code but this is a major bug that require new a new release.
