### ISSUE TITLE
no layout in html output

### ISSUE THREAD

**Issue by fvannee** [darold/pgbadger#437]
I'm running pgbadger in incremental mode like this:
`/usr/local/bin/pgbadger --incremental --maxlength 4096 --outdir $OUTDIR --quiet --timezone $TZOFFSET --extra-files $FILE`
The generated overall html file has a normal layout as I expect it (eg. I see a calendar and I can click on a day). However, when I click on a specific day it takes me to an HTML page where the layout is messed up. I've attached a screenshot. (I ran it on latest master which includes the division by zero fix)
I didn't have this issue on the previous version of pgbadger.

![image](https://user-images.githubusercontent.com/1274053/45347800-3a7c6280-b5ad-11e8-9670-8293798ebeaa.png)

**Comment by fvannee** [comment]
I'm pretty sure it's the links to the css that's not correct. In the previous version it'd be eg.
`<script type="text/javascript" src="../../../9/jquery.min.js"></script>`
And now it's:
`<script type="text/javascript" src="./10/jquery.min.js"></script>`

It's pointing to a non-existing directory (should be a couple directories up).

**Comment by darold** [comment]
Thanks for the report, commit be5d936 might fix this issue.

**Comment by fvannee** [comment]
Thanks! It works again :)
