### ISSUE TITLE
FATAL: when looking for log file format, can't open file -

### ISSUE THREAD

**Issue by maligree** [darold/pgbadger#439]
Hey! I recently migrated from version 7 (that's what's in the official repositories for `ubuntu/xenial`) to 10 and noticed a script stop working. 

Simplified, the line that worked for `v7` was:
```
docker logs $CONTAINER 2>&1  | pgbadger --prefix "%m [%p]" -v -f stderr -
```

But now it's throwing a fatal error:
```
DEBUG: Output 'html' reports will be written to out.html
DEBUG: waiting for log entries from stdin.
FATAL: when looking for log file format, can't open file -, No such file or directory
```

It's entirely likely something has changed in the API, but I'm reporting this just in case.

I've worked around this by first dumping the logs to a file and then passing the file to `pgbadger`, but it would be cool to have the old functionality back.

Let me know if you need any more info!

**Comment by darold** [comment]
Got it, commit 1e650ef might solve the issue.

**Comment by maligree** [comment]
Yep, that fixes it. That was fast, thanks!

**Comment by darold** [comment]
Thanks for the feedback, a new release is coming the incremental mode is totally broken.
