### ISSUE TITLE
Multiple output files

### ISSUE THREAD

**Issue by NikolayS** [darold/pgbadger#442]
It would be great to be able to generate multiple reports in a single run, using multiple `-o` options, like this:
```
pgbadger ... -o out.html -o out.json
```

Right now all `-o` values except the last one are ignored (so in the example above, it generates only `out.json`).

This is a small but convenient optimization for cases when we need to have 2 types of reports – one for humans, another for someone else – w/o necessity to run it twice.

**Comment by darold** [comment]
This desirable feature need a huge rewrite of pgbadger, unfortunately I do not have enough spare time to work on this patch. New status is: delayed at an undefined date.

**Comment by eazrael** [comment]
Add me to the list of interested people. 
May use case is more or less a breakdown of the same reports for different users or application to better see where optimization may be necessary.

**Comment by darold** [comment]
I think what you mention is more related to issue #460 , here the need is to be able to generate for example an HTML report and a second report in JSON for processing with other tools. The goal is to avoid several parsing of the log files.

**Comment by darold** [comment]
Commit c57c931 adds this feature:
```
    The -o | --outfile option can now be used multiple time to dump
    output in several format in a single command. For example:
    
      pgbadger -o out.txt -o out.html -o - -x json /log/postgresql-11.log
    
    Here pgbadger will create two reports in text and html format saved
    in the two corresponding file. It will also output a json report on
    standard output.
```
