### ISSUE TITLE
Improvement parse some logs in local an some others in remote

### ISSUE THREAD

**Issue by jacks33** [darold/pgbadger#446]
Hello, 

I'm using pgbadger 9.2

My use case is parsing postgres logs in local and pgbouncer logs in remote.

Due to high availability architecture base on repmgr/pgbouncer, I face this issue.

It seems pgbouncer attemps to parse all logs in remote.

Is it possible to make the improvement ?

Thank you very Much

**Comment by darold** [comment]
Commit 6e6e867 adds this feature. You might use the following syntax:
```
pgbadger postgresql-local.log ssh://remote.host//var/log/postgresql/pgbouncer.log
```
here the postgresql log is local (same machine as pgbadger) and the pgbouncer log is on a remote host.

Outside ssh you can now use http or ftp to download the remote log file, for example:
```
pgbadger postgresql-local.log http://remote.host/pgbouncer.log.gz
```
