### ISSUE TITLE
pgbadger 10.1 does not display parameters in examples anymore

### ISSUE THREAD

**Issue by BernhardGruen** [darold/pgbadger#447]
Hi,

version 10.1 of pgbadger does not display parameters in the examples view anymore. With 10.0 parameters like $1 and so on were replaced by a value.

Do you think you could optionally reenable this feature?

**Comment by darold** [comment]
Right, commit 14fef5e fixes this issue.

**Comment by darold** [comment]
I've reverted the previous commit because of the inclusion of extra code of a current work in progress. The commit dedicated to this issue is c9941a0.
