### ISSUE TITLE
Unable to generate pgbouncer reports

### ISSUE THREAD

**Issue by tatzlwurm2** [darold/pgbadger#450]
Hello,  Since version 8.0 I have been unable to get anything working for pgbouncer.  
Here's my configuration pgbouncer configuration:
[databases]
databasedb = host=pgdatabasedb02dxm1.dev.oclc.org port=5601 dbname=databasedb
databasedb-ro = host=pgdatabasedb01dxm1.dev.oclc.org port=5601 dbname=databasedb
repmgr-rw = host=pgdatabasedb02dxm1.dev.oclc.org user=isoftstats dbname=repmgr port=5601 application_name=pgbouncer_pgdatabasedb01dxm1.prod.oclc.org pool_size=10
repmgr-ro = host=pgdatabasedb01dxm1.dev.oclc.org user=isoftstats dbname=repmgr port=5601 application_name=pgbouncer_pgdatabasedb01dxm1.prod.oclc.org pool_size=10

[pgbouncer]
listen_port = 5600
listen_addr = *
#logfile = /pgcluster/pgbouncer/log/pgbouncer.log
pidfile = /pgcluster/pgbouncer/run/pgbouncer.pid
#auth_type=hba
#auth_hba_file=/pgcluster/pgbouncer/etc/bouncer_hba.conf
auth_type=md5
auth_file = /pgcluster/pgbouncer/etc/userlist.txt
pool_mode = session
admin_users=admin
stats_users=isoftstats
max_client_conn = 350
ignore_startup_parameters = replication,extra_float_digits,search_path
default_pool_size=300
reserve_pool_size=200
reserve_pool_timeout=60
application_name_add_host=1
#client_tls_sslmode = verify-full
client_tls_sslmode = prefer
client_tls_key_file = /pgdata-system/pg-data-databasedb96/pg-server-san.key
client_tls_cert_file = /pgdata-system/pg-data-databasedb96/pg-server-san.cer
client_tls_ca_file = /home/postgres/.postgresql/root.crt
client_tls_ciphers = HIGH:MEDIUM:+3DES:!aNULL

I run :
./pgbadger --version
pgBadger version 10.1
./pgbadger -v --format=pgbouncer --pgbouncer-only /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log 2> /tmp/output

head -n20 /tmp/output |sed 's/ill/database/g'
DEBUG: Autodetected log format '' from /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log
DEBUG: Output 'html' reports wdatabase be written to out.html
DEBUG: Autodetected log format '' from /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log
DEBUG: Autodetected log format '' from /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log
DEBUG: pgBadger wdatabase use log format pgbouncer to parse /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log.
DEBUG: Starting to parse log file: /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log
DEBUG: Starting reading file /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log...
DEBUG: Start parsing at offset 0 of file /prod/isoftpostgres/prod/logs/pgbouncer-pgdatabasedb01dxm1-2018-10-18.log to 6621199
DEBUG: Unknown pgbouncer line format: e00:00:01 2018-10-18 00:00:01.596 9872 LOG C-0xd08380: (nodb)/(nouser)@10.230.80.7:54784 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.533 9872 LOG C-0xd08380: databasedb/wsdatabase_u@unix(72234):5600 login attempt: db=databasedb user=wsdatabase_u tls=no
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.534 9872 LOG S-0xce87e0: databasedb/wsdatabase_u@10.230.80.93:5601 closing because: server_lifetime (age=3600)
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.559 9872 LOG Stats: 17 xacts/s, 48 queries/s, in 3936 B/s, out 6031 B/s, xact 11597 us, query 535 us wait time 0 us
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.564 9872 LOG S-0xcefcf0: databasedb/wsdatabase_u@10.230.80.93:5601 new connection to server (from 10.230.80.92:37902)
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.961 9872 LOG C-0xd0a450: pgbouncer/admin@unix(72323):5600 login attempt: db=pgbouncer user=admin tls=no
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.962 9872 LOG C-0xd0a450: pgbouncer/admin@unix(72323):5600 closing because: client close request (age=0)
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.967 9872 LOG C-0xd0a450: pgbouncer/admin@unix(72325):5600 login attempt: db=pgbouncer user=admin tls=no
DEBUG: Unknown pgbouncer line format: e00:00:02 2018-10-18 00:00:02.967 9872 LOG C-0xd0a450: pgbouncer/admin@unix(72325):5600 closing because: client close request (age=0)
DEBUG: Unknown pgbouncer line format: e00:00:03 2018-10-18 00:00:03.055 9872 LOG C-0xd0a450: pgbouncer/admin@unix(72340):5600 login attempt: db=pgbouncer user=admin tls=no
DEBUG: Unknown pgbouncer line format: e00:00:03 2018-10-18 00:00:03.056 9872 LOG C-0xd0a450: pgbouncer/admin@unix(72340):5600 closing because: client close request (age=0)
DEBUG: Unknown pgbouncer line format: e00:00:04 2018-10-18 00:00:04.479 9872 LOG C-0xd0a450: (nodb)/(nouser)@10.230.80.8:35235 closing because: client unexpected eof (age=0)

tail -n20 /tmp/output
DEBUG: Unknown pgbouncer line format: e23:59:25 2018-10-18 23:59:25.894 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:31133 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:26 2018-10-18 23:59:26.963 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:34447 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:30 2018-10-18 23:59:30.823 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:36494 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:32 2018-10-18 23:59:32.009 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:10509 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:35 2018-10-18 23:59:35.889 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:19901 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:37 2018-10-18 23:59:37.001 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:14501 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:40 2018-10-18 23:59:40.835 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:59326 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:41 2018-10-18 23:59:41.925 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:49418 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:45 2018-10-18 23:59:45.823 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:53824 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:46 2018-10-18 23:59:46.959 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:49835 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:50 2018-10-18 23:59:50.829 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:38146 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:51 2018-10-18 23:59:51.947 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:46208 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:55 2018-10-18 23:59:55.932 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:38557 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e23:59:57 2018-10-18 23:59:57.020 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.7:19776 closing because: client unexpected eof (age=0)
DEBUG: Unknown pgbouncer line format: e00:00:00 2018-10-19 00:00:00.892 9872 LOG C-0xd089c0: (nodb)/(nouser)@10.230.80.8:38973 closing because: client unexpected eof (age=0)
[========================>] Parsed 6621199 bytes of 6621199 (100.00%), queries: 0, events: 0
DEBUG: the log statistics gathering took: 0 wallclock secs ( 0.24 usr +  0.08 sys =  0.32 CPU)
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
DEBUG: the total execution time took:  0 wallclock secs ( 0.24 usr +  0.08 sys =  0.32 CPU)

I didn't see any special setting or examples on how to generate graphs on this.  Am I overlooking something?

**Comment by darold** [comment]
If the PostgreSQL log and pgbouncer log are on the same machine, yes just give both log file at command line arguments, ex:
```
pgbadger postgresql.log pgbouncer.log
```
if you use pgbadger default log line prefix you will have a single report for both.

If the pgbouncer log is on a remote server this is not possible to parse local an remote log file for the moment. I'm working on this feature request reported in issue #449.
