### ISSUE TITLE
No parameters in query examples

### ISSUE THREAD

**Issue by zawadaa** [darold/pgbadger#451]
After upgrade to 10.1 there is no parameters in query examples.
in 9.2 was:

> l.rodzaj = '43'

now in 10.1 is:

> l.rodzaj = $1

I did not change anything in the execution of the script.

**Comment by darold** [comment]
Please upgrade to latest development code this issue have been fixed in commit c9941a0.

**Comment by zawadaa** [comment]
True, I just did it :-) Fixed
