### ISSUE TITLE
pgbadger stuck during csv parsing

### ISSUE THREAD

**Issue by anayrat** [darold/pgbadger#452]
Hello Gilles,

I try to generate a  report with log in csv format.
pgbadger seems stuck with 100% CPU : 
```
[>                        ] Parsed   10270901 bytes of 1581133486 (0.65%), queries: 337, events: 1
```

A perf top show this perl function : 
```
  84.84%  libperl.so                  [.] Perl_utf8_length
```

It do a git bisect and it is related to this commit : https://github.com/darold/pgbadger/commit/20712f8339f90a51d87b1dbc2507b664a20a2818

How can I help you to fix this bug?

Thanks

**Comment by anayrat** [comment]
I found the line which is 51420002 characters long :( I can't send you, it contains personal data.

**Comment by anayrat** [comment]
Yes, I run pgbadger with only this line and I can reproduce the problem. I will try to anonymize the line.
Thanks

**Comment by darold** [comment]
Ok, I'm closing the issue I think it is not related to pgBadger but to the Text::CSV_XS Perl module. I could be wrong so if you have time to test it using small perl script give it a try.
