### ISSUE TITLE
Documentation issue: -j does not work with csv

### ISSUE THREAD

**Issue by cstdenis** [darold/pgbadger#453]
This is only documented in the code, not in the documentation. Had to dig through the source code to figure out why -j was not working for me. 

Issuing a warning when -j is used with .csv would also be handy. Not even a mention of the problem with -v currently.

**Comment by darold** [comment]
Commit ed356e8 update the documentation an usage and commit eaa0251 add a warning when you try to use parallel processing with csvlog. Thanks.
