### ISSUE TITLE
Timezone shown in graphs does not match the rest of the report

### ISSUE THREAD

**Issue by raptelan** [darold/pgbadger#456]
Our server logs are in UTC.  I'm running pgBadger on a webserver which is also in UTC.  Should be pretty straightforward....but it's not.  For some reason I don't understand, the graphs are shown in UTC-7, my local time zone.  My only guess is that this must be due to client-side rendering as the servers have no awareness of my local time zone.  It makes the reports misleading and difficult to read correctly.

**Comment by darold** [comment]
Yes, unfortunately the timezone to render javascript graphs is taken from the browser side. You can adjust the timezone at pgbadger command using:
```
    -Z | --timezone +/-XX  : Set the number of hours from GMT of the timezone.
                             Use this to adjust date/time in JavaScript graphs.
```

**Comment by raptelan** [comment]
Thank you, sorry for my oversight.  I had seen that option but for some reason thought it had to do with translating the log file timestamps rather than the JavaScript graphs.
