### ISSUE TITLE
not a valid file descriptor at /usr/bin/pgbadger line 12328.

### ISSUE THREAD

**Issue by raptelan** [darold/pgbadger#457]
I get the error, "not a valid file descriptor at /usr/bin/pgbadger line 12328.28", quite a number of times while processing log data.  Here is the command I'm using:

pgbadger -f csv -I -J 8 -t 50 -a 1 --log-duration -U postgres -O "${html_output_directory}/${server}" ${files}

I'm using pgBadger 10.1.

**Comment by darold** [comment]
I can not reproduce this issue, please give a try to latest development code.
