### ISSUE TITLE
pgBadger reporting double queries

### ISSUE THREAD

**Issue by raptelan** [darold/pgbadger#458]
I'm not completely sure why, but on every server that I've tried running pgBadger against, I end up seeing counts that don't add up right in pgBadger.  For example, on the Overview page in the General Activity section for a particular hour, I see 1,018,481 total queries, but only 298,236 read queries, 1,355 inserts, 97,564 updates, and 601 deletes.   That's only 397,756 total.

On the Queries tab, it always shows exactly 50.00% of the queries as type "Others".  What are these "others"?  I don't think they actually exist.

One thing that comes to mind is that I am using both both log_duration = on and log_statement = 'all', but I am also calling pgBadger with --log-duration which is supposed to handle this, right?

Here are my PostgreSQL log settings:

## Where to log
log_destination                         = 'csvlog'
logging_collector                       = on
log_directory                           = '/var/log/postgresql/11/main'
log_filename                            = '%Y-%m-%d_%H.log'
log_file_mode                           = 0640
log_rotation_age                        = 1h
log_rotation_size                       = 0
log_truncate_on_rotation                = off
syslog_facility                         = 'LOCAL0'
syslog_ident                            = 'postgres'
syslog_sequence_numbers                 = on
syslog_split_messages                   = on
event_source                            = 'PostgreSQL'

## When to log
client_min_messages                     = notice
log_min_messages                        = warning
log_min_error_statement                 = error
log_min_duration_statement              = -1

## What to log
debug_print_parse                       = off
debug_print_rewritten                   = off
debug_print_plan                        = off
debug_pretty_print                      = on
log_checkpoints                         = on
log_connections                         = on
log_disconnections                      = on
log_duration                            = on
log_error_verbosity                     = default
log_hostname                            = off
log_line_prefix                         = '%t:%r:%u@%d:[%p-%l]:'
log_lock_waits                          = on
log_statement                           = 'all'
log_replication_commands                = on
log_temp_files                          = 0
log_timezone                            = 'UTC'

**Comment by darold** [comment]
> One thing that comes to mind is that I am using both both log_duration = on and log_statement = 'all',
> but I am also calling pgBadger with --log-duration which is supposed to handle this, right?

pgBadger can handle this configuration but don't expect right results. I will use your configuration to try to find where the problem comes from.

**Comment by raptelan** [comment]
Hm okay, what would you recommend I change to get correct results?  I thought this setup was good as it ensures pretty much everything that can get logged does, but I'm happy to change it if I've inadvertently shot myself in the foot!

**Comment by darold** [comment]
If you want right statistics about queries duration you have to use the recommended configuration with log_min_duration_statement. Otherwise if you just want the statistics about number of queries just disable log_duration. But here I think there could be a bug in csvlog parsing, I will try to give you an answer tomorrow.

**Comment by darold** [comment]
Well have a look to the documentation (README) at chapter "POSTGRESQL CONFIGURATION" may help. The problem with csvlog output is that you will not be able to use multiprocess, personally I prefer to use stderr. syslog log destination is good to, multiprocess is possible, but your very long queries can be truncated.

**Comment by raptelan** [comment]
I will use stderr; and I found the documentation...sorry for missing that before.  What is the most ideal log_line_prefix setting for pgBadger?  I see that it will work with a pretty minimal one, but is there advantage of using a longer one with more details?  Will pgBadger use any of that extra data at all?  It's not clear from the documentation...  I think my current setting is the PostgreSQL default, as I was only logging to CSV previously where it didn't take effect, yet I knew all the information was being logged...

**Comment by darold** [comment]
The more complete auto-detected log_line_prefix by pgBadger is:
```
log_line_prefix = '%t [%p]: user=%u,db=%d,app=%a,client=%h '
```
Other placeholder will not be used by pgBadger.

**Comment by raptelan** [comment]
I have tried to follow all your advice to get parallel processing, but unfortunately, it's not working and pgBadger stays stuck on one CPU still despite me using -j16 on a 16-core system.  Can you please advise me as to what I may be doing wrong?

Here is my pgBadger command currently:

pgbadger -f stderr -I -j 16 -t 50 -a 1 -Z -07 --log-duration -U postgres -O ${target} ${file}

Here is my PostgreSQL logging configuration now on all the databases:

## Where to log
log_destination                         = 'stderr'
logging_collector                       = on
log_directory                           = '/var/log/postgresql/11/main'
log_filename                            = '%Y-%m-%d_%H.log'
log_file_mode                           = 0640
log_rotation_age                        = 1h
log_rotation_size                       = 0
log_truncate_on_rotation                = off
syslog_facility                         = 'LOCAL0'
syslog_ident                            = 'postgres'
syslog_sequence_numbers                 = on
syslog_split_messages                   = on
event_source                            = 'PostgreSQL'

## When to log
client_min_messages                     = notice
log_min_messages                        = warning
log_min_error_statement                 = error
log_min_duration_statement              = 0

## What to log
debug_print_parse                       = off
debug_print_rewritten                   = off
debug_print_plan                        = off
debug_pretty_print                      = on
log_checkpoints                         = on
log_connections                         = on
log_disconnections                      = on
log_duration                            = off
log_error_verbosity                     = default
log_hostname                            = off
log_line_prefix                         = '%t [%p]: db=%d,user=%u,app=%a,client=%h '
log_lock_waits                          = on
log_statement                           = 'none'
log_replication_commands                = off
log_temp_files                          = 0
log_timezone                            = 'UTC'

**Comment by raptelan** [comment]
Ahh, I figured out the problem...I need to run pgBadger on uncomupressed log files to get it to run in parallel.

**Comment by darold** [comment]
pgBadger can't use multi-process with compressed file. Why are you processing log files one by one? You can simply do things in a single command as follow:

```
pgbadger -I -O /mnt/pgbadger_reports/d-gp2-dbpg11common1-1/11-main/ -j 8 /mnt/postgresql_log_statistics/d-gp2-dbpg11common1-1/11/main/*
```
executing this command every day will only parse new log file, you don't have to write a complex script, pgBadger will do all the job.

**Comment by raptelan** [comment]
Earlier when I tried multiple files with CSV and -J option, with large (gzipped) logs from busy servers pgBadger was throwing Out of Memory! errors, even with 32GB of RAM.  I did refactor the script to do as you suggest above but I am seeing the same problem that I described in my last message above - with uncompressed files parallel processing stops shortly after the first file.  I can only see multiple CPUs at work for a short time and usually it is limited by a single CPU...

**Comment by raptelan** [comment]
Here is a screen recording showing the latest version of my script source and running, along with top on the same server - you can see that processing starts out utilizing 16 cores, but drops gradually as it progresses:

https://www.youtube.com/watch?v=tf7LMypIctA

**Comment by darold** [comment]
If I understand well you are expecting that all 16 processes should takes 100% of a CPU until ends? With the `-j 16` option a not compressed and not csvlog will be spitted in 16 equal chunks and will be processed in parallel. They could end at the same time but this is not the case, some parts of the log are processed more quickly following the content of the log partition. Also remember that there might be some iowait, all processes are reading the same file at the same time.

**Comment by raptelan** [comment]
Okay, I understand, thank you for the explanation.  As a possible future enhancement, would it be possible to split the file into a lot more chunks, work on 16 at a time, and whichever one finishes first grabs another small chunk out of the remaining pool?  I was hoping to keep the CPU's all busy, as I am processing logs from dozens of hosts, some of which have pretty large logs...  At least before this latest change, I was not able to process log data as fast as it is produced for our production servers, but in that case for whatever reason it was dropping all the way down to 1 core before it hit 50%...  I have thus far only deployed all the logging and other changes in our development environment (I have set up a separate pgbadger server in each environment).  I will keep working this up and hope for a better outcome.  Worst case, I can scale out to more pgbadger nodes in production.

Thank you for all the assistance, and sorry for too much unrelated noise on this ticket!
