### ISSUE TITLE
Progress indicator goes way over 100% for some log files

### ISSUE THREAD

**Issue by raptelan** [darold/pgbadger#459]
pgBadger's progress indicator never seems to finish at 100%.  It usually seems to stop in the mid 90's, but other times it goes over 100% by quite a bit:

```
[========================>] Parsed 5151637342 bytes of 958229234 (537.62%), queries: 7642159, events: 0vents: 0
LOG: Ok, generating HTML daily report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/11/30/...
LOG: Ok, generating HTML weekly report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/week-48/...
LOG: Ok, generating global index to access incremental reports...
  --> Processing file /srv/nfs/postgresql_logs/b-gp2-dbpgmgsrch2-1/2018-11-30_19.csv.gz...
[========================>] Parsed 8655240345 bytes of 335629349 (2578.81%), queries: 20287720, events: 0
LOG: Ok, generating HTML daily report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/11/30/...
LOG: Ok, generating HTML weekly report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/week-48/...
LOG: Ok, generating global index to access incremental reports...
  --> Processing file /srv/nfs/postgresql_logs/b-gp2-dbpgmgsrch2-1/2018-11-30_20.csv.gz...
[========================>] Parsed 10187691484 bytes of 1923510792 (529.64%), queries: 24424887, events: 0
LOG: Ok, generating HTML daily report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/11/30/...
LOG: Ok, generating HTML weekly report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/week-48/...
LOG: Ok, generating global index to access incremental reports...
  --> Processing file /srv/nfs/postgresql_logs/b-gp2-dbpgmgsrch2-1/2018-11-30_21.csv.gz...
[========================>] Parsed 6269485191 bytes of 2127923081 (294.63%), queries: 11517816, events: 0
LOG: Ok, generating HTML daily report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/11/30/...
LOG: Ok, generating HTML weekly report into /srv/nfs/pgbadger_reports/b-gp2-dbpgmgsrch2-1/2018/week-48/...
LOG: Ok, generating global index to access incremental reports...
  --> Processing file /srv/nfs/postgresql_logs/b-gp2-dbpgmgsrch2-1/2018-11-30_22.csv.gz...
[========================>] Parsed 3614310071 bytes of 227122003 (1591.35%), queries: 4893784, events: 0
```

Relatedly perhaps, while processing the logs from some servers, the queries count never increases beyond 0 although there are many queries logged in the file.  The PostgreSQL logging parameters are identical on all our servers, so that is not a factor.

**Comment by darold** [comment]
What version are you using? Is this last development code?

**Comment by raptelan** [comment]
pgBadger version 10.1 as packaged by Ubuntu 18.04

**Comment by raptelan** [comment]
I'm running pgBadger on logs from quite a few different servers, and this problem plagues a few specific servers, as does the query count of 0.  The PostgreSQL configuration is identical, so I guess it must have something to do with the way each database is used and the resulting log data.  Sorry I can't manage to narrow it down any better...

**Comment by darold** [comment]
Usually pgBadger is able to detect the uncompressed log size unless it is compressed with bzip2 or, in last development code when the compressed file is downloaded using http or ftp.

**Comment by darold** [comment]
Commit 28b7d7a, 6d9b8cb and 0ded137 might solve this issue. The first commit is related to csv files and other are for issues with files with estimate size (bz2 compressed files and remote compressed files).
