### ISSUE TITLE
Add ability to split log into multiple reports based on database name and hour

### ISSUE THREAD

**Issue by raptelan** [darold/pgbadger#460]
Feature requests:

1.  Just as incremental mode splits out data into reports based on the day and week, it would be really nice if we could look closer at one particular hour of a given day.

2.  When there are multiple databases hosted on a single database cluster, it would be ideal if we could have the option to split the data out into multiple per-database reports, while still being able to look at the whole cluster report.

Combined, it would be possible to have weekly, daily, and hourly reports for both database clusters and each individual database.  I think I could accomplish these by preparsing the log data and calling pgBadger multiple times, but I imagine this would require a lot more compute time to process...

**Comment by darold** [comment]
Report by database are now available. About report per hour this will not be done, I think you can use the binary file from incremental mode to generate a report with a filter on the hour you want.
