### ISSUE TITLE
Is it feasible to use pgbadger with 'logging_collector' off

### ISSUE THREAD

**Issue by dorbodwolf** [darold/pgbadger#464]
Is it feasible to use `pgbadger `with '`logging_collector`' off？
How about using  `pgbadger ` to output log statistics once a week?
My disk with 255GB SSD to store satellite image with `postgis`,  the disk can provide log space for the database for only one week.
here is my `postgresql.conf`:
```
#------------------------------------------------------------------------------
# ERROR REPORTING AND LOGGING
#------------------------------------------------------------------------------

# - Where to Log -

#log_destination = 'stderr'             # Valid values are combinations of
                                        # stderr, csvlog, syslog, and eventlog,
                                        # depending on platform.  csvlog
                                        # requires logging_collector to be on.

# This is used when logging to stderr:
#logging_collector = off                # Enable capturing of stderr and csvlog
                                        # into log files. Required to be on for
                                        # csvlogs.
                                        # (change requires restart)

# - When to Log -
log_min_duration_statement = 30  # -1 is disabled, 0 logs all statements
                                        # and their durations, > 0 logs only
                                        # statements running at least this number
                                        # of milliseconds
# - What to Log -
log_checkpoints = on
log_connections = off
log_disconnections = off
#log_duration = off
log_error_verbosity = default           # terse, default, or verbose messages
log_line_prefix = '%m [%p] %q%u@%d '            # special values:
                                        #   %a = application name
                                        #   %u = user name
                                        #   %d = database name
                                        #   %r = remote host and port
                                        #   %h = remote host
                                        #   %p = process ID
                                        #   %t = timestamp without milliseconds
                                        #   %m = timestamp with milliseconds
                                        #   %n = timestamp with milliseconds (as a Unix epoch)
                                        #   %i = command tag
                                        #   %e = SQL state
log_lock_waits = on                     # log lock waits >= deadlock_timeout
log_temp_files = 0                      # log temporary files equal or larger
                                        # than the specified size in kilobytes;
                                        # -1 disables, 0 logs all temp files
log_timezone = 'PRC'

# - Process Title -

cluster_name = '10/main'                        # added to process titles if nonempty
                                        # (change requires restart)

```
Any suggestions for my config settings for better performance?
I am grateful if any help.

yours dorbodwolf

**Comment by darold** [comment]
Hi,

Yes pgBadger is fully compatible with syslog output or stderr handle by system logging. Usually logging_collector is off by default on most distribution.

There is no problem of running pgbadger to report statistics once a week, the only limitation is the size of the log after one week. pgBadger is able to parse huge log file very quickly in multiprocess mode but some time it is better to generate reports each days. There is an incremental mode in pgBadger that combines the two reports. In this mode you can just execute pgbadger every day and it will automatically generate a cumulative report on weekly statistics. See `-I | --incremental` option for this mode. For example you can have a cron task running each nigth over your PostgreSQL log files:
```
    0 5 * * * /usr/bin/pgbadger -I -q /var/log/postgresql/postgresql-11.log* -O /var/www/pg_reports/
```
it will automatically generates daily and weekly incremental reports.

By giving the full log file to parse each time (`/var/log/postgresql/postgresql-11.log*`) you don't have to take care about log file that have already been parsed or those who have been renamed and compressed by logrotate. In this mode pgBadger will never parse a log twice, only new log or new part of the current log are parsed.

Regards,

**Comment by dorbodwolf** [comment]
thank you. I have days leaving for work, I will try it.
