### ISSUE TITLE
"414 Request-URI Too Large" when clicking Explain plan (explain.depesz.com)

### ISSUE THREAD

**Issue by cschwaderer** [darold/pgbadger#465]
I have a very complex nested query to analyze. I tried to copy&paste the relevant parts of the log file to [explain.depesz.com](http://explain.depesz.com) - but I always get a parsing error. Obviously, I'm somehow lost in the log file and selecting the wrong snippet.

I thought pgbadger with its auto-links might help. Actually, this was the only reason I tried pgbadger. However, I was disappointed. When clicking on `Explain plan`, all I got was `414 Request-URI Too Large` from them. Not really surprising, when trying to send a few hundred lines via GET param. That cannot work that way I think.

I don't know if explain.depesz.com is still actively developed. If yes, maybe you can work out a way with them to allow POST params without a limit. Or if not, you might think about forking their code or at least, replace the link with a short explanation why complicated queries cannot be analyzed that way :(

**Comment by darold** [comment]
You don't need pgbadger if you just want to send your explain plan to explain.depesz.com, a copy / paste from your log is enough. I guess that Hubert has put some limitation in the post size witch is normal, the main problem is that you plan is too big. I recommend you to install Pg-Explain on your own server, you will be able to post plan of bigger size. Pg-Explain is a Perl module that you can install and use just like in the official web site. You can download it from https://gitlab.com/depesz/Pg--Explain
