### ISSUE TITLE
File size limit? No Dataset for Slowest individual queries

### ISSUE THREAD

**Issue by leonardofaria** [darold/pgbadger#466]
Did anyone reach a file size limit here? 

Trying to run pgbadger (v. 10.2) with a 2.3GB log from AWS RDS and despite the queries are collected, no information is showing in the  Slowest individual queries section. Command:

```
pgbadger -f stderr -p "%t:%r:%u@%d:[%p]:" -o postgres-15.html postgresql.log.2019-01-16-15
[========================>] Parsed 2282052686 bytes of 2282052686 (100.00%), queries: 8330005, events: 11
LOG: Ok, generating html report...
```

Any advice here? 

Thanks

**Comment by darold** [comment]
Hi,

There should be a slowest queries report as pgBadger detect 8330005 queries. My guess is that you don't have log_min_duration_statement enabled.

Regards,

**Comment by mujz** [comment]
I'm having the same issue and the `log_min_duration_statement` is enabled. I have it set to `5000`. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/12049480/53439156-7c417e00-3a12-11e9-87a6-4a4ad5086c81.png)

So the queries are getting parsed, but the duration isn't. Any clues on why that might be happening?

**Comment by darold** [comment]
Please report your current PostgreSQL configuration with the following command:
```
grep "^log_" postgresql.conf
```
and your pgbadger command.

**Comment by mujz** [comment]
PostgreSQL engine version is 9.4.18
```
log_checkpoints: 1
log_error_verbosity: terse, default, verbose
log_line_prefix: %t:%r:%u@%d:[%p]:
log_min_duration_statement: 5000
log_statement: all
log_truncate_on_rotation 0
```

Tried both of these `pgbadger` commands:

```
pgbadger -f stderr -p "%t:%r:%u@%d:[%p]:" -o out.html out.log
pgbadger -p "%t:%r:%u@%d:[%p]:" -o out.html out.log
```

Thanks for taking a look!

**Comment by darold** [comment]
Well you have to set `log_min_duration_statement = 0` and `log_statement = 'none'` to have things working. Also it is better to enable others log information like:
```
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
```

**Comment by darold** [comment]
Of course if you want to limit the quantity of log you can set `log_min_duration_statement = 5000` but in all cases `log_statement = 'none'` must be set.

**Comment by mujz** [comment]
Ah gotcha. Thanks so much for the explanation!
