### ISSUE TITLE
Execution of function with insert operation is not recognized as INSERT

### ISSUE THREAD

**Issue by julianoparo** [darold/pgbadger#469]
Hi

I have a function called load_sar() that insert data into a table. This function is auto-executed as "SELECT load_sar();" every 15 minutes by pgagent but, it is not recognized as an insert operation on the chart "INSERT/UPDATE/DELETE Traffic". Is there any way to this operation being recognized as an insert by pgbadger?

Cheers!

**Comment by darold** [comment]
Hi,

Unfortunately not, pgBadger doesn't know about functions real action. We can probably add an option to be able to force the kind of query using a regexp, example: `--as-insert 'load_sar|load_iostat'` and same with update and delete statements. But for all functions that are doing all or several actions we have no solution. If you want such advanced information you'd better use pgCluu.

Regards,

**Comment by julianoparo** [comment]
OK, had a quick look on pgCluu and it looks cool, so, does it powerful like has all the options available from pgbadger?

Thanks and this question can be closed.

**Comment by darold** [comment]
This is not the same usage, you have much more information with pgCluu and especially you can correlate PostgreSQL use with system use. But pgCluu and pgBadger have the same developer so I guess that if something is missing posting a feature request here could help to improve the software :-)
