### ISSUE TITLE
similer No queries or events detected problem

### ISSUE THREAD

**Issue by dorbodwolf** [darold/pgbadger#476]
Hi Darold, Thank you for your great work on pgbadger, I have read your perl codes, its huge. I meet the similer no queries or events detected problem when I began to use it today. Here are my log samples, configs. Hope for your suggestions.
LOG file sample in `postgresql-10-main.log`:
> 2019-02-17 15:08:55.490 CST [19710] postgres@firstgis 日志:  执行时间: 71.729 ms 语句: SELECT pr.oid, pr.xmin, pr.*, pg_get_function_result(pr.oid) AS typname, typns.nspname AS typnsp, lanname, proargnames, pg_get_expr(proargdefaults, 'pg_catalog.pg_class'::regclass) AS proargdefaultvals, pronargdefaults, proconfig,        pg_get_userbyid(proowner) as funcowner, description,
>     (SELECT array_agg(label) FROM pg_seclabels sl1 WHERE sl1.objoid=pr.oid) AS labels,
>     (SELECT array_agg(provider) FROM pg_seclabels sl2 WHERE sl2.objoid=pr.oid) AS providers
>       FROM pg_proc pr
>       JOIN pg_type typ ON typ.oid=prorettype
>       JOIN pg_namespace typns ON typns.oid=typ.typnamespace
>       JOIN pg_language lng ON lng.oid=prolang
>       LEFT OUTER JOIN pg_description des ON (des.objoid=pr.oid AND des.classoid='pg_proc'::regclass)
>      WHERE proisagg = FALSE AND pronamespace = 2200::oid
>        AND typname NOT IN ('trigger', 'event_trigger')
>      ORDER BY proname
> 2019-02-17 15:13:43.546 CST [16761] 日志:  checkpoint starting: time
> 2019-02-17 15:13:49.215 CST [16761] 日志:  checkpoint complete: wrote 55 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.514 s, sync=0.054 s, total=5.669 s; sync files=2, longest=0.054 s, average=0.027 s; distance=154 kB, estimate=5613 kB

config file:

> # - Where to Log -
> log_destination = 'stderr'
> log_min_duration_statement = 30 
> # - What to Log -
> log_checkpoints = on
> log_connections = on
> log_disconnections = on
> log_error_verbosity = default       # terse, default, or verbose messages
> log_line_prefix = '%m [%p] %q%u@%d '  
> log_lock_waits = on         # log lock waits >= deadlock_timeout
> log_temp_files = 0          # log temporary files equal or larger
> log_timezone = 'PRC'
> # - Process Title -
> cluster_name = '10/main'  

 
the pgbadger cmd line:
`pgbadger -f stderr --prefix '%m [%p] %q%u@%d ' /var/log/postgresql/postgresql-10*`

**Comment by darold** [comment]
Hi,

pgBadger do not support messages localisation, you need to set `lc_messages = 'C'`  in your postgresql.conf.

Best regards,

**Comment by dorbodwolf** [comment]
yes, I just test it by created a temp file and it works!
