### ISSUE TITLE
how can i run pgbadger on windows

### ISSUE THREAD

**Issue by myzhen** [darold/pgbadger#480]
In addition to the perl environment whatI also need to install，how can i get them？thanks

**Comment by myzhen** [comment]
i do not want to use MSYS2

**Comment by darold** [comment]
Hi,

I don't know what is MSYS2 but pgBadger is build as a standalone Perl program so normally you just need Perl. The only limitation is that you will not be able to use multi-process mode and you should not be able to parse csvlog and jsonlog PostgreSQL log format. These two log format need additional Perl modules.

**Comment by myzhen** [comment]
tks
on windows, when i run pgbadger ,I get message is like 'awk' not find. the tools 'awk' is not installed on windwos , I should install it?

**Comment by myzhen** [comment]
on windows my step:
1. download sourcecode pgbadger10.3
2.perl Makefile.PL
3.gmake
4.gmake install

and i run follow command:
C:\Users\myzhen>pgbadger.bat -o C:\Users\myzhen\Desktop\a.html C:\Users\myzhen\Desktop\my-pg.log

I have been waiting for a long time and have not responded, it seems that the program is dead.

**Comment by darold** [comment]
Oh yes sorry, the awk and ls command are used to retrieve the file size I should have remember that. I think it could be possible to fix that for local parsing but I don't know about a windows command to get file size. Do you know one?

**Comment by myzhen** [comment]
sorry i also don't know，i download a MSYS2 and install. can work well.  I use it this way first, thank you for your script. it's good

**Comment by darold** [comment]
Good news. I will try to find a windows VM to work on portability without the need of MSYS2.

**Comment by myzhen** [comment]
that's great. waiting for your good news!
