### ISSUE TITLE
Documentation not wide enough

### ISSUE THREAD

**Issue by WoLpH** [darold/pgbadger#481]
When looking at the [options in the documentation](http://pgbadger.darold.net/documentation.html#SYNOPSIS) it's quite hard to read because it's only utilizing a small part of the screen.

If instead of using a `container` class on the parent div we would use a `container-fluid` class. And a `col-md-12` on the actual column, it would even fit on half a 1920x1200 screen properly without any need for scrolling.

**Comment by darold** [comment]
Thanks for the report. I have keep the existing formatting but move the line that was generating the scrolling from `pre` to `code` tag and remove `codè tag every where else. I also use `col-md-12` instead of `col-md-12`. Looks better for me.

**Comment by WoLpH** [comment]
Amazing, thank you. It looks much better now :)
