### ISSUE TITLE
Reports duplicate "slowest individual queries" with auto_explain logging

### ISSUE THREAD

**Issue by sdupre1961** [darold/pgbadger#492]
"Top/Slowest Individual Queries" Report seems to duplicate report "Query Text" of auto_explain and then regular report of INSERT - uses up the "top N" setting.

NOTE:  Related to https://github.com/darold/pgbadger/issues/413

so, pgbadger -t<n>
.... "top N" report slots can be used up by duplicated entries that are auto_explain'd.

pgbadger sees the statement and the auto_explain (below) as separate ... it's also a quirk in the auto_explain module of postgres (in my opinion) to report the query twice.

=== parameters used ===
log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
pgbadger -t10 -p <above>

=== simple log snippet ==
2019-04-15 10:03:19 EDT [9174]: [4-1] user=customer,db=customer,app=[unknown],client=10.54.48.14 LOG:  duration: 2909462.586 ms  plan:  
      Query Text:  Insert on public.foo  (cost=0.00..0.01 rows=1 width=4)
   ->  Result  (cost=0.00..0.01 rows=1 width=4)
         Output: 1
2019-04-15 10:03:20 EDT [9174]: [5-1] user=customer,db=custtomer,app=[unknown],client=10.54.48.14 LOG:  duration: 2910396.795 ms  statement:  INSERT INTO foo (bar) select 1

It's hard to tell what to key off of here too, since  (see above ) duration is shown as DIFFERENT  values for auto_explain and normal statement logging - PID is the same, etc. but still..

https://github.com/darold/pgbadger/issues/413 is similar and reports this behavior generally - as a secondary issue - at the bottom .. 

There is a note on #413  "Commit 20712f8 fixes this issue"... 

I think Commit 20712f8  may have fixed the mangled reporting output, but not the duplication

**Comment by darold** [comment]
I'm closing this issue, duplication can not be fixed with the current design of pgBadger.
