### ISSUE TITLE
how to exclude multiple users?

### ISSUE THREAD

**Issue by hunleyd** [darold/pgbadger#494]
I see that one can use `-U` to exclude a user, but how does one exclude multiple users? Do you use multiple `-U` args or pass a list to a single `-U`? Is said list space separated or comma separated?

Sorry if this is documented somewhere. I looked but didn't see anything?

**Comment by darold** [comment]
Yes you must use the `-U` or `--exclude-user` multiple time to exclude several users. I will fix the documentation, I keep the issue open until it is fixed.

**Comment by darold** [comment]
Documentation updated in commit 5c10824.
