### ISSUE TITLE
new feature: set the working hours without the day

### ISSUE THREAD

**Issue by massimosala** [darold/pgbadger#495]
example

>            --begin '08:00:00' --end '20:00:00'

**Comment by fluca1978** [comment]
I think this can be closed as of #501 .

**Comment by darold** [comment]
@massimosala Luca has implemented the feature, please use latest development code and let us know if there is any issues.

**Comment by massimosala** [comment]
Luca, many thanks for this new feature.

I am not sure to have time to try the beta version. Surely I will use the
next official release.

ciao, Massimo
