### ISSUE TITLE
Queries by type report

### ISSUE THREAD

**Issue by shurik88** [darold/pgbadger#496]
Off course I understand that it is not issue, but I have no options to solve my problem.

I'm using pgbadger to analize postgres logs. I see "queries by type" section and don't understand what means "others" category in table.
[my question in stackoverflow](https://stackoverflow.com/questions/55569052/report-queries-by-type-analysis)
I know only dml, ddl, tcl, dcl commands. DCL is absent in table, but Others is too huge to be only dcl.
Please tell me what queries are included in category "Others"?

**Comment by darold** [comment]
'COPY FROM', 'COPY TO' are used when you are importing and dumping tables from and to files.
'CTE' are Common Table Expression, WITH ... AS queries.

Others are all LOG messages that can not be categorized with ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'COPY FROM', 'COPY TO', 'CTE', 'DDL', 'TCL') keywords.

**Comment by shurik88** [comment]
Thanks for full answer!
