### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by klmansel** [darold/pgbadger#498]
There is a broken url in `CONTRIBUTING.md` to the "Read the doc" section. This link leads to a 404 page.

<img width="1280" alt="Screen Shot 2019-05-21 at 5 01 28 PM" src="https://user-images.githubusercontent.com/18410214/58130532-38fa4400-7bea-11e9-8a7c-9184555bf976.png">
<img width="1238" alt="Screen Shot 2019-05-21 at 5 02 59 PM" src="https://user-images.githubusercontent.com/18410214/58130567-50d1c800-7bea-11e9-9499-7646026b4e87.png">

**Comment by darold** [comment]
Hi,

Thanks for the report, commit 9f99cc6 solves this issue by pointing to http://pgbadger.darold.net/documentation.html.

Regards,
