### ISSUE TITLE
graphs, javascript and datetime, timezone offset: fix to calc default

### ISSUE THREAD

**Issue by massimosala** [darold/pgbadger#512]
We process the logs and publish the web pages, with nginx, on the same server.

In our script, calling pgbadger.pl, I wish to not set
     _--timezone          Set the number of hours from GMT of the timezone.
                                 Use this to adjust date/time in JavaScript graphs._

Without setting it, pgbadger calcs a "timezone offset", but it is incorrect.
I fix with this little change, it works also with DST.

pgbadger.pl 10.3, line 678
```
if (!$timezone)
{
	use Time::Local;
	my @lt = localtime(time);
# count TimeZone and Daylight Saving Time
	$timezone = timegm(@lt) - timelocal(@lt);
	print STDERR "WARNING: --timezone not specified, using $timezone seconds\n";
	$timezone = - $timezone;
}

```

Please I ask to review and merge this fix.
Best regards, Massimo

**Comment by darold** [comment]
Good catch Massimo, commit 16448c0 applies your fix.
