### ISSUE TITLE
rebuild does not work without report-per-database

### ISSUE THREAD

**Issue by tbe** [darold/pgbadger#514]
`--rebuild` does not generate any output without report per database. I found, that `%DBLIST` is empty at least at the point where `build_incremental_reports` is called, but could not find where it's cleared.

**Comment by darold** [comment]
Hi,

What command do you use? If I try to reproduce the problem with per database report:
```
perl pgbadger  --explode -I -O /home/git/pgbadger/report/ /data/pglog/multi-small-files/postgresql-2012-03-20_0[89]*
perl pgbadger  --explode -I -O /home/git/pgbadger/report/ --rebuild
```

or without, it is just working fine:
```
 perl pgbadger -I -O /home/git/pgbadger/report/ /data/pglog/multi-small-files/postgresql-2012-03-20_0[89]*
perl pgbadger -I -O /home/git/pgbadger/report/ --rebuild
```

If you can post a debug output using `-v` option it could help too.

**Comment by darold** [comment]
Does this issue can be closed? Otherwise please give additional the information I've asked.

**Comment by thomasLeclaire** [comment]
--rebuild tag use the content of tmp file $TMP_DIR/dblist.tmp which is fed only during some parsing of files. 

if you try for the example to use the rebuild param in a container where you never did some parsing without share the $TMP_DIR, the tmpfile is empty, and therefore rebuild won't work. 

workaround can be to create manually the tmp dblist file.
