### ISSUE TITLE
Report States "NO DATASET"

### ISSUE THREAD

**Issue by DanielAdeniji** [darold/pgbadger#520]
[reportFile.html.txt](https://github.com/darold/pgbadger/files/3479288/reportFile.html.txt)
[postgresql-2019-08-07_093413.log](https://github.com/darold/pgbadger/files/3479289/postgresql-2019-08-07_093413.log)
[postgresql-2019-08-07_141019.log](https://github.com/darold/pgbadger/files/3479290/postgresql-2019-08-07_141019.log)

[publishFile.cmd.txt](https://github.com/darold/pgbadger/files/3479294/publishFile.cmd.txt)

**Comment by darold** [comment]
This is the same as issue #505 , pgbadger is broken on Windows operating system. I'm sorry but I do not have the time to work on it for the moment. Best is to use it on Linux or to use an older version, https://github.com/darold/pgbadger/releases/tag/v9.2 works on window.

**Comment by DanielAdeniji** [comment]
Darold 

Sorry to create a duplicate issue.

Downloaded and validated that version 9.2 indeed works very well.

Please consider issue remedied.
