### ISSUE TITLE
Graphs timeline not match reality

### ISSUE THREAD

**Issue by birkosan** [darold/pgbadger#522]
Hello

I just saw that the graphs timeline have an offset compared to reality in logfile.
I tried to adjust with --timezone or --log-timezone but I just can't figured out.

I attached a screenshot ... you can see  the 1 hour offset of the query peak in the top Global Stats and the graph.
The correct one is in the Global Stats, the error is in the graph.

I have log_timezone = 'Europe/Bucharest' in the postgresql.conf

![pgbadger](https://user-images.githubusercontent.com/1405487/63229659-90b94300-c20b-11e9-9c04-e5951dacce73.png)

Thanks
Levi

**Comment by darold** [comment]
The problem with javascript graph is that they take the timezone of your browser, normally using `--timezone +02` should adjust graphs time series. What is your pgbadger command line?

**Comment by birkosan** [comment]
Indeed! As I remember I tried in the past few days with this parameter too... but it seems I don't.
Thank you!
Levi
