### ISSUE TITLE
avoid showing big queries (div scroll it instead)

### ISSUE THREAD

**Issue by ilisepe1** [darold/pgbadger#524]
Hello,

This is not an issue, it's just a recommendation.

There are cases where a query can be huge. It would be nice to show just the first 5-6 lines of a query (ie in "Slowest individual queries" page), to avoid "spamming" the whole page with these huge queries.

That seems to be easy just by adding the following css code in .sql-largesize:
max-height: 200px; overflow: auto;

(Tested it with ver 9.2, that we have in our company.)

Thanks
ilias

**Comment by darold** [comment]
Thanks Ilias, applied in commit e2d2b23.
