### ISSUE TITLE
Parsing troubles

### ISSUE THREAD

**Issue by tdavis** [darold/pgbadger#527]
I am having a hell of a time getting pgBadger to parse some logs. The logs are generated by GCP and I can't control the `log_line_prefix`, but I managed to construct what I _thought_ was a compatible format:

```
Sep 16 14:11:20 [104663]: [3-1] db=database-staging-7bde24ce,user=user-staging-0c486bec LOG:  duration: 879.786 ms  execute <unnamed>: SELECT ...
```

However, pgBadger parses the 8mb log file and finds a single (missing) query. My options are `--prefix '%t [%p]: [%l-1] db=%d,user=%u ' --format syslog`. Maybe I'm just really inept, but I have been tearing my hair out trying to find some combination of prefix/data that works to no avail. I mirrored the format after what I found in `pg-syslog.1.bz2` but... :man_shrugging:

**Comment by darold** [comment]
Hi Tom,

Can you tell me what is GCP and can you send me one or two log lines so that I can decide by myself what is the log_line_prefix that is used?

Regards,

**Comment by tdavis** [comment]
Sorry! GCP stands for "Google Compute Platform", it's just their IaaS thing. One such service is SQL, which you can set up to export logs. The exported logs are in JSON format, but the full text of the log message is what you see above, minus the date. I added the date in post-processing using a separate `timestamp` value comes with each entry. 

To get pgBadger to work, I had to further add a host and `postgres` in front of the process id so that each entry could exactly match the test data, allowing me to drop`--format`. I'm still curious why I am unable to make that option work, though.

**Comment by darold** [comment]
Tom if I ask you a log line from the source log this is not to have your interpretation of what should be done, this is to have my own interpretation :-) Please provide the full json log entry that report the message above. If pgBadger have to support the GCP log output I must work on the original and untouched format, not the one you are generating. If an entry can be multi-line please provide an example.

**Comment by darold** [comment]
Ok, I'm closing the issue without real log input line I don't want to waste more time on this problem.
