### ISSUE TITLE
Parsing queries not found and "DEBUG: Unknown stderr line format"

### ISSUE THREAD

**Issue by eacshm** [darold/pgbadger#529]
When ran command, works fine but don't get queries and events.  When ran with -vv show me DEBUR error in the subject.  I think that made something wrong.  I see checkpoins, connections, vacuum, but queries and events not.

pgBadger version 11.1
PostgreSQL 11

-- Config.
logging_collector = on
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
lc_messages = 'C'
log_min_duration_statement = 0 
log_autovacuum_min_duration = 0
log_destination = 'stderr'
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

-- Command
pgbadger --prefix '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h ' postgresql-Fri.log

-- ERRORS when debug used.
DEBUG: Unknown stderr line format: 	BEGIN
DEBUG: Unknown stderr line format: 	    SET client_encoding TO 'UTF8';
DEBUG: Unknown stderr line format: 	    SET search_path TO xyz;
DEBUG: Unknown stderr line format: 	    SET application_name = xyz';
DEBUG: Unknown stderr line format: 	    PERFORM set_var('app', 'xyz');
... Continue log

**Comment by darold** [comment]
Hi,

As you are using the default log_line_prefix of pgBadger you don't have to specify it at command line. Can you please post one or two lines of your log file? Especially those reported by the DEBUG mode. I thinks the log format doesn't correspond to what is expected.

**Comment by stvoidmain** [comment]
I'm on the same boat here...
DEBUG: Unknown stderr line format:      VALUES ($1, $2, $3, $4, $5, $6, $7)
Which corresponds to:
2019-10-18 14:06:40 UTC-5da9c6c2.84-LOG:  execute <unnamed>: INSERT INTO adminglobal."PersistedGrants" ("Key", "ClientId", "CreationTime", "Data", "Expiration", "SubjectId", "Type")

	VALUES ($1, $2, $3, $4, $5, $6, $7)

It seems like is a thing with Azure formatting the logs, right?

**Comment by darold** [comment]
Yes Azure log are not supported natively, you might try the add the following to your pgbadger command:
```
--prefix '%t-%c-'

**Comment by stvoidmain** [comment]
Thanks, that worked!

**Comment by simondobner** [comment]
Hi Darold,
I know this is closed, and happy to open another ticket, but I'm seeing the same issue with RDS logs. The HTML report is saying 'NO DATASET' for lots of components, and I ran pgbadger ( current version from github ) and got the same errors as above.

```
DEBUG: Unknown stderr line format: 	            UPDATE linkages.building_to_state SET link_supersede_date = '2017-02-14T10:00:00+00:00'
DEBUG: Unknown stderr line format: 	            WHERE secondary_record_id = '5922ac64b459027b169a64bd58286a2010e1e232'
DEBUG: Unknown stderr line format: 	            AND primary_record_id IS NULL;
```
