### ISSUE TITLE
[Information] Difference between sessions and connections

### ISSUE THREAD

**Issue by ThomasPoty** [darold/pgbadger#530]
Hello,
First, I would thank you for this project.
Then, I would like to know the difference between "sessions" and "connections".

For exemple : on the same report, I have 500,231 connections for the main user and I have 500,048 sessions for the same main user.
 
Could you help to understand?

Thanks

**Comment by darold** [comment]
Hi Thomas,

Sessions statistics are collected on disconnection log entry:
```
    ... =~ /disconnection: session time: ([^\s]+) user=([^\s]+) database=([^\s]+) host=([^\s]+)/
```
That means that if a connection is not closed on the same log file or same section of log if you are using multiprocess (option -j), the count of session will be different than the connection count. If log_disconnections is not enable in postgresql.conf then there will be no sessions statistics.

I hope this is more clear now.

Regards,

**Comment by ThomasPoty** [comment]
Hi Gilles,

Thanks for your reply.
So, is it correct to say that a session is just composed of a connection and a disconnection?

Many thanks

**Comment by darold** [comment]
Yes.

**Comment by Khareeb** [comment]
Hi, thank you for the explanation. What is the relationship between the `max_connections` configuration settings in Postgres and the measured number of connections and sessions in PgBadger then? How can you determine to which value you can set `max_connections` based on the generated reports?

**Comment by darold** [comment]
pgBadger reports the number of connection per seconds with an average of 5 minutes per default. You also have the Connection Peak that reports the peak of  connections on PostgreSQL. But best if too look at the simultaneous session reports, this is what can be compared to your max_connections setting.
