### ISSUE TITLE
What's mean <defunct> processes?

### ISSUE THREAD

**Issue by artful88533** [darold/pgbadger#531]
Hello!
Server specification:
CPU 40 cores
RAM 62G
SSD drives
Pgbadger 11.1 

I have 60 log files per hour (rotate every minute). And run pgbadger every hour with command:
`/usr/local/bin/pgbadger -j 32 -J 32 -I -f stderr -p '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h ' -L "/opt/logs/pg-master/files_for_parser.log" -O /opt/html/pg-master`

In the first some seconds of parsing, I see a high CPU load. After about 5% of parsing load only one-five CPU core. Why does parsing don't load 32 cores?

```
root@appodeals-pg-logs ~ # ps aux | grep pgbadg
jenkinsb 196940  1.2  0.0  65452 29172 pts/0    S+   11:15   0:07 perl /usr/local/bin/pgbadger -j 32 -J 32 -I -f stderr -p [%p] %t : [%l-1] user=%u,db=%d,app=%a,client=%h  -L /opt/logs/pg-master/files_for_parser.log -O /opt/html/pg-master
jenkinsb 196941  0.0  0.0  65048 26668 pts/0    S+   11:15   0:00 pgbadger logger
jenkinsb 198625 23.0  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198626 23.3  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198628 24.1  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198629 25.2  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198630 26.4  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198631 27.0  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198632 29.0  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198638 29.8  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198640 31.4  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198642 33.3  0.0      0     0 pts/0    Z+   11:24   0:07 [pgbadger parser] <defunct>
jenkinsb 198644 31.3  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198650 36.1  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198652 37.5  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198654 40.5  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198655 43.3  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198656 45.6  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198658 43.7  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198660 51.7  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198661 56.5  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198662 62.1  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198663 68.3  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198664 73.5  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198670 83.8  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198671 96.4  0.0      0     0 pts/0    Z+   11:24   0:06 [pgbadger parser] <defunct>
jenkinsb 198672  106  0.0  65716 27808 pts/0    R+   11:24   0:06 pgbadger parser
jenkinsb 198677  107  0.0  65716 27824 pts/0    R+   11:24   0:05 pgbadger parser
jenkinsb 198678  109  0.0  65716 27768 pts/0    R+   11:24   0:04 pgbadger parser
jenkinsb 198679  112  0.0  65716 27756 pts/0    R+   11:24   0:03 pgbadger parser
jenkinsb 198685  117  0.0      0     0 pts/0    Z+   11:24   0:02 [pgbadger parser] <defunct>
jenkinsb 198686  136  0.0  65716 27720 pts/0    R+   11:24   0:01 pgbadger parser
jenkinsb 198687  0.0  0.0  65584 27632 pts/0    R+   11:24   0:00 pgbadger parser
```

Also, what's mean messages `can not load incompatible binary data, binary file is from version < 4.0.`?
```
[========================>] Parsed 125943218 bytes of 125943218 (100.00%), queries: 201977, events: 468
LOG: Ok, generating HTML daily report into /opt/html/appodeals-pg-master/2019/10/10/...
can not load incompatible binary data, binary file is from version < 4.0.
can not load incompatible binary data, binary file is from version < 4.0.
can not load incompatible binary data, binary file is from version < 4.0.
```

**Comment by darold** [comment]
Defunct process are child processes that a have completed their task. The parent process is responsible of cleaning them either when it need an other child process either when all log files are parsed. So don't worry about these process they will be cleanup by pgbadger.

About your multi-process configuration you are trying to use `-j 32 * -J 32` = 1024 cores this is a bit too high :-)  If you have 60 files that you want to process in parallel just use `-J 32` and if you really want to use all your 40 cores set it to 40.

About the "can not load incompatible binary data, binary file is from version < 4.0." error this is because v4.0 is not backward compatible with binary files generated by previous version. If all your statistics in `/opt/html/pg-master` have been generated by version v4.0 then there is a bug.

**Comment by artful88533** [comment]
Thank you! 
Without `-j 32` 32 CPUs load in top)

How can I fix `can not load incompatible binary data, binary file is from version < 4.0` ?

**Comment by darold** [comment]
If your reports are well generated you can ignore these messages or if you don't want them to appears you have to remove the binary files (*.bin) in sub directories of /opt/html/pg-master/ before the date where you moved to pgBadger v4.0. If it is not possible you can use the attached script to test your binary files as follow:
```
find /opt/html/pg-master/ -name '*.bin' | xargs -i perl test_bin_compat.pl {}
```
[test_bin_compat.pl.gz](https://github.com/darold/pgbadger/files/3713699/test_bin_compat.pl.gz)

**Comment by artful88533** [comment]
Thanks for the script! I have found and deleted bad bin files.

I have another problem.
Parsing now quick. But generating html files is very slow.
For example:
60 files with size ~2G each file.
Parsing - 20 min.
`[========================>] Parsed 119613734881 bytes of 119613734881 (100.00%), queries: 31607790, events: 240`
Generating html - 1 hour
```
LOG: Ok, generating HTML daily report into /opt/html/pg-slave1/2019/10/14/...
LOG: Ok, generating HTML weekly report into /opt/html/pg-slave1/2019/week-42/...
LOG: Ok, generating global index to access incremental reports...
```

Can I speed up generating html files?

**Comment by darold** [comment]
I'm afraid not, you are building reports about 120GB of log, it takes time :-)

**Comment by artful88533** [comment]
I've solved this problem by increasing the time between parsing to 4 hours. I have enough space on disk for logs.
