### ISSUE TITLE
pgbadger   only create index.html file and also doesnt create any directory (in incremental mode)) 

### ISSUE THREAD

**Issue by tengilim** [darold/pgbadger#533]
Hi;

    I  didnt understand that but pgbadger doesn not create the report . I did all config any other pg server and it create a report even with directory like 2019 .. week etc... But on production  server it doesn't. It just generate a file - index.html. and  this report  shows nothing.

**my parameters:** 
log_destination = 'stderr'  (it request -f option also...)
log_checkpoints = on
log_connections = on
log_disconnections = on
log_duration = off
log_error_verbosity = dafault           # terse, default, or verbose messages
log_line_prefix = '%t [%p]: user=%u,db=%d,app=%a,client=%h '
log_lock_waits = on 
#log_statement = 'none'                 # none, ddl, mod, all
#log_replication_commands = off
log_temp_files = 0  
log_autovacuum_min_duration = 0 

**my command;**
/usr/bin/pgbadger -I  /pgV11Data/data/log/postgresql-14.log -O /var/lib/pgsql/11/backups/

How can I handle it?

thanx in advence

**Comment by darold** [comment]
It seems that `log_min_duration_statement = 0` is missing in your settings?

**Comment by tengilim** [comment]
I have set it like this:

log_min_duration_statement = 10000

**Comment by darold** [comment]
Well I guess that there is no statement or information in your log that is parsable by pgBadger. If this is not the case please post a log line sample here.

**Comment by tengilim** [comment]
now I have checked again and I saw that reports was generated. your guess is correct I think.  I will keep checking if somethigs wrong I will write here again. Thank u so much.
