### ISSUE TITLE
Ability to handle custom log messages

### ISSUE THREAD

**Issue by animulay** [darold/pgbadger#534]
Hi,

I'm looking for ways to handle postgres log files that have some extra fields in addition to the log message generated by log_line_prefix. The additional fields are a side effect of using a common syslog template.

Here is a sample format of the log messages:

<timestamp> <log-severity> <node-name> <node-ip-addr> <postgres-log-message>

Potential solutions / workarounds:

1. Fix syslog template
   This only helps with handling new logs.

2. Strip out the extra fields from the log file and feed the "cleaned up" log file to pgbadger.
    This works, but it requires an extra step.

3. I wish there was a way to notify pgbadger to skip/ignore certain fields from the logs.

It would be good to hear your thoughts.

Thanks in advance,

- A

**Comment by darold** [comment]
What are these custom fields, do you have an example? Also have you tried with `-f syslog2`?

**Comment by animulay** [comment]
Hi,

Thanks for the response.

> What are these custom fields, do you have an example?

Some background:
The postgres logs are generated via syslog. The first 6 fields in the following sample statements 
were added by the syslog (because it shares the template with other applications).

user1@pg ~ $ head -2 postgresql.log
2019-07-11T20:10:23.000000-07:00 level=info host=xxxx ip=a.b.c.d program=postgresql| [1-1] 2019-07-12 03:10:23.312 GMT      00000 5d27fa1f.12b8 LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-07-11T20:10:23.000000-07:00 level=info host=xxxx ip=a.b.c.d program=postgresql| [2-1] 2019-07-12 03:10:23.312 GMT      00000 5d27fa1f.12b8 LOG:  listening on IPv6 address "::", port 5432
--

> Also have you tried with -f syslog2?

I just tried the following command, but it did not work.
$ ./pgbadger/pgbadger postgresql.log -f syslog2 -j 2 --verbose -o report.html

Here is a sample debug output:
DEBUG: Unknown syslog line format: 2019-10-07T17:24:57.000000-07:00 level=info host=xxxx ip=a.b.c.d program=postgresql| [7-4] 	buffer usage: 110 hits, 0 misses, 2 dirtied
--

On the other hand, as I mentioned earlier, the following 2-step process did the trick.

1. Remove the syslog generated extra fields.
$ cut -d' ' -f7- postgresql.log > postgresql2.log

2. Feed the resulting log file to pgbadger.
$ ./pgbadger/pgbadger --prefix '%m %r %u %a %d %i %e %c ' postgresql2.log --verbose -j 2 -o foo.html

- A

**Comment by darold** [comment]
Well I have no solution for your logs. Instead of changing your syslog output you should use the default and add additional information from log_line_prefix as explained in the documentation. pgbadger supports syslog and rsyslog default format, if you change these format you have to use a script to transform the log before sending it to pgBadger as you are doing. pgBadger already supports custom PostgreSQL log format it can not also support custom syslog format :-)
