### ISSUE TITLE
Unmatched ( in regex; marked by <-- HERE in...   from RDS logs

### ISSUE THREAD

**Issue by simondobner** [darold/pgbadger#536]
Hi darold,

`➜  pgbadger --version
pgBadger version 11.1`

I'm pointing pgbadger at downloaded RDS logs with the following command

`➜  error pgbadger -p "%t:%r:%u@%d:[%p]:" postgresql.log.2019-10-15-00   -o t2.html
Unmatched ( in regex; marked by <-- HERE in m/^(?:\d+-\d+-\d+T\d+:\d+:\d+\.\d+Z)?\s*(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)\s*[^:]*:( <-- HERE [^\(:]+\(\d+\):([^\@]+)\@([^:]+):\[(\d+)\]:(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})(?: [A-Z\+\-\d]{3,6})?:([a-zA-Z0-9\-\.]+|\[local\]|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|[0-9a-fA-F:]+)?[\(\d\)]*:([0-9a-zA-Z\_\[\]\-\.]*)@([0-9a-zA-Z\_\[\]\-\.]*):\[(\d+)\]:(LOG|WARNING|ERROR|FATAL|PANIC|DETAIL|STATEMENT|HINT|CONTEXT|LOCATION):\s+(.*)/ at /usr/local/bin/pgbadger line 2430.`

my log line prefix is as

`
=> show log_line_prefix;
  log_line_prefix
-------------------
 %t:%r:%u@%d:[%p]:
(1 row)
`

I saw a recent post on SO - https://stackoverflow.com/questions/58139442/what-is-the-correct-pattern-for-pgbadger-to-match-rds-logs - with the same problem.

**Comment by simondobner** [comment]
OK, I can confirm that it's working in the current github code

```
➜  pgbadger git:(master) ./pgbadger -p "%t:%r:%u@%d:[%p]:" ~/Downloads/postgresql.log.2019-10-22-04   -o t2.html
[========================>] Parsed 302304 bytes of 302304 (100.00%), queries: 1, events: 0
LOG: Ok, generating html report...
```
Thank you.

**Comment by giskarda** [comment]
Would it be possible to cut a new release so new rpm packages can be created? thank you in advance

**Comment by darold** [comment]
Hi Riccardo,

Next release will be published once I found time to fix Windows port, unfortunately I am very busy and cannot find spare time to work on it. I will do my best to work on it this month.

Best regards,
