### ISSUE TITLE
Too many open files / Wiki Information

### ISSUE THREAD

**Issue by mcsaygili** [darold/pgbadger#541]
Just in case of getting this error you should increase OS limits. 

If you are using ubuntu this configuration is under /etc/security/limits.conf
```
root soft nproc 20470
root hard nproc 163840
root soft nofile 10240
root hard nofile 655360
```
This process is actually the responsibility of system administrators, but does not hurt to add information to the readme. :)

DB Log file size ~10 GB
Parallel processing create 1045 files under /tmp

Error Example
```
[========================>] Parsed 10441024553 bytes of 10441024553 (100.00%), queries: 1907172, events: 602
FATAL: can't open temp file /tmp/tmp_pgbadger4IKD.bin, Too many open files
```

Best Regards

**Comment by darold** [comment]
What is your pgbadger command line?

**Comment by mcsaygili** [comment]
Here, 
```
pgbadger \
        -f stderr \
        -I /opt/database/db_data/dev/log/postgresql-*.log \
        -O /var/lib/docker/volumes/apache_kktc-report-www/_data/db/dev \
        -o index.html \
        --exclude-query "^(SELECT 1)" \
        -T "Prod DB" \
        -X \
        -j 4
```

**Comment by darold** [comment]
There is only 4 parallel processes which mean 4 temporary files per log file, how many files are concerned by `/opt/database/db_data/dev/log/postgresql-*.log`?

**Comment by mcsaygili** [comment]
1007 log files under the directory and continue to increase.

```
ls | wc -l
1007
```

**Comment by darold** [comment]
You might want to parallelize one process per file not multiple processes for one file. Use `-J 4` (uppercase J)  instead of `-j 4` (lowercase j).

**Comment by darold** [comment]
Saying that, this will not solve the problem of temporary file so increase max open file is the solution in this case.

**Comment by mcsaygili** [comment]
I'il try and let you know. Thank you for your interest.

**Comment by mcsaygili** [comment]
Nope still same error.  Increasing max open file is the solution i think. Btw -J (uppercase j) is more faster then -j (lowercase j) you mentioned before if you have a lot of log files.

**Comment by darold** [comment]
Yes this is really faster if your log file are small and I guess that this is your case. I don't know why you have 1000+ log file, but you might tune your postgresql.conf to have bigger log file.

**Comment by mcsaygili** [comment]
I have many log files because its 20 days files :) I upgrade postgres 10.3 to 11.5 and i dont want to lose log files so i kept :) Now i have over 40-50 log file and i have 20 days historical pgbadger analysis :) Thanks
