### ISSUE TITLE
'About' and 'Latest Release' concide with each other on web site.

### ISSUE THREAD

**Issue by sudo-batman** [darold/pgbadger#542]
On pgbadger.darold.net/
'About' and 'latest release' tag are on top of each other. On on small screen the alignment are not proper.
![issue](https://user-images.githubusercontent.com/23376158/68488654-8e471200-026b-11ea-8af4-564963d047f5.JPG)

This happens on both chrome and Firefox.

**Comment by darold** [comment]
Thanks for the report. If anyone can help to fix it please send a patch.

**Comment by darold** [comment]
Found a simple workaround failing to do this properly.
