### ISSUE TITLE
pgbadger on windows using strawberry perl

### ISSUE THREAD

**Issue by jrobert83** [darold/pgbadger#548]
Hi, 
I am trying to use pgbadger on windows (sorry, nobody's perfect) and I get stuck in a error:

When I type in: perle.exe pgbadger (in pgbadger folder), I got the following errors:
Possible unintended interpolation of @temp_content in string at pgbadger line 17434.
Can't modify division (/) in division (/) at pgbadger line 17430, near "1;"
Global symbol "$object" requires explicit package name at pgbadger line 17434.
Global symbol "$object" requires explicit package name at pgbadger line 17434.
Global symbol "$something" requires explicit package name at pgbadger line 17434.
Global symbol "$new_value" requires explicit package name at pgbadger line 17434.
Global symbol "$new_value" requires explicit package name at pgbadger line 17434.
Global symbol "$new_value" requires explicit package name at pgbadger line 17434.
Global symbol "$i" requires explicit package name at pgbadger line 17434.
Global symbol "@temp_content" requires explicit package name at pgbadger line 17434.
syntax error at pgbadger line 17459, near "my @temp_content = split(/("
pgbadger has too many errors.

**Comment by darold** [comment]
Current port to Windows is broken, if you can't use a Linux box pgBadger version 9.x should work if I remember well.

**Comment by jrobert83** [comment]
Yep, just checked, v9.2 is working on windows.

**Comment by jrobert83** [comment]
Are you planning to get the windows part working again in a new version ? That would be great !

**Comment by darold** [comment]
Yes next version will have it.

**Comment by jrobert83** [comment]
Great news ! Thanks for you time !
