### ISSUE TITLE
Issues with viewing statistics from AWS RDS database log

### ISSUE THREAD

**Issue by dgorbov** [darold/pgbadger#550]
pgBadger version 11.1
AWS RDS postgre 9.6.11
log_min_duration_statement = 1 and log_statement = 'none'

$ pgbadger postgresql-example.log
[========================>] Parsed 1412 bytes of 1412 (100.00%), queries: 0, events: 0
LOG: Ok, generating html report...

In result report out.html -> NO DATASET for all blocks

Log file in attachments. 
[postgresql-example.log](https://github.com/darold/pgbadger/files/3951539/postgresql-example.log)

Same results with file that contains 30k+ queries and 35mb of size

I've tried different options plus also version 10, no luck.
Thank you in advance

**Comment by darold** [comment]
Hi Dmitry,

This is because only bind part of the prepare/bind/execute is logged, pgBadger need the three parts in the log or at least the execute. I will check if we can compute statistics just using bind part.

Regards,

**Comment by giskarda** [comment]
Hi,

I can see the same behaviour with rds / pgsql 11.5.  Another thing is that it seems not be able to parse users either.

For what is worth it works  fine with pgbadger version 9.x

I'm not sure what kind of information you need from me to help you with the issue. I'll be welcome to provide support in case!

Thank you very much,
R

**Comment by darold** [comment]
Commit  8c61758 fixes a bug in the RDS log parsing which might solve this issue.
