### ISSUE TITLE
report without queries/events - "DEBUG: Unknown stderr line format" 

### ISSUE THREAD

**Issue by marielcherkassky** [darold/pgbadger#551]
postresql 12
pgbadger 11.1
```
postgres#= show log_line_prefix;
         log_line_prefix
---------------------------------
 db=%d,user=%u,app=%a,client=%h
(1 row)
```
logging settings in pg :
```
log_checkpoints = on
log_lock_waits = on
log_temp_files = 1024
log_connections = on
log_disconnections = on
log_min_duration_statement = 0
log_autovacuum_min_duration = 0
```
```
/usr/bin/pgbadger --prefix 'db=%d,user=%u,app=%a,client=%h' postgresql-Mon.log
FATAL: unable to detect log file format from postgresql-Mon.log, please use -f option.
```
Tried also to run : 
```
/usr/bin/pgbadger -f stderr --prefix 'db=%d,user=%u,app=%a,client=%h' -v postgresql-Mon.log
```
all rows have the same following msg : 
```
DEBUG: Unknown stderr line format: query1
DEBUG: Unknown stderr line format: query 2
DEBUG: Unknown stderr line format:      Connection matched pg_hba.conf line 67: 
....
```

**Comment by darold** [comment]
You are using the prefix for syslog log destination. You should set log_line_prefix to `%t [%p]: db=%d,user=%u,app=%a,client=%h` this is the default for stderr log destination.

**Comment by marielcherkassky** [comment]
I want to analyze logs that had the following prefix : db=%d,user=%u,app=%a,client=%h .
Isnt it optional ? why do I need to specify the -f flag with stderr, the prefix isnt enough ?

**Comment by darold** [comment]
You can not, you need at least a timestamp and the pid which are not in your prefix. The -f flag is necessary because you didn't use the default one for stderr log destination and pgbadger is unable to auto-detect the log format because of the timestamp and pid missing. The default must be:
```
log_line_prefix = '%t [%p]: db=%d,user=%u,app=%a,client=%h '
```
In this case you don't have to use the -p option of pgbadger. All of this is better explained in the documentation.

**Comment by marielcherkassky** [comment]
I see, thanks !
