### ISSUE TITLE
[DOC] Explaining different type of logging structure

### ISSUE THREAD

**Issue by tpoindessous** [darold/pgbadger#557]
Hi !

I want to use PgBadger with GCP CloudSQL logging. For the moment, this format is not supported (I will submit another issue ).

I wanted to convert CloudSQL logs to a supported format, I saw several logs formats in PgBadger documentation but I can't find explanation (or examples) about those logs formats.

Could you please, add examples or explanation of different types of logs formats ?

Thanks !

**Comment by darold** [comment]
Hi,

There is internal supported format to avoid having to set the prefix at command line, otherwise yiou just have to set the prefix using -p option. Can you please post the value of the log_line_prefix used by GCP CloudSQL ? I will see if it can easily be auto detected.

Regards,

**Comment by darold** [comment]
Any chance to have this log_line_prefix information? A `SHOW log_line_prefix;` query might do the job.
