### ISSUE TITLE
Incremental reports ignoring year change

### ISSUE THREAD

**Issue by FabioPereira666** [darold/pgbadger#559]
I have found an issue when using incremental (-R) option. The script is not dealing with year change.
I have re-written a small part to fix it. (next to line 1300)
How can I send the changed code?
Regards,
   Fabio.

**Comment by darold** [comment]
Hi Fabio,

If you are not familiar with git, you can just post here  the diff -u with the original file. Otherwise the preferred way is to create a pull request, you will have to clone the project in github.

**Comment by FabioPereira666** [comment]
Thanks for your time.
   Here is the output of diff -u:

diff -u 20190916-pgbadger-orig pgbadger
--- 20190916-pgbadger-orig      2019-09-16 11:02:34.000000000 -0300
+++ pgbadger    2020-02-07 07:33:30.259762668 -0300
@@ -1288,7 +1288,6 @@
                }
        }
 }
-
 # Clear storage when a retention is specified in incremental mode
 if ( $outdir && $retention && ($saved_last_line{datetime} || $pgb_saved_last_line{datetime}) ) {

@@ -1298,9 +1297,23 @@
                # Search the current week following the last parse date
                my $limit = $1;
                my $wn = &get_week_number($1, $2, $3);
-               if (($wn - $retention) < 1) {
-                       $limit--;
-                       $limit .= "52";
+# ################################### #
+                my $My_Diff_Weeks = ($wn - $retention);
+               if (($My_Diff_Weeks) < 1) {
+# ################################### #
+# ***************              if (($wn - $retention) < 1) {
+
+
+# ################################### #
+                $My_Diff_Weeks = -($My_Diff_Weeks);
+                my $My_Years = int($My_Diff_Weeks / 52)+1;
+                $limit -= $My_Years;
+                $limit .= (52-$My_Diff_Weeks);
+                &logmsg('DEBUG', "Directories and files older than <$limit> will be removed");
+# ################################### #
+
+# ***************                      $limit--;
+# ***************                      $limit .= "52";
                } else {
                        $limit .= sprintf("%02d", $wn - $retention);
                }



Regards,
   Fabio.

**Comment by FabioPereira666** [comment]
Here is the "diff -u" output file attached.

Regards,
   Fabio.
[202002-pgBadger-Diff-u.txt](https://github.com/darold/pgbadger/files/4170286/202002-pgBadger-Diff-u.txt)

**Comment by darold** [comment]
Commit 1b5180c might fix this issue. Thanks, I have modified a bit your patch to handle years with 53 weeks.
