### ISSUE TITLE
pgbadger swaps out from running 1GB logfile

### ISSUE THREAD

**Issue by cleverKermit17** [darold/pgbadger#560]
hello friends
after setting up app in my logformat of pg10, i cannot run a proper pgbadger report anymore. it crashes - i logfiles that rotates every hour and average size is 1GB, with lots of very long queries in them. Ive setup incremental mode, but pgbadger fails to parse the files. usually it almost complletes but hangs for hours until it writes out "

> DEBUG: Saving last parsed line into XXXXX"

 (due to the -l param).

now the perl process is the one hanging for the longest, and from truss on the process i got
```
wait4(-1,{ SIGNALED,sig=SIGFPE },WNOHANG,0x0)    = 0 (0x0)
nanosleep({ 1.000000000 })                       = 0 (0x0)
```
-for extremely many times until i had to terminate the consoleprocess manually. Sometimes pgbadger would cause all the swap space to be used, and crashing eveything. My server has 16GB memory and 4GB Swap space.

ive tried setting maxlength to 500, but it doesnt help - as i though well it might be due to the process consuming too much memory due to huge queries.

my options for pgbadger is the following:
` -q \
-I \
-j 5 \
-s 5 \
-t 10 \
--maxlength 4000 \
-U postgres \
-l "/path-to-my-dir/last-parsed" \
-X \
--pid-file "pgbadger-my.pid" \
--disable-checkpoint \
--start-monday \
-T "production: my name" \
-O "/path-to-my-dir/html-reports`

i run multible instances with the same logfile format, only these two huge-query producing instances are the ones crashing pgb, the others run smoothly.

ive considered if it helps to explicitly define logfileformat in the option-list. Does anyone have a clue what one could do?

cheers and thanks

**Comment by cleverKermit17** [comment]
i run pgBadger version 11.1 by the way..

**Comment by cleverKermit17** [comment]
anyone ? -i can add that i have alot of geospatial queries to be analyzed, and it could seem that this is exhausting for memory.

**Comment by darold** [comment]
If you can send to my private address < gilles AT darold DOT net > a link to download a log it will be helpful. Otherwise I don't see what happen, `--maxlength` should truncate the query so you might not experienced this problem. I can not reproduce it with my test.

**Comment by cleverKermit17** [comment]
Thanks Darold,
but due to the strict GDPR related ruling, i cannot distribute you our logfiles, not even snippets, unless i completely screwed them over in an anonymizing-crusade which would make them useless to the parser right. so i hope we can go about me answersing to your qualified questions?

Since past message ive extended swap space from 4 to 16 GB and now i can parse the files that cause a server stall earlier. Take note that these files are everything from 400~1000MB large - so rather small in other words, however the queries are highly complex and long. Now logfiles are parsed successfully, however they are really slow to pass through (not suprisingly since they swap so much). At the moment the parser has been hanging with a tiny 28MB logfile for 30 minuts - thats says it all, the logfile has 183.000 loglines - it seems that pgbadger has a writer and a reader process and the read is the one hanging (atleast using truss -p on each process reveals that the writer spews output and the reader occationally says something). Maybe some of this points you to a place in your program where it could be running wild.. being a perl programmer since 2010 or so, i know perl can be absorbing memory like crazy, but having a 28MB logfiles swapping out seems suspicious.


Ive notived the perl script does drop this 

> openat(AT_FDCWD,"/path/to/my/files/index.html",O_WRONLY|O_CREAT|O_TRUNC,0666) = 5 (0x5)
ioctl(5,TIOCGETA,0x7fffffffe370)                 ERR#25 'Inappropriate ioctl for device'
lseek(5,0x0,SEEK_CUR)                            = 0 (0x0)
fstat(5,{ mode=-rw-r--r-- ,inode=17014278,size=0,blksize=32768 }) = 0 (0x0)
fcntl(5,F_SETFD,FD_CLOEXEC)                      = 0 (0x0)

Some perl mongers think this (ian ioctl for device) is rogue perl bug that is not important to the runtime. Thought i'd mention it anyway - this particularly is dropped right before everything ends (efter reports have been genereted), but is trapped a number of times through the process.

Ive also noticed that perl does drop this in the very end of the parsing:
> stat("/usr/share/nls/C/libc.cat",0x7fffffffddd8) ERR#2 'No such file or directory'
stat("/usr/share/nls/libc/C",0x7fffffffddd8)     ERR#2 'No such file or directory'
stat("/usr/local/share/nls/C/libc.cat",0x7fffffffddd8) ERR#2 'No such file or directory'
stat("/usr/local/share/nls/libc/C",0x7fffffffddd8) ERR#2 'No such file or directory'
getpid()                                         = 19966 (0x4dfe)
getpid()                                         = 19966 (0x4dfe)
close(4)                                         = 0 (0x0)
stat("/tmp/tmp_pgbadgerIQUk.bin",{ mode=-rw------- ,inode=5296898,size=0,blksize=32768 }) = 0 (0x0)
chmod("/tmp/tmp_pgbadgerIQUk.bin",0600)          = 0 (0x0)
lstat("/tmp/tmp_pgbadgerIQUk.bin",{ mode=-rw------- ,inode=5296898,size=0,blksize=32768 }) = 0 (0x0)
unlink("/tmp/tmp_pgbadgerIQUk.bin")              = 0 (0x0)
getpid()                                         = 19966 (0x4dfe)
getpid()                                         = 19966 (0x4dfe)
getpid()                                         = 19966 (0x4dfe)
getpid()                                         = 19966 (0x4dfe)
close(3)                                         = 0 (0x0)
openat(AT_FDCWD,"/dev/dtrace/helper",O_RDWR,00)  ERR#2 'No such file or directory'
exit(0x0)
process exit, rval = 0

Seems that some libC files are required, however, i dont know if this is needed at all ?

I also should mention i have been running pgbadger steadily for years without a single problem, but one month ago we changed logformat to include applicationname, following pgbadger advices we implemented log prefix in postgres, and since that time it became chaos..

ps. i've tried parsing the **--maxlenth 500 option** earlier, but it didnt help a tad, still stalling. It doesnt say but i figure maxlength is the length of the query in number of chars used.

**Comment by darold** [comment]
Ok, is it possible to just have one line of log to see if you are using the right prefix?

**Comment by cleverKermit17** [comment]
Now thats a good idea.. i have tampered the content a bid, just in case someone wouldnt find it appropriate, and so all content is obscured, and if you like GIS data this polygon wouldnt make much sense, but get the gist from whats going on. This is a complete logline..
Postgres version is 10.5 with no customization besides postGIS.

`2020-02-13 11:59:50 CET [1500]: [7-1] user=u123,db=d123,app=[unknown],client=127.0.0.1 LOG:  duration: 0.719 ms  bind <unnamed>: select encode(ST_AsBinary(ST_Force2D("wkb_geometry"),'LKR'),'hex') as geom,"ogc_fid" from schema1.table1 where wkb_geometry && ST_GeomFromText('POLYGON((722934.399999616 5172323.12922844,922934.239999616 2253955.79997932,724566.679959535 4173925.68992932,224566.689999535 9872323.69997844,322334.573959616 2172323.45997844))',76849)`

cheers

**Comment by cleverKermit17** [comment]
im currently having a 320MB logfile that took 7+ hours to process swapping more than 10GB - it makes no sense at all.

can it have something todo with complex postgis functions inside the queries ?

**Comment by darold** [comment]
Just though about one thing, can you try with option `--no-prettify`? The performances lost could be related to the SQL code beautifier.

**Comment by cleverKermit17** [comment]
so i tried this latest advice, but after two hours runtime for a 300MB logfile, i killed the process. It did however produce 11GB of swapping - thats insane.. but then i noticed that it did commit stuff into the .bin file used, so i could view graphs and stuff on the web. I cant verify if everything is there, and i dont know how you commit to the bin file (your perlscript i rather large, and it would take a little while to comprehend it end to end). My logfiles rotate hourly and i could see this one committed for the last minute of that logfiles hour, so thats good, maybe then its comparing to other stuff in other bin files thats taking up all this memory ? You know best..

For this run i tried the `--no-prettify` option, and i also tried to hint with the prefix option: `--prefix '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '`

im running out of options it seems

**Comment by darold** [comment]
What id committed to the bin file in the "objects" in memory after the parsing. This is done in method dump_as_binary(). Once all binaries are generated from the log parsing, pgbadger build the statistics by rereading those files from method load_stats() and reimport in memory the objects containing stats.

What could take very long time and use lot of memory in incremental mode could be the build of weekly reports, step "LOG: Ok, generating HTML weekly report into ...". If this is the case, can you please give a test to latest development code, commit 7952e38 adds option `--no-week` to disable this cumulative report over the week. This will prevent loading all binary files from the week into memory. Let me know the results.

**Comment by cleverKermit17** [comment]
right on Mr. Darold, i saw you made that commit based on this issue, thank you very much Sir, - i have tried it out, and it vaporized runtime into 2-3 minutes with no swapping issue at all, for the same file that would swap into 20GB and run for half a day..
    `--no-week` does the trick, and the weekly reports we can live without :)

as i run on FreeBSD, i am going to collect it from ports whenever someone decides to commit it overthere, but for now we are saved and full of thanks to your time and effort.

c'est compliqué - Vive la France

**Comment by darold** [comment]
Thanks for the feedback, I will try to get out a new release before the end of the month.
