### ISSUE TITLE
"unknown" database and user take the brunt of the stats

### ISSUE THREAD

**Issue by nodje** [darold/pgbadger#561]
New user here.

I've ran pgbadger on the stats collected overnight simply with `pgbadger -I -q -f stderr` over ssh.
All good, but there's this `unknown` user & databse that show up everywhere and get the brunt of the queries.

Trying to find it in the `stderr` logs, I could only find this type of connection logs actually using it:
`[unknown]@[unknown] LOG:  connection received` 
And only about ~1500 matches, where I get like ~300,000 queries referenced by `unknown` as a user.

Everything should be either default `postgres` or a user database.

Is there anything wrong in my postgres logs?

**Comment by darold** [comment]
Hi, this is because you don't have %u and %d in the log_line_prefix configuration directive. In this case pgBadger will use "unknown" as user and database name for all queries executed on a connection.

See documentation about the log_line_prefix tha pgbadger can use.

**Comment by nodje** [comment]
Hi, thanks for your prompt answer.
Actually, the default for a postgres v12 install is `log_line_prefix = '%m [%p] %q%u@%d '`
This is what I have, so the user and database are specified.

But that rings a bell, I should probably use `--prefix '%m [%p] %q%u@%d ' to make sure pgBadger knows how to read the log_line_prefix.

And thanks for this fantastic piece of software!
