### ISSUE TITLE
part of the SQL request code is missing

### ISSUE THREAD

**Issue by did16** [darold/pgbadger#562]
Hi
This is what I get in my pgbadger report "slowest individual queries":
>>
 LEFT JOIN egw_preferences ON egw_preferences.preference_owner = egw_accounts.account_id WHERE account_lid = $1 AND preference_app = 'obs_backlog'; 
<<
part of the SQL request code is missing.
when i search the log file i find:
>>
2020-02-14 14:44:29 CET [38802]: [438-1] [0] user=egroupware,db=egroupware,client=noe00aqs.noe.edf.frLOG:  00000: execute pdo_stmt_00000022: **SELECT preference_value FROM egw_accounts**
                        LEFT JOIN egw_preferences ON egw_preferences.preference_owner = egw_accounts.account_id
                        WHERE account_lid = $1 AND preference_app = 'obs_backlog'
<<

**Comment by darold** [comment]
What is your pgbadger command line?

**Comment by did16** [comment]
My pgbadger command :
pgbadger --dbname "observer"  --jobs 4 --begin "2020-02-14 00:00:00"   --end "2020-02-16 23:59:00" --title "Rapport OBSERVER 16-02-2020" --outfile rapport_OBSERVER_16-02-2020.html postgresql.log*
moreover the SQL request is executed on another database : db=egroupware while I had specified the database observe

**Comment by darold** [comment]
You should have a look to pgbadger documentation about log_line_prefix and log_statement versus log_min_duration_statement.
