### ISSUE TITLE
Very long queries truncated despite "no truncate" default

### ISSUE THREAD

**Issue by nodje** [darold/pgbadger#563]
Hi,

I see the truncate option in the doc:
```
-m | --maxlength size  : maximum length of a query, it will be restricted to
                             the given size. Default: no truncate
```
and also that by default it doesn't truncate, but still, I get very long queries truncated.

I can also see that it's not truncated in the logs.

FYI truncated to ~10489 char with last chars replaced by `[...]`
while in the logs the query runs 39713chars.

**Comment by darold** [comment]
Right actually query are truncated to 10480 characters by default, the documentation is not up to date. Commit fd1f62d fix the documentation. If you want no query truncate at all you can set `--maxlength 50000`
