### ISSUE TITLE
Encoding problems for asian chars in queries

### ISSUE THREAD

**Issue by nodje** [darold/pgbadger#564]
Hey,

i've tried to follow your advice and use `lc_messages = 'C'` in postgres conf, but since I was having encoding issues, I returned to the default `lc_messages = 'en_US.UTF-8'` set by the system.

With this in place (not entirely sure, but suspect the UTF-8 is needed to support Asian script in postgres log, though `C.UTF-8` would probably be working and follow your recommendations, wouldn't it?), I get proper logs in postgres (i.e. `UPPER('%谢%')`) that get garbled in html reports ( `LIKE UPPER('%è°¢%')`

I'm running pgbadger with ssh, so I suppose the client machine local config could play a role. Though it's `'en_US.UTF-8'` on both sides.

**Comment by darold** [comment]
Commit 761e6da update documentation, `lc_messages = 'en_US.UTF-8'` is perfectly valid. Perhaps one of the pgbadger evolution should be to support any lc_messages locale.

**Comment by nodje** [comment]
ok, then where could the encoding corruption possibly happen?

As far as I can test, `scp` a file containing asian script to the local server where pgadger does the parsing keeps the encoding clean.

**Comment by nodje** [comment]
I got it working.
I just deleted the existing reports and re-ran on the entire log base with the `--maxlength 50000` that you advised in the other issue and now the encoding is proper.
Don't know what happened, sorry about the trouble.

Closing this now, thanks.
