### ISSUE TITLE
pgbadger swapping and very slow

### ISSUE THREAD

**Issue by cleverKermit17** [darold/pgbadger#566]
Hello again,
This is a issue to reopen #560 

--
oh well, fortune sometimes dont last long.. the new feature made all the small projects run extremely fast without swapping,. now ive taken on the big guys. Logs are sometimes 5GB large (for one hours runtime), and this seems to give pgbadger the creeps.
for example i just had produced three logs with a total of 6.5 million queries. It took 1½ hours. What i notice now is that the later the hour for that day, the slower the file is processed. So it possibly is due to this handling in the .bin files.. also these big jobs are swapping bigly again, though much less, they still do it.

Currently i have removed the whole bin file structure for a big database analysis and try to run, so that everything is created from scratch - i have 300GB data to process, but i am tracing the runtime now.

One thing the perl process spends much time on is this:
`mmap(0x0,2097152,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 40531656704 (0x96fe00000)`

So the no-week option was good, but didnt resolve the whole problem.
It seems to have been a problem since we introduced the applicationname in the logprefix - so maybe theres something in this regard ?

**Comment by darold** [comment]
This is normal that following the hour of the day generating reports takes longer, same as for week report, pgbadger load all hourly binary files into memory to generate daily reports.

I think you should separate statistics build from the reports and generate the reports at end of the day or when needed.

For example run pgbadger every hour like this (I take you command line example in the previous issue):
```
pgbadger -q -I -j 5 -s 5 -t 10 --maxlength 4000 -U postgres -l "/path-to-my-dir/last-parsed" --pid-file "pgbadger-my.pid" -O "/path-to-my-dir/pgbadger-data" --noreport /var/log/postgresql*.log
``` 
thanks to `--noreport` it will just create the data binary files in "/path-to-my-dir/pgbadger-data".

Then for example you can make reports available each night for the next day in a separate directory, let's say `/path-to-my-dir/pgbadger-report`:
```
pgbadger -q -I -s 5 -t 10 --disable-checkpoint -X --no-week -l "/path-to-my-dir/last-parsed" -H "/path-to-my-dir/pgbadger-report/" /path-to-my-dir/pgbadger-data/2020/02/19/*.bin
``` 
This will build daily reports in `/path-to-my-dir/pgbadger-report` and require to set the path (`l`) to the last parsed information, the path (`-H`) where HTML reports will be written and the binary data files of the day as argument (`/path-to-my-dir/pgbadger-data/2020/02/19/*.bin`).

I have pushed a new commit c33245e that allow this feature. Could you give a try and let me know if this is more efficient.

**Comment by cleverKermit17** [comment]
hello sir,
i cant seem to find a commit of that name (c33245e).

from trying the commit from the other day, pgbadger doesnt create any html files, it does however process something..:
`./pgbadger  -I -s 5 -t 10 -X --no-week --disable-checkpoint -H "/tmp/test-html/" -O /tmp/test-html/ 2020-02-19-9716*.bin
[========================>] Parsed 19239363 bytes of 19239363 (100.00%), queries: 361602, events: 0`

i discovered that the -O option is nescesary or it wont start, however nothing is created in that dir either..

**Comment by darold** [comment]
Sorry I forgot to push the commit last night, this is done now.

**Comment by cleverKermit17** [comment]
no worries Darold,
i just tried then
`/pgbadger-c33245e97ea3588c5797a3b38332f253238091c0/pgbadger -I -j 5 -s 5 -t 10 -U postgres -l ./last-parsed --pid-file "pgbadger-my.pid" -O /myfiles-dir/ --noreport /my-logdir/*.log`

it displayed
`[========================>] Parsed 18803406081 bytes of 18803406081 (100.00%), queries: 1736649137, events: 2204`
so lots of stuff to work with, parsing took 67 minutes for 11 files with a total of 18GB logdata

no reports was generated, but i got 51 .bin files with a total of 797MB size / now thats as expected.

but then, sadly, i tried this>
`/pgbadger-c33245e97ea3588c5797a3b38332f253238091c0/pgbadger -I -s 5 -t 10 --disable-checkpoint -X --no-week -l last-parsed -H /my-path-to/html/ -O /mypath-to/out/ 2020/02/20/2020-02-20-1*.bin}`
giving this output
`[========================>] Parsed 832777363 bytes of 832777363 (100.00%), queries: 11678747, events: 2204
`
runtime was 2 minuts and 8 seconds.. but the sad thing is that no reports was generated - 0 .html files created.. very strange - any ideas ?

**Comment by darold** [comment]
Please remove the `-O /mypath-to/out/` if you set this pgbadger look for any new log entries but stop because there is not.

**Comment by darold** [comment]
On my computer (32GB ram, 16 cores) using your command in a 12GB of log file and around 14 billions of queries I have the following results :
```
$ time perl ./pgbadger -I -j 5 -s 5 -t 10 -O /home/git/pgbadger/report/ --noreport /data/pglog/huge_log_test/postgresql-*.log
[========================>] Parsed 10031788505 bytes of 10031788505 (100.00%), queries: 14628985571, events: 3074

real	21m3,322s
user	104m1,843s
sys	0m3,899s
```
