### ISSUE TITLE
binary format: multiplication issue of statistics

### ISSUE THREAD

**Issue by wibrt** [darold/pgbadger#569]
Using the binary format as described on
http://pgbadger.darold.net/documentation.html#BINARY-FORMAT
i get the impression that results are multiplied per day

What does this mean:
the first run the results are correct,
but the second day the  results are doubled (compared to actual),
the the third day the results are trippled (compared to actual),
and so on

Can anyone confirm this?

Possible reason?:
the documentation example talks about  a daily logfle,
while debian stable rotates the logfile weekly, not daily by default, keeping 10 weeks?
But since the days are correct in de graphs, i would expect pgbadger to take this into account, since it knows the days (, so the full  timestamp, not only the hours)

Commands used:
```
rm /tmp/cluster1_weekdag_$(date +%A)*.bin
pgbadger --pid-file /tmp/pgbadger_cluster1.pid --last-parsed /tmp/.pgbadger_last_state_file_cluster1 -o /tmp/1920_weekdag_$(date +%A-%Hu).bin /var/log/postgresql/postgresql-12-cluster1.log 2>> /v
pgbadger --pid-file /tmp/pgbadger_cluster1.pid -o week_report_cluster1.html /tmp/cluster1_weekdag_*.bin 2>>  /var/log/pgbadger_dagelijks_cluster1.log
```

Context: debian stable with apt.postgresql.org

**Comment by darold** [comment]
Yes they are doubled because your first query generate statistics from the log file but the second also read input from the binary files which creates new binary files with what has been read. You need to set the last parsed file in the second command too to avoid load twice the data:
```
pgbadger --pid-file /tmp/pgbadger_cluster1.pid--last-parsed /tmp/.pgbadger_last_state_file_cluster1  -o week_report_cluster1.html /tmp/cluster1_weekdag_*.bin 2>>  /var/log/pgbadger_dagelijks_cluster1.log
```

**Comment by wibrt** [comment]
os : standard debian 

this problem seems to persists with (my usage?) of the binary format

this script is a called every hour by cron.hourly:

`#!/bin/sh

# cluster1
echo "$(date): cluster1" >> /var/log/pgbadger_hourly_cluster1.log

pgbadger --pid-file /run/pgbadger_cluster1.pid --last-parsed /var/local/pgbadger/.pgbadger_last_state_file_cluster1 -o /var/local/pgbadger/cluster1_day_$(date +%A-%Hu).bin /var/log/postgresql/postgresql-13-cluster1.log 2>> /var/log/pgbadger_hourly_cluster1.log 
pgbadger --pid-file /run/pgbadger_cluster1.pid --last-parsed /var/local/pgbadger/.pgbadger_last_state_file_cluster1 -o $(date +%A)_report_cluster1.html /var/local/pgbadger/cluster1_day_*.bin 2>> /var/log/pgbadger_hourly_cluster1.log

# cluster2
echo "$(date): cluster2" >> /var/log/pgbadger_hourly_cluster2.log

pgbadger --pid-file /run/pgbadger_cluster2.pid --last-parsed /var/local/pgbadger/.pgbadger_last_state_file_cluster2 -o /var/local/pgbadger/cluster2_day_$(date +%A-%Hu).bin /var/log/postgresql/postgresql-13-cluster2.log 2>> /var/log/pgbadger_hourly_cluster2.log 
pgbadger --pid-file /run/pgbadger_cluster2.pid --last-parsed /var/local/pgbadger/.pgbadger_last_state_file_cluster2 -o week_report_cluster2.html /var/local/pgbadger/cluster2_day_*.bin 2>>  /var/log/pgbadger_hourly_cluster2.log

exit 0`

each time the above script runs, the numbers of already processed data seem to get added to the previous results, resulting in a multiplication issue per run

**Comment by darold** [comment]
Commit a8ca1eb might fix this issue.
