### ISSUE TITLE
Error parsing with last source

### ISSUE THREAD

**Issue by lours1** [darold/pgbadger#57]
Hi,

I get this error when i run pgbadger from last source
D:\log>perl D:\programme\pg_badger.git\pgbadger\pgbadger plop.log
[=======================> ] Parsed 84315852 bytes of 84388628 (99.91%), queries: 129873, events: 1
Variable length lookbehind not implemented in regex m/(?<!CLASSSY0B\$\$)\bALTER\b/ at D:\programme\pg_badger.git\pgbadger\pgbadger line 3915, <DATA> line 46.

No problem with version 2.2
D:\log>perl D:\programme\pgbadger-2.2\pgbadger plop.log
[=======================> ] Parsed 84315852 bytes of 84388628 (99.91%), queries: 259618, events: 1

Cédric

**Comment by darold** [comment]
Any news about this issue?

**Comment by pcav** [comment]
I'm going to test in the next few days, thanks.

**Comment by pcav** [comment]
Just tested on a clean jessie box, no error.
Sorry for the noise.

**Comment by darold** [comment]
That's ok, feel free to reopen it if you are facing the same problem again.

Best regards,

**Comment by umbiz** [comment]
Hi, i have the same problem: 
"Variable length lookbehind not implemented in regex m/(?<!STYLESY0B\$\$)\bALTER\b/ at /usr/bin/pgbadger line 4997, line 48"
the program fails to update pgbadger.html, while if i delete it's created
debian: 8.1
pgbadger: 3.3-2
perl: 5.20.2-3

thanks

**Comment by darold** [comment]
Hi,

You are using the last version of pgbadger for Debian, which is a very old version. Please use latest version which is now 7.1, download at https://github.com/dalibo/pgbadger/releases

You can also drop a line to the lazy Debian maintainer.

Best regards

**Comment by pcav** [comment]
Right, ticket open:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785216

Trying to push a bit, thanks.
