### ISSUE TITLE
Not able to parse custom prefix

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [darold/pgbadger#572]
Im trying to parse a PostgreSQL log file with pgbadger. Its a custom log prefix. But when I try to parse its always showing queryes=0.

sample log:
```
'2020-03-07T16:09:43Z UTC [ db=dev user=rdsdb pid=16929 userid=1 xid=7382 ]' LOG: SELECT 1
'2020-03-07T16:09:43Z UTC [ db=dev user=rdsdb pid=16929 userid=1 xid=7383 ]' LOG: SET statement_timeout TO 120000
```

Pgbadger log:
```
/usr/local/bin/pgbadger -v pglog --prefix "'%t [ db=%d user=%u pid=%p userid=%p xid=%x ]'"

DEBUG: timezone not specified, using 0 seconds
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Autodetected log format 'stderr' from pglog
DEBUG: pgBadger will use log format stderr to parse pglog.
DEBUG: Starting progressbar writer process
DEBUG: Processing log file: pglog
DEBUG: Starting reading file pglog...0 bytes of 205 (0.00%), queries: 0, events: 0
DEBUG: Start parsing postgresql log at offset 0 of file pglog to 205
DEBUG: the log statistics gathering took: 2 wallclock secs ( 0.00 usr +  0.01 sys =  0.01 CPU)

DEBUG: Output 'html' reports will be written to out.html
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.01 usr +  0.00 sys =  0.01 CPU)
DEBUG: the total execution time took:  2 wallclock secs ( 0.01 usr +  0.01 sys =  0.02 CPU)
```

I don't know whats wrong with this.

**Comment by darold** [comment]
Where does your log come from? The format of the timestamp do not correspond to the `%t` placeholder, you should have something like that `2020-03-07 19:09:13 UTC` and for `%m` it should be `2020-03-07 19:09:13.634 UTC`. Can you post the value of the `log_line_prefix` in your postgresql.conf?

**Comment by BhuviTheDataGuy** [comment]
I tried manually change the timestamp format as well. But still it's not working.even I tried to remove the timestamp from these 2 lines and removed the %t 

Regarding this log prefix,it is generated from AWS redshift. I don't have the log prefix.

**Comment by darold** [comment]
Commit 8ca8889 adds auto-detection of AWS RedShift log format. Can you give a try to latest development code (`git clone` or `wget https://github.com/darold/pgbadger/archive/master.zip`)?

Also do you know if you can enable statement log duration and if possible post some log lines so that I could add support to this log format.

**Comment by BhuviTheDataGuy** [comment]
Hi @darold 
There is no straight forward way to add execution time in the log file. Because all the queries will be logged into the log file before the execution. 

But there is a creak to do this, we already tested this.
1. stl_query - Its a system table in redshift and it'll capture the query along with its execution time, but there is a glitch, if the query size is more than 4k bytes, then it'll truncate the query text.
2. stl_querytext - This contains the complete query, but we have to [reconstruct the SQL](https://thedataguy.in/redshift-reconstructing-sql-from-sql-querytext/) we can join both the tables to get the Query + Execution time. 

But this process should be a manual/cron job. The result should be unloaded to S3 bucket. Then we can use CSV format in pgbagder to archive the complete query analysis.
