### ISSUE TITLE
Unknown option: exclude-client

### ISSUE THREAD

**Issue by jwalsh2** [darold/pgbadger#573]
I am trying to exclude a client IP Address from parsing.  When I pass `--exclude-client x.x.x.x` (I masked IP) I get:

Unknown option: exclude-client

The `--exclude-appname foo` does not throw and error and seems to work.

pgbadger version 11.2

**Comment by darold** [comment]
What is the value of log_line_prefix in your postgresql.conf and post one line of your log file here.

**Comment by jwalsh2** [comment]
@darold The log_line_prefix is fixed in RDS `%t:%r:%u@%d:[%p]:`

Here is a log snippet, posted a few lines for you:

`2020-03-09 10:49:36 UTC:172.31.53.34(34934):pgwatch2@enterprise_dw:[1375]:LOG:  temporary file: path "base/pgsql_tmp/pgsql_tmp1375.2", size 6953670
2020-03-09 10:49:36 UTC:172.31.53.34(34934):pgwatch2@enterprise_dw:[1375]:STATEMENT:  
	select
	  (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
	  sum(calls) as calls,
	  sum(total_time) as total_time
	from
	  pg_stat_statements
	where
	  dbid = (select oid from pg_database where datname = current_database())
	  and calls > 10
	;
	
2020-03-09 10:49:36 UTC:172.31.53.34(34934):pgwatch2@enterprise_dw:[1375]:LOG:  duration: 44.903 ms  statement: `

**Comment by darold** [comment]
Thanks, commit 1e7572f fixes this issue.

**Comment by jwalsh2** [comment]
Thanks @darold that worked!!  Closing this one.
