### ISSUE TITLE
save normalized query results to a text file

### ISSUE THREAD

**Issue by shantanuo** [darold/pgbadger#576]
I am using the following command to generates a report file out.html

`./pgbadger -f redshift /tmp/rlogs3/* --dbname xyz_db`

The report is awesome and I have never seen something like this before. But is there any way to export the report to a text file? I just need to save the normalized query report (all - not just top 20) to a text file.

**Comment by darold** [comment]
To have a text output simply add `-o out.txt`, pgBadger detect the extension and adapt the output format automatically.

```
    -o | --outfile filename: define the filename for the output. Default depends
			     on the output format: out.html, out.txt, out.bin,
			     out.json or out.tsung. This option can be used
			     multiple time to output several format. To use json
			     output the Perl module JSON::XS must be installed,
			     To dump output to stdout use - as filename.
```

If you just want to report the normalized queries add `--normalized-only` all of them will be reported ordered by count.
```
    --normalized-only      : only dump all normalized query to out.txt
```
Actually I guess that there is an option for all you might want to do, otherwise feature request are welcomes :-)

**Comment by shantanuo** [comment]
1) Even if I mention the dbname, certain system related queries are returned.

./pgbadger -f redshift /tmp/rlogs3/* --dbname xyzdb --outfile out.txt --normalized-only

```
116	select typname from pg_type where typnamespace = (select oid from pg_namespace where nspname = current_schema()) and typtype in (...) and typelem = ?;
116	select description from pg_catalog.pg_description where objoid = ? and classoid = (select oid from pg_catalog.pg_class where relname = ? and relnamespace = ?) and objsubid = ?;

58	select relname AS "Name", case relkind when ? then ? when ? then ? when ? then ? else ? end AS "Engine", pg_relation_size(oid) AS "Data_length", pg_total_relation_size(oid) - pg_relation_size(oid) AS "Index_length", obj_description(oid, ?) AS "Comment", relhasoids::int AS "Oid", reltuples AS "Rows" from pg_class where relkind in (...) and relnamespace = (select oid from pg_namespace where nspname = current_schema()) order by relname;
58	select nspname from pg_namespace order by nspname;
58	select datname from pg_database order by datname;

12	select oid,typname from pg_type;
8	select oid from pg_class where relnamespace = (select oid from pg_namespace where nspname = current_schema()) and relname = ?;
8	select relname, indisunique::int, indisprimary::int, indkey, indoption from pg_index i, pg_class ci where i.indrelid = ? and ci.oid = i.indexrelid;
8	select attnum, attname from pg_attribute where attrelid = ? and attnum > ?;
8	select relname from pg_class where oid=?;
```

The tables like pg_namespace, pg_class should be excluded.

2) There should be an option to filter out queries. For e.g. --where count > 2  (the queries those appear only once will not be returned)

**Comment by darold** [comment]
Why? These tables are part of the database even if they are from the system catalog. What you are asking is to limit report following your application schema. If these queries are generated by a different application, you can use `--appname appname --dbname xyzdb` to limit report to your application. If these queries are part of your application then reporting them is something normal.

**Comment by shantanuo** [comment]
I added the following parameter to get the exclusive queries I was looking for.

>  --exclude-query 'FROM pg_' 

This is just for the record. I do not want to re-open the issue.
