### ISSUE TITLE
external ssh connection

### ISSUE THREAD

**Issue by augustomurri** [darold/pgbadger#577]
I am trying to get the postgres log fron another server, getting it with ssh running on non standard port (2222). It doesn't work, i can't see any parameter to specify port

`pgbadger ssh://root@10.0.0.2/var/log/postgresql/postgresql-11-main.log -o /var/www/html/pgbadger.html`

`ssh -p 2222 root@10.0.0.2 tail /var/log/postgresql/postgresql-11-main.log`  works

**Comment by darold** [comment]
Look like we need a better way to specify an alternate port to ssh, I will work on something like: `ssh://root@10.0.0.2:2222/...`

Actually you should be able to modify the default ssh port by adding: `--ssh-command "ssh -p 2222"` to your pgbadger command.

**Comment by darold** [comment]
Commit f3e9820 adds this feature. You can now use the notation: `ssh://root@10.0.0.2:2222/...`
