### ISSUE TITLE
no queries recognized

### ISSUE THREAD

**Issue by augustomurri** [darold/pgbadger#578]
This is my postgres.conf 
```
# PGBADGER
log_statement = 'none'
log_min_duration_statement = 0
lc_messages='en_US.UTF-8'
lc_messages='C'

log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
log_error_verbosity = default
log_line_prefix = 'user=%u,db=%d,app=%a,client=%h '
```

after a pgbench i get this log file with thousands of lines, this a a chunk
[test.log](https://github.com/darold/pgbadger/files/4402534/test.log)

root@WEBECOFIL:/var/www/html# **pgbadger --prefix 'user=%u,db=%d,app=%a,client=%h ' test.log -o pgbadger.html -f stderr**
[========================>] Parsed 3324586 bytes of 3324586 (100.00%), **queries: 0, events: 0**
**LOG: Ok**, generating html report...

no queries recognized.. why? thanks

**Comment by augustomurri** [comment]
This is output in verbose mode -v 
[pgbadger-v.txt](https://github.com/darold/pgbadger/files/4402565/pgbadger-v.txt)

**Comment by augustomurri** [comment]
It works using
`log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u ' `

**Comment by darold** [comment]
Ok, most of the time if no query are reported this is because of a wrong log line prefix.
