### ISSUE TITLE
[enhancement] Support of GCP CloudSQL format

### ISSUE THREAD

**Issue by tpoindessous** [darold/pgbadger#579]
Hi

I'm back with the format of GCP CloudSQL Postgresql logs.
It's fairly normal PG log but encapsulated in JSON format.

```
{
  "textPayload": "[153735]: [10-1] db=cloudsqladmin,user=cloudsqladmin LOG:  duration: 11.446 ms  statement: SELECT datname, numbackends, xact_commit, xact_rollback, blks_read, blks_hit, tup_inserted, tup_updated, tup_deleted, deadlocks, blk_read_time, blk_write_time, stats_reset, current_timestamp FROM pg_catalog.pg_stat_database WHERE stats_reset IS NOT NULL ORDER BY datname ",
  "insertId": "s=31ab647413784ebda4ba4d0f0ef93d6b;i=cb0cc;b=ac15f05ee2554206b2aea5191234f431;m=15048af7ae7;t=5a2ce3c603f6e;x=3a11dd807086788-0@a1",
  "resource": {
    "type": "cloudsql_database",
    "labels": {
      "project_id": "test-dev",
      "region": "europe",
      "database_id": "test-dev:test-replica"
    }
  },
  "timestamp": "2020-04-08T21:32:23.456622Z",
  "severity": "INFO",
  "logName": "projects/test-dev/logs/cloudsql.googleapis.com%2Fpostgres.log",
  "receiveTimestamp": "2020-04-08T21:32:24.286915566Z"
}
```

In CloudSQL, we can't modify log_line_prefix but we can play with log_min_duration_statement, log_duration, log_connections, log_lock_waits, etc.

It would be cool if pgbadger could parse GCP JSON format !

Thanks !

**Comment by darold** [comment]
Can you post a sample log file using pgbench for example, with the following configuration:
```
            log_checkpoints = on
            log_connections = on
            log_disconnections = on
            log_lock_waits = on
            log_temp_files = 0
            log_autovacuum_min_duration = 0
```
this will help covering all cases.

**Comment by tpoindessous** [comment]
Hi

I set these options, I did the pgbench test and I will collect the log tomorrow.

Thanks

**Comment by tpoindessous** [comment]
hi ! 

here is the log (GCP makes one file by hour)

https://send.firefox.com/download/2225cb134996dc60/#DPSmMnFnMgb4xJvmIvSz_w

I did one pgbench test with `pgbench  -h 104.155.65.77 -U postgres -t 250  test`, it ended at this timestamp : `2020-05-02T13:42:24`

There is no SELECT lines in this file as I didn't set log_min_duration_statement.

Do you want another log with `log_min_duration_statement = 0 ` ?

Thanks !

**Comment by darold** [comment]
Commit 717a467 add support to GCP CloudSQL log file. Let me know if there is any issue.

**Comment by tpoindessous** [comment]
Thanks ! I will test it.

**Comment by tpoindessous** [comment]
Thanks @darold , it works :)

**Comment by thomasLeclaire** [comment]
> Hi
> 
> I'm back with the format of GCP CloudSQL Postgresql logs.
> It's fairly normal PG log but encapsulated in JSON format.

Hello!
Can I ask you how do you export the cloudsql logs ? 
and how do you consider the multiline subjects when big requests?

thx!

**Comment by tpoindessous** [comment]
Hi !

you need to set up a log routing, AKA logsink :
https://cloud.google.com/logging/docs/export/configure_export_v2

For multiline, I don't know, you will need to test :)

Have a nice day

Le ven. 26 juin 2020 à 13:49, Thomas Leclaire <notifications@github.com> a
écrit :

**Comment by thomasLeclaire** [comment]
sounds like multiline is correclty managed by sink export. (but not when using the google cli to read logs)
thx!

**Comment by vborcea** [comment]
Hello,

I know that this si a closed topic but it's related to it.

I have downloaded version 11.3 and I am trying to analyze logs pgbadger -f jsonlog postgres.json but without success.
Here is an example of one entry

{
    "textPayload": "2020-11-12 18:13:08.388 UTC [1824977]: [42-1] db=test-service,user=test-service LOG:  duration: 2.475 ms  parse <unnamed>: select user0_.id as id1_0_, user0_.active as active2_0_, user0_.language as language9_0_, user0_.last_name as last_na10_0_, user0_.mobile_number as mobile_11_0_,  user0_.role_id as role_id18_0_, user0_.sms_code as sms_cod14_0_, user0_.sms_code_expiration as sms_cod15_0_, user0_.uid as uid16_0_, user0_.zip_code as zip_cod17_0_ from app_user user0_ where user0_.uid=$1",
    "insertId": "s=4027b358aec64ff0bf73af185b4cb473;i=dcead7;b=90d604700bc240409c1f8cfc9a47478f;m=5e266b4d20b;t=5b3ecdd342444;x=c6fd1262fc7fb735-0@a1",
    "resource": {
      "type": "cloudsql_database",
      "labels": {
        "project_id": "project-x",
        "database_id": "project-x:test",
        "region": "europe-west2"
      }
    },
    "timestamp": "2020-11-12T18:13:08.388932Z",
    "severity": "INFO",
    "logName": "projects/compelling-cat-212513/logs/cloudsql.googleapis.com%2Fpostgres.log",
    "receiveTimestamp": "2020-11-12T18:13:09.429173904Z"
  }

The config on the database is:
log_min_duration_statement 1
log_duration on
log_checkpoints on
log_connections on
log_disconnections on
log_lock_waits on
log_temp_files 0
log_autovacuum_min_duration 0

Can you tell me if I am missing something?
