### ISSUE TITLE
Vacuum stats are not parsed from RDS (Aurora) via Cloudwatch logs

### ISSUE THREAD

**Issue by timanovsky** [darold/pgbadger#581]
Analyze statements are recognized, but vacuum are not. I can attach sample file, but in general lines look like this:
```
2020-04-09T02:50:27.000Z 2020-04-09 02:50:27 UTC::@:[44097]:LOG:  automatic aggressive vacuum of table "w.public.fjc": index scans: 0
        pages: 0 removed, 2628375 remain, 0 skipped due to pins, 0 skipped frozen
        tuples: 0 removed, 92782333 remain, 0 are dead but not yet removable, oldest xmin: 214253111
        buffer usage: 6827064 hits, 0 misses, 0 dirtied
        avg read rate: 0.000 MB/s, avg write rate: 0.000 MB/s
        system usage: CPU: user: 29.79 s, system: 0.23 s, elapsed: 64.72 s
```

Repro:
 
- configure logs to be sent to CloudWatch
- export logs from Cloudwatch to S3
- try parse with `-f rds`

**Comment by darold** [comment]
Commit 6ffd582 fixes this issue. More work should be done to report aggressive and wraparound vacuum statistics. Thanks for the report.

**Comment by timanovsky** [comment]
Thanks for looking into this. So the problem was not due to Aurora
