### ISSUE TITLE
Complete report of all queries

### ISSUE THREAD

**Issue by shantanuo** [darold/pgbadger#582]
I used the following command and got the report as expected...

`./pgbadger --format redshift `find /tmp/mylogs/ -name "*tylog*"`  --dbname vadb --outfile myq1.txt`

As per the overall stats, there are 72,470 queries in the log files. How do I return all of these queries instead of concise report?

> - Overall statistics ---------------------------------------------------
> Number of unique normalized queries: 7,388
> Number of queries: 72,470
> Total query duration: 0ms
> First query: 2020-02-29 23:16:04
> Last query: 2020-03-31 22:41:02
> Query peak: 1,107 queries/s at 2020-03-04 21:13:38
> Number of events: 0
> Number of unique normalized events: 0

**Comment by darold** [comment]
You can not, unless you just want the 7,388 normalized query. In this case use option `--normalized-only`.

**Comment by shantanuo** [comment]
Can you please consider adding a feature that will return all queries? It will help me a lot because even if the queries are there in the log files, it is very difficult to extract them using linux commands!

**Comment by darold** [comment]
Commits c6ace51 and 67e63fb add this feature through a new query:
```
    --dump-all-queries     : dump all queries found in the log file replacing
                             bind parameters are included in the queries at
                             their respective placeholders position.
```
Note that queries are not sort by uniqueness, this must be done by an external command.

**Comment by shantanuo** [comment]
Thanks for considering the feature request. Can you remove line breaks and return a single query per line?

**Comment by shantanuo** [comment]
Thanks for considering the feature request. Can you remove line breaks and return a single query per line?

**Comment by shantanuo** [comment]
Or can you add a blank line between 2 queries?

**Comment by darold** [comment]
Actually adding a blank line will not help because you can also have blank line in multi line queries, to help parsing the output script I have added a new option `-Q | --query-numbering` used to add numbering of queries to the output when using options `--dump-all-queries` or `--normalized-only`.
By this way you will have an identifiable separator between each line. Example:
```
# Query #1 
SELECT * FROM table1;
# Query #2 
DELETE FROM table1;
...
```

**Comment by darold** [comment]
Forgot to give the commit: dd4b134
