### ISSUE TITLE
Cannot generate out file in AWS lambda

### ISSUE THREAD

**Issue by Akshay2378** [darold/pgbadger#584]
pgbadger is unable to write out file to the /tmp directory of lambda. Gives this error
"error":"Can't set $0 with prctl(): Operation not permitted at ./pgbadger line 3056, <DATA> line 122.\nCan't set $0 with prctl(): Operation not permitted at ./pgbadger line 3155.\nLOG: Ok, generating html report...\nFATAL: can't write to out.html, Read-only file system\n    - Error at line 1847\n"

**Comment by darold** [comment]
Commit e71f0bc allow to change path to temporary file.
```
Add new command line option --tempdir to be able to set the directory where temporary
files will be written. Default: File::Spec->tmpdir() || '/tmp
```

Let us know if that's solve the problem.

**Comment by Akshay2378** [comment]
Commenting out lines which have "$0" (trying to assign process name, i.e.,3056 and 3155) worked for me.
Thanks for the response.

**Comment by darold** [comment]
Commit 71b0a7e allow to disable process title modification.
```
 --no-process-info      : disable changing process title to help identify
                                    pgbadger process, some system do not support it.
```
