### ISSUE TITLE
--begin --end aguments, broken support for "time" format

### ISSUE THREAD

**Issue by massimosala** [darold/pgbadger#585]
Hi

With the previous version (sorry I am not sure 10 or 10.1) I can use the time format:

> --begin '07:00:00' --end '20:59:59'"

Now it is broken: pgbadger discards all the events.
I have to use the full date-time format:

> --begin '2020-04-24 07:00:00' --end '2020-04-24 21:59:59'"

**Comment by darold** [comment]
Hi,

Yes, there is dedicated command line options to filter on time:
```
        --exclude-time  regex  : any timestamp matching the given regex will be
                                 excluded from the report. Example: "2013-04-12 .*"
                                 You can use this option multiple times.
        --include-time  regex  : only timestamps matching the given regex will be
                                 included in the report. Example: "2013-04-12 .*"
                                 You can use this option multiple times.
```

I mean that, for the stderr log format for example, you can use: `--include-time '\d{4}-\d{2}-\d{2} [012].*', this should works.

`--begin` and `--end` must be used to est exact timestamp.
