### ISSUE TITLE
dbuser parameter not set correctly

### ISSUE THREAD

**Issue by shantanuo** [darold/pgbadger#586]
The first command works correctly as expected:

```
# pgbadger --format redshift /tmp/todel/26/useractivitylog_2020-03-26T08:53.gz --dbname vdb --outfile /tmp/myqn199.txt
[========================>] Parsed 612540 bytes of 612540 (100.00%), queries: 702, events: 0
LOG: Ok, generating txt report...
```

But when I add the dbuser parameter it does not return any query.

```
# pgbadger --format redshift /tmp/todel/26/useractivitylog_2020-03-26T08:53.gz --dbname vdb --dbuser root --outfile /tmp/myqn199.txt
LOG: Ok, generating txt report...d 612540 bytes of 612540 (100.00%), queries: 0, events: 0
```

I have checked that the file has queries executed by "root" user. For e.g.

> '2020-03-26T07:55:08Z UTC [ db=vdb user=root pid=28961 userid=100 xid=36036362 ]' LOG: SET search_path TO "public"

**Comment by darold** [comment]
Same problem as for RDS log format, commit 3e3c1ae fixes also this issue. Thanks for the report.
