### ISSUE TITLE
Modification of non-creatable array value attempted

### ISSUE THREAD

**Issue by wingedpig** [darold/pgbadger#588]
Got this error overnight:

LOG: Ok, generating HTML daily report into /var/groupsio/misc/pgbadger/2020/04/30/...
Modification of non-creatable array value attempted, subscript -1 at /usr/local/bin/pgbadger line 19572.

We ship logs off the database server hourly, and here is command line that generated this error:

/usr/local/bin/pgbadger -j 5 -I postgresql-2020-04-30_01.log -O /var/xxx/misc/pgbadger

This is on Centos 7, latest pgbadger, postgresql 9.6.

We just started using pgbadger yesterday, so we have less than 24 hours of using it.

**Comment by jwalsh2me** [comment]
I just hit that for the first time after using it for 6 months....   just on a different line number.

```LOG: Ok, generating HTML daily report into /home/ec2-user/pgbadger_reports/edw-adhoc/html//2020/05/06/...
Modification of non-creatable array value attempted, subscript -1 at /bin/pgbadger line 19483.```

**Comment by jwalsh2me** [comment]
@darold tried the latest code from `master` and get the same error but different line number. 

> Modification of non-creatable array value attempted, subscript -1 at /bin/pgbadger line 19606.

**Comment by darold** [comment]
Thanks for the report, commit 6ce0bea might fix this issue.

**Comment by darold** [comment]
pgFormatter has also been fixed with commit 17f795c as this code comes from here.

**Comment by jwalsh2me** [comment]
@darold thanks you.  I will try the code in `master` today.

**Comment by jwalsh2me** [comment]
@darold sadly same error...  here is my fill command and output:

```
[ec2-user@pgbadger-reports html]$ pgbadger -f rds -s 10 -t 100 -I /home/ec2-user/rds_logs/edw-adhoc/edw-adhoc.log.*-daily -O /home/ec2-user/pgbadger_reports/edw-adhoc/binary/ -H /home/ec2-user/pgbadger_reports/edw-adhoc/html/ -U pgwatch2 --exclude-client 172.31.53.34
[========================>] Parsed 9553108368 bytes of 9553108368 (100.00%), queries: 477147801, events: 739
LOG: Ok, generating HTML daily report into /home/ec2-user/pgbadger_reports/edw-adhoc/html//2020/05/03/...
LOG: Ok, generating HTML daily report into /home/ec2-user/pgbadger_reports/edw-adhoc/html//2020/05/04/...
LOG: Ok, generating HTML daily report into /home/ec2-user/pgbadger_reports/edw-adhoc/html//2020/05/05/...
LOG: Ok, generating HTML daily report into /home/ec2-user/pgbadger_reports/edw-adhoc/html//2020/05/06/...
Modification of non-creatable array value attempted, subscript -1 at /bin/pgbadger line 19608.
[ec2-user@pgbadger-reports html]$
```

**Comment by darold** [comment]
Yes of course sorry for the time lost, commit 65c483c might help fixing this issue.

**Comment by jwalsh2me** [comment]
@darold Thank you!!  SO far it is looking good, will let you know more on Monday!

**Comment by wingedpig** [comment]
It's not crashing with the error anymore, but it seems that the all the queries in the 'Top Queries' tab are now duration numbers. Could that be related?

**Comment by darold** [comment]
I don't think there is a lkink, previous issue is related to SQL query formatting. Can you post one line of your log file where a statement is reported?

**Comment by wingedpig** [comment]
Here is one statement (some data redacted):

```
2020-05-11 08:00:00 PDT [20286]: [104175-1] user=XX,db=userdb,app=web,client=XXX.XXX.XXX.XXX LOG:  execute <unnamed>: update "drafts" set "created"=$1, "updated"=$2, "version"=$3, "userid"=$4, "groupid"=$5, "type"=$6, "from"=$7, "subject"=$8, "tags"=$9, "body"=$10, "start"=$11, "bodytype"=$12, "isspecial"=$13, "numattachments"=$14, "nextattachmentnum"=$15, "messageid"=$16, "subids"=$17, "bccme"=$18, "bccall"=$19, "pollid"=$20, "eventid"=$21, "replyid"=$22 where "id"=$23 and "version"=$24;
2020-05-11 08:00:00 PDT [20286]: [104176-1] user=XX,db=userdb,app=web,client=XXX.XXX.XXX.XXX DETAIL:  parameters: $1 = 'XX', $2 = 'XX', $3 = '8', $4 = 'XX', $5 = 'XX', $6 = '1', $7 = '0', $8 = 'Re: Some projects I am using to study RF and microwaves', $9 = '', $10 = 'Great! Thanks for sharing. I was wondering if you have any test data for your two probes you had developed?', $11 = '', $12 = 'html', $13 = 'f', $14 = '0', $15 = '0', $16 = '165577530', $17 = '', $18 = 'f', $19 = 'f', $20 = '0', $21 = '0', $22 = '0', $23 = 'XX', $24 = '7'
2020-05-11 08:00:00 PDT [20286]: [104177-1] user=XX,db=userdb,app=web,client=XXX.XXX.XXX.XXX LOG:  statement: COMMIT
```

I'm also including a screenshot, where you can see that it appears that perhaps the query wasn't parsed correctly, because of all the extra data at the end.
<img width="1134" alt="Screen Shot 2020-05-11 at 9 25 04 AM" src="https://user-images.githubusercontent.com/145360/81585721-685d1000-9369-11ea-9329-c223e8802de2.png">

**Comment by darold** [comment]
Well you have enable `log_statement` and not `log_min_duration_statement` so there is no duration information.

Set `log_statement` to 'none' and `log_min_duration_statement` to 0, this is well documented.

**Comment by wingedpig** [comment]
Oh, duh. Thank you.
