### ISSUE TITLE
No queries detected - cloudsql json logs

### ISSUE THREAD

**Issue by alexandre-sk5** [darold/pgbadger#590]
Hello, 

I've tried to parse cloudsql json logs, but pgbadger doesn't seem to find any queries. 

`-> % pgbadger -f jsonlog -o cloudsql_out.html cloudsql.googleapis.com_postgres_log.json
[========================>] Parsed 30644787 bytes of 30644787 (100.00%), queries: 0, events: 0
LOG: Ok, generating html report...
`
Here are my postgresql flags : 

- log_connections=on
- log_lock_waits=on
- log_checkpoints=on
- log_disconnections=on
- log_temp_files=0
- log_autovacuum_min_duration=0
- log_min_duration_statement=0

Did i miss something ?

Thanks !

**Comment by darold** [comment]
Can you please add one or two line of your log file, the log format is probably a bit different than the one I had to implement this feature.

**Comment by alexandre-sk5** [comment]
`{"insertId":"s=0df70ca5e8fc4a519aa0b19b28f1cd21;i=27ff6e5;b=ed6a54b58d8c4d6b8bfa50d2e0f7a83a;m=3a02771e3ae;t=5a5aae8d97759;x=4a2ceab4b92cf404-0@a1","logName":"projects/*/logs/cloudsql.googleapis.com%2Fpostgres.log","receiveTimestamp":"2020-05-15T07:39:13.613169765Z","resource":{"labels":{"database_id":"*","project_id":"*","region":"europe"},"type":"cloudsql_database"},"severity":"INFO","textPayload":"[1430907]: [70-1] db=*,user=* LOG:  duration: 0.208 ms  execute <unnamed>: SELECT \"TOTO\".\"id\" AS \"TOTO\" FROM \"TABLE\" WHERE \"TOTO\".\"id\" IN ($1)","timestamp":"2020-05-15T07:39:13.142617Z"}`

**Comment by tpoindessous** [comment]
Hi @darold 

I'm the one which send you the CloudSQL log example :) 

For me, pgBadger works well with CloudSQL log.

I work with @alexandre-sk5 , I will check with him how did he launch pgbadger :) 

Thanks !

**Comment by darold** [comment]
I found the reason, last commit 1de1505 should fix this issue.

**Comment by tpoindessous** [comment]
Thanks @darold !

**Comment by juliolvfilho** [comment]
Hi @darold !

First of all, I'm sorry for commenting on this closed issue, but I'm facing the exactly same problem pointed by alexandre-sk5 (same command and params, same postgresql flags, no queries detected).

I'm using version 11.5.

Here, there are some lines of json logs extracted directly from Google Cloud Loging:

```json
{
    "textPayload": "2021-07-22 14:00:26.206 UTC [3130704]: [2-1] db=,user= STATEMENT:  SELECT \"my_table\".\"id\" FROM \"my_table\" INNER JOIN \"my_table2\" ON (\"my_table\".\"fk\" = \"my_table2\".\"id\") WHERE \"my_table\".\"column\"::text LIKE 'pattern%' ORDER BY \"my_table\".\"id\" DESC LIMIT 1000 OFFSET 23000",
    "insertId": "s=cdae1b3a02e54041b97e2842d72c19fc;i=98318e;b=50055f933c044c458c57319cdf94aef5;m=6f0c680d2b2;t=5c7b6b57a1a04;x=b10d17e8080cf6c6-0-0@a1",
    "resource": {
      "type": "cloudsql_database",
      "labels": {
        "database_id": "project-name:instance-name",
        "region": "us-central",
        "project_id": "project-name"
      }
    },
    "timestamp": "2021-07-22T14:00:26.206724Z",
    "severity": "INFO",
    "logName": "projects/project-name/logs/cloudsql.googleapis.com%2Fpostgres.log",
    "receiveTimestamp": "2021-07-22T14:00:27.814364536Z"
  },
  {
    "textPayload": "2021-07-22 14:00:26.206 UTC [3130705]: [1-1] db=,user= LOG:  temporary file: path \"base/pgsql_tmp/pgsql_tmp3130705.0\", size 3850240",
    "insertId": "s=cdae1b3a02e54041b97e2842d72c19fc;i=98318f;b=50055f933c044c458c57319cdf94aef5;m=6f0c680d308;t=5c7b6b57a1a5a;x=6bd8ba24397ca017-0-0@a1",
    "resource": {
      "type": "cloudsql_database",
      "labels": {
        "project_id": "project-name",
        "region": "us-central",
        "database_id": "project-name:instance-name"
      }
    },
    "timestamp": "2021-07-22T14:00:26.206810Z",
    "severity": "INFO",
    "logName": "projects/project-name/logs/cloudsql.googleapis.com%2Fpostgres.log",
    "receiveTimestamp": "2021-07-22T14:00:27.814364536Z"
  },
  {
    "textPayload": "2021-07-22 14:00:28.775 UTC [3130716]: [1-1] db=[unknown],user=[unknown] LOG:  connection received: host=[local]",
    "insertId": "s=cdae1b3a02e54041b97e2842d72c19fc;i=9831a0;b=50055f933c044c458c57319cdf94aef5;m=6f0c6a80823;t=5c7b6b5a14f74;x=2ecacac8301f03ce-0-0@a1",
    "resource": {
      "type": "cloudsql_database",
      "labels": {
        "database_id": "project-name:instance-name",
        "region": "us-central",
        "project_id": "project-name"
      }
    },
    "timestamp": "2021-07-22T14:00:28.776308Z",
    "severity": "INFO",
    "logName": "projects/project-name/logs/cloudsql.googleapis.com%2Fpostgres.log",
    "receiveTimestamp": "2021-07-22T14:00:29.801987181Z"
  },
  {
    "textPayload": "2021-07-22 14:00:28.778 UTC [3130716]: [2-1] db=dbname,user=postgres LOG:  connection authorized: user=postgres database=dbname",
    "insertId": "s=cdae1b3a02e54041b97e2842d72c19fc;i=9831a1;b=50055f933c044c458c57319cdf94aef5;m=6f0c6a8135d;t=5c7b6b5a15aae;x=264f4706c8b7dc2b-0-0@a1",
    "resource": {
      "type": "cloudsql_database",
      "labels": {
        "project_id": "project-name",
        "database_id": "project-name:instance-name",
        "region": "us-central"
      }
    },
    "timestamp": "2021-07-22T14:00:28.779182Z",
    "severity": "INFO",
    "logName": "projects/project-name/logs/cloudsql.googleapis.com%2Fpostgres.log",
    "receiveTimestamp": "2021-07-22T14:00:29.801987181Z"
  },
```

And bellow a screenshot of a execution with pgbadger:

![image](https://user-images.githubusercontent.com/4303698/126668377-df65ca53-dae6-4534-906f-3320f47c5e18.png)

Am I doing something wrong?

Thank you in advance!
