### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by caiado** [darold/pgbadger#591]
I recently installed PGBadger via "apt-get" on Ubuntu and the installed version was "**7.1**".

I checked that the latest version of PGBadger is "**11.2**".

Would it be possible to update the version of the Ubuntu repository to the latest one?

**Comment by darold** [comment]
I don't know where you get the package and who is maintaining the Ubuntu package but I recommend you to use the official PostgreSQL debian/ubuntu repository, pgbadger is always up to date. See instruction at https://wiki.postgresql.org/wiki/Apt
