### ISSUE TITLE
Parent blocker from Pgbadger

### ISSUE THREAD

**Issue by ravisql09** [darold/pgbadger#592]
How we can find the parent blocker from the blocking list as we can see only 

- Most frequent waiting queries
--Queries that waited the most

I need to find the root cause of the sql for the blocking.

Thanks

**Comment by darold** [comment]
Unfortunately we don't have this information in the log, you have to connect to the database and query the catalog when the lock occurs. See https://wiki.postgresql.org/wiki/Lock_Monitoring

**Comment by ravisql09** [comment]
> Unfortunately we don't have this information in the log, you have to connect to the database and query the catalog when the lock occurs. See https://wiki.postgresql.org/wiki/Lock_Monitoring

Thanks for the quick response Darold.
