### ISSUE TITLE
Temp files created but the queries that created it are not visible

### ISSUE THREAD

**Issue by tengilim** [darold/pgbadger#593]
Hello there.
 I could see all the temp files that have ever occurred and the queries that created them. But now I can only see the amount of tempfiles . The queries that compose them are not included in the report.

**Comment by darold** [comment]
Hi,

What do you call "now"? Is this after a pgbadger upgrade? What is the version you are using?

**Comment by tengilim** [comment]
> Hi,
> 
> What do you call "now"? Is this after a pgbadger upgrade? What is the version you are using?


No. I mean for the last few days.  pgBadger version 11.0

**Comment by darold** [comment]
I'm closing this issue, it is not reproducible at least with the latest development code.
