### ISSUE TITLE
Failure when updating incremental report.

### ISSUE THREAD

**Issue by soulhunter** [darold/pgbadger#594]
Hello,

Conditions:

+ RDS log format
+ log_min_duration_statement set to 0 
+ log_statement set to none
+ log_duration disabled
+ Incremental mode

The first time a report is generated it works fine, regardless of the number of log files (1, 2, 3, 20), then when updating the report by adding one or more new files, it does not detect new lines, it just says something like this for all files, old and new:

DEBUG: this file has already been parsed: log_file_name_here, there no new lines in this file

If I include one or more gzipped files, I would also get several lines like these, with different parts of queries:

DEBUG: Unknown rds log line format:                     WHERE id =  

I have tried this with 11.2 and latest "master".

Command line looks like:

pgbadger -v -J 4 --incremental --retention 52 old_log_file(s) new_log_file -O /path/to/output/

If I delete the report directory and start over: it will process all files just fine, old a new.

Sincerely,

Ildefonso

**Comment by soulhunter** [comment]
Hello,

Quick update, this also occurs if I remove -J, so, with or without parallel this happens, also without --retention: same behavior.

Not sure if the detail is important, but the logs I am parsing include *all* queries on a relatively highly loaded server, so, there are lots and lots of log lines per timestamp entry.

The current LAST_PARSED content is a "DETAIL" with parameters like $1 = 'somestring', $2='someotherstring'

I have not had the time to finish reviewing pgBadger code... will try to make some time for it today.  

Logic tells me that, for the system to reliably avoid losing log lines, it should look for the last parsed line and then resume from that point on, but, what if the previous log file is not provided (I could be sure to provide the "previous" log file if necessary)... but let's say it is not provided, in that case, I would assume it should look for the same or higher timestamp, as the first recognizable timestamp in a file, definitely before the last position --> new log file (continuation), and so it would start at that point.

I hope this helps.

Ildefonso

**Comment by soulhunter** [comment]
Another update, I found the related issue:

https://github.com/darold/pgbadger/issues/567

It sounds like the same problem, they even complain about the issue with compressed files.  I had this problem before with 11.1, a few months ago, I "worked around it" by downgrading to 10.3.  This time I decided to try and investigate the problem some more.

I'll try to find more information.

Ildefonso

**Comment by darold** [comment]
Thanks for the report Ildefonso, I was able to reproduce this issue, I'm working on a fix.

**Comment by darold** [comment]
Got it, commit 2e14858 might solve this issue.

**Comment by soulhunter** [comment]
Thank you!  It seems to be working now.

I get a few messages like:

DEBUG: Unknown rds log line format:....

I am guessing it is for the first second or so of the log file, until the timestamp actually changes (?)... but it is good enough... 

I believe the decision of closing the issue is yours.

Once again, thanks!

Ildefonso
