### ISSUE TITLE
Javascript reporting wrong local time zone

### ISSUE THREAD

**Issue by mightybs** [darold/pgbadger#595]
I reviewed this issue before posting: https://github.com/darold/pgbadger/issues/456

I've been attempting the `-Z` option to get a page that worked as expected, and I finally generated a page that almost made sense until I realized it was technically incorrect, but visually less confusing than any other result.  It is unclear to me whether or not the `-Z` option is supposed to set what the time zone should be forced to render on the page, or whether it is intended simply to offset what's being displayed.  The behavior tells me that it must be an offset from what is rendered without using the option, in which case means I cannot produce an accurate page.

Using a log file where the time zone is UTC and starts with 16:00:00 UTC and ends with 17:00:00 UTC I have found the following.

I believe this command would be the same as no time zone options, and produces Javascript that incorrectly reports the times as 1600 - 1700 CDT (my current local time zone).
`pgbadger --log-timezone -00 -Z -00 ./postgresql.log.2020-05-21-16`

I subsequently tried various options to see how they operated:
```
pgbadger --log-timezone -00 -Z -02 ./postgresql.log.2020-05-21-16
pgbadger --log-timezone -00 -Z -01 ./postgresql.log.2020-05-21-16
pgbadger --log-timezone -00 -Z -00 ./postgresql.log.2020-05-21-16
pgbadger --log-timezone -00 -Z +01 ./postgresql.log.2020-05-21-16
pgbadger --log-timezone -00 -Z +02 ./postgresql.log.2020-05-21-16
```
Here are a summary of the results:
```
-Z -02 => shows 1300 - 1400 CDT, which is two hours off (later).
-Z -01 => shows 1200 - 1300 CDT, which is one hour off (later).
-Z -00 => shows 1600 - 1700 CDT (matching UTC).
-Z +01 => shows 1000 - 1100 CDT, which is one hour off (earlier).
-Z +02 => shows 0900 - 1000 CDT, which is two hours off (earlier).
```
The `-Z -00` or not using a `-Z` at all is what I expect would work, but does not.

This behavior makes me believe that the `-Z` is not to specify what time zone you would want used in the html, but the offset of how you want to adjust from your actual time zone?  Again, I'm a bit confused.

Observing this behavior, I decided to try an option that felt pretty strange, but I was curious:
`pgbadger --log-timezone -00 -Z -24 ./postgresql.log.2020-05-21-16`
Subsequently I also tried ` -Z +24`.  These two options were the first time that I got the correct times showing on the page (1100 - 1200 CDT), but they of course were for the next day 05/22 and the previous day 05/21.

In the end I'm not entirely sure how the `-Z` option is intended for use, but I was not able to get a `pgbadger` command to produce html where it reported the correct time zone for the graphs where it specifically states my time zone (CDT) is what is being displayed.

Screenshot using `-Z +24`:

![Screenshot 2020-05-22 08 29 04](https://user-images.githubusercontent.com/157826/82672842-84cd3800-9c06-11ea-9743-080c55b28436.png)

Screenshot using `-Z -00`:

![Screenshot 2020-05-22 08 30 18](https://user-images.githubusercontent.com/157826/82672893-96164480-9c06-11ea-85cb-b07b0c510aff.png)

**Comment by darold** [comment]
Commit 237fa60 should fix this issue. UTC time is now autodetected and in this case pgbadger will not automatically apply the localtime zone.

**Comment by darold** [comment]
@mightybs can you confirm the fix?
