### ISSUE TITLE
User execute query is hide in Slowest Individual Queries

### ISSUE THREAD

**Issue by phlaluna** [darold/pgbadger#600]
Hello there,

When I execute the pgbadger command with parameter -z "/bin/zcat" the user who executes the query in Slowest Individual Queries is disappearing.
PS: declaring --format stderr, the pgbadger auto detected log format 'rds'

> $ pgbadger --version
pgBadger version 11.2

Command pgbadger without zcat piped:
> $ pgbadger -v --format stderr --exclude-query "^(COPY)" --extension html --title "PostgreSQL teste" --prefix '%t:%r:%u@%d:[%p]:' --outfile - -z "/bin/zcat" ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz > teste.html 
DEBUG: timezone not specified, using 10800 seconds
DEBUG: Output 'html' reports will be written to -
DEBUG: Looking for file size using command: gunzip -l ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz | grep -E '^\s*[0-9]+' | awk '{print $2}'
DEBUG: Starting progressbar writer process
DEBUG: Compressed log file, will use command: /bin/zcat "ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz"
DEBUG: Autodetected log format 'rds' from ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz
DEBUG: pgBadger will use log format rds to parse ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz.
DEBUG: Processing log file: ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz
DEBUG: Compressed log file, will use command: /bin/zcat "ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz"
DEBUG: Starting reading file "ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz"...
DEBUG: Start parsing postgresql log at offset 0 of file "ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz" to 376347183
[========================>] Parsed 376347183 bytes of 376347183 (100.00%), queries: 27465723, events: 991
DEBUG: the log statistics gathering took:123 wallclock secs ( 0.09 usr  0.01 sys + 122.26 cusr  0.93 csys = 123.29 CPU)
DEBUG: Output 'html' reports will be written to -
LOG: Ok, generating html report...
DEBUG: building reports took:  6 wallclock secs ( 6.71 usr +  0.00 sys =  6.71 CPU)
DEBUG: the total execution time took: 129 wallclock secs ( 6.80 usr  0.01 sys + 122.26 cusr  0.93 csys = 130.00 CPU)

![teste](https://user-images.githubusercontent.com/25820139/85798567-0d625b00-b714-11ea-9521-3f00264e2867.png)

Using zcat piped to pgbadger:
> $ zcat ras-rds-1-postgresql.log.2020-06-25-07-1593072000000.log.gz | pgbadger -v --format stderr --exclude-query "^(COPY)" --extension html --title "PostgreSQL teste" --prefix '%t:%r:%u@%d:[%p]:' --outfile - - > teste-zcat.html 
DEBUG: timezone not specified, using 10800 seconds
DEBUG: Output 'html' reports will be written to -
DEBUG: Can not autodetect log format, assuming stderr.
DEBUG: Starting progressbar writer process
DEBUG: Processing log file: -
DEBUG: Starting reading file "-"...
DEBUG: Start parsing postgresql log at offset 0 of file "-" to -1
[+] Parsed 376347183 bytes, queries: 27465723, events: 991
DEBUG: the log statistics gathering took:136 wallclock secs ( 0.07 usr  0.02 sys + 133.24 cusr  0.41 csys = 133.74 CPU)
DEBUG: Output 'html' reports will be written to -
LOG: Ok, generating html report...
DEBUG: building reports took:  7 wallclock secs ( 6.69 usr +  0.02 sys =  6.71 CPU)
DEBUG: the total execution time took: 143 wallclock secs ( 6.76 usr  0.04 sys + 133.24 cusr  0.41 csys = 140.45 CPU)

![teste-zcat](https://user-images.githubusercontent.com/25820139/85798579-12270f00-b714-11ea-91ac-92b7b3988839.png)

I tested the command with zcat piped to pgbadger declaring "--format rds" and the result is the same to first (user is disappearing)

How do I force the format?

My database is an Aurora RDS PostgreSQL.

**Comment by darold** [comment]
This issue has been solved with commit 3e3c1ae6, you need to upgrade to latest development code or wait for new release 11.3 coming soon.
