### ISSUE TITLE
Amazon Linux

### ISSUE THREAD

**Issue by leotoras** [darold/pgbadger#604]
Hi, is it possible to use some current package to install pgbadger on amazon linux ? Or maybe, is there a roadmap to have amazon linux installation packages for pgbadger ?
I use PostgreSQL a lot in AWS and would be very helpful to have pgbadger working on amazon linux.

**Comment by darold** [comment]
Hi @leotoras I am not working at Amazon I can not help on providing such package. pgbadger is available as RPM or debian package from the official repositories yum.postgresql.org and apt.postgresql.org

**Comment by leotoras** [comment]
Hi Darold, I didn´t say you work at Amazon, I meant to use pgbadger running on Amazon Linux Servers. Nevermind.
