### ISSUE TITLE
pgbadger queries: 0, events: 0

### ISSUE THREAD

**Issue by XalGoz** [darold/pgbadger#606]
I'm having some issue configuring this tool and it probably is a rooky mistake.

Here is my configuration file : https://pastebin.com/JViURUKr

Example of log file : 
`2020-08-07 17:37:57 CEST [652]: LOG:  duration : 0.000 ms, instruction : SELECT format_type(oid,NULL) as typname FROM pg_type WHERE oid = 1043`

Here is my command line
```
>perl.exe pgbadger "C:\Postgres\data\pg_log\postgresql-2020-08.log" -v
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Autodetected log format 'default' from C:\Postgres\data\pg_log\postgresql-2020-08.log
DEBUG: pgBadger will use log format default to parse C:\Postgres\data\pg_log\postgresql-2020-08.log.
DEBUG: timezone not specified, using -7200 seconds
DEBUG: Processing log file: C:\Postgres\data\pg_log\postgresql-2020-08.log
DEBUG: Starting reading file "C:\Postgres\data\pg_log\postgresql-2020-08.log"...s: 0
DEBUG: Start parsing postgresql log at offset 0 of file "C:\Postgres\data\pg_log\postgresql-2020-08.log" to 2144
[=======================> ] Parsed 2129 bytes of 2144 (99.30%), **queries: 0, events: 0**
DEBUG: the log statistics gathering took: 0 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
DEBUG: Output 'html' reports will be written to out.html
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
DEBUG: the total execution time took:  0 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
```

I've tried to update log_line_prefix, and use --prefix as a parameter but it does not work for me

Thanks for the tool, it seems pretty handy and I hope I'll be able to use it.

Btw : I'm on Windows 10, using http://strawberryperl.com/

**Comment by darold** [comment]
What is your value for log_line_prefix? I guess it is `%t [%p]: ` and this is not the pgbadger default so you need to specify the prefix used:
```
perl.exe pgbadger "C:\Postgres\data\pg_log\postgresql-2020-08.log" -v -p '%t [%p]: '
```
Also looking at `instruction: ` I think you are not using ANSI C or english log format, you should set `lc_messages` to `'C'` or `'en_US.utf8`.

The good practice about PostgreSQL log configuration is explain in the documentation, you should read it carefully if you want to benefit from all possible traces. This is the best way to be sure it will works for you :-)

**Comment by darold** [comment]
Oh and I should I read carefully your post I would have not miss you link to the postgresql.conf. This is the best way to answer correctly to users :-) I was right on the prefix but about lc_message that is set to C, have you reloaded the configuration?

In you log you should have  `statement: ` or `query: ` not `instruction: ` unless this is something that I missed.

**Comment by XalGoz** [comment]
It was indeed the "instruction :" instead of "statement:" that was problematic. 
lc_message was set to C and the configuration has been reloaded but it keeps logging in French, anyway I just replace them and it works.

Thanks for your quick answer and for this tool.
