### ISSUE TITLE
Application name from RDS

### ISSUE THREAD

**Issue by hansgv** [darold/pgbadger#607]
What Postgres log parameters and pgbadger --format parameter should I use to include the application name from RDS Postgres (11.8) into reports?

**Comment by darold** [comment]
I don't see any field that stores the application name in RDS log. It appears that RDS has only one log_line_prefix which is `'%t:%r:%u@%d:[%p]: '`. If you can customize this prefix add a `%a` somewhere, for example: `'%t:%r:%u@%d:%a:[%p]: '` in your postgresql.conf and give this value to pgbadger using the `-p` option.

**Comment by hansgv** [comment]
Based on https://aws.amazon.com/blogs/database/working-with-rds-and-aurora-postgresql-logs-part-1/ it looks like switching to csvlog is the only way to get application name logged. Any downsides to that from pgbadger point-of-view? What --format should I select if using csvlog?

**Comment by darold** [comment]
`csv` if not autodetected by pgbadger. I hope you will not have huge logs because you can not use multiprocess with csv.

**Comment by hansgv** [comment]
What would be considered "huge"? I use --incremental and my hourly logs are usually 100-300MB. With --jobs=2 it takes a couple of minutes for pgbadger to run.

**Comment by darold** [comment]
In your case it could simply take the double of time.
