### ISSUE TITLE
postgresql text logs to csv file

### ISSUE THREAD

**Issue by bagafoot** [darold/pgbadger#608]
Hi all,

I have huge postgresql default text logs with log_line_prefix.
I want to convert all text logs to csv file, and pgbadger already has a parser engine for that.
I wonder, can I convert all logs via pgbadger to csv file, and if it is possible, how ?

Thanks.

**Comment by darold** [comment]
Hi,

No, pgBadger do not have such export mode. The objective of pgBadger is to produce advanced and professional report, generating log with the csv by setting log_destination to csvlog, you don't need pgBadger for that.
