### ISSUE TITLE
extra new column  info  **(2020-09-08T04:00:24.000Z)**  in log files, the pgbadger created nothing.

### ISSUE THREAD

**Issue by dzhang-fec** [darold/pgbadger#609]
Could you please help to find what command (prefix) we need to do (the log is download from s3: it is aurora postgres logs)?
(extra info  **(2020-09-08T04:00:24.000Z)**  in log files, the pgbadger created nothing.)

problem:
extra info  **(2020-09-08T04:00:24.000Z)**  in log files, the pgbadger created nothing.
as129:/home/oracle/AURORA_DAILY/4f15b84a-1adb-492a-820c-c0cedcaf1933/prod-aurora-inst-1.0>>head -1 000000

2020-09-08T04:00:24.000Z 2020-09-08 04:00:24 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(48501):fec_api@fec:[109708]:LOG:  duration: 1.370 ms

---this old log file worked before
2020-09-08 04:00:24 UTC:ec2-52-222-123-172.us-gov-west-1.compute.amazonaws.com(48501):fec_api@fec:[109708]:LOG: duration: 1.370 ms
(not has extra info  **(2020-09-08T04:00:24.000Z)** from s3 aurora log new files)

![image](https://user-images.githubusercontent.com/62447258/92809627-ca1a9e80-f38a-11ea-8524-4228a1fc3fcf.png)

what we did we did 
1) "/usr/local/bin/pgbadger -p '%t:%r:%u@%d:[%p]:' 000000"
passed and show  nothing at the output.

2) if no prefix, I can get the queries - fecas129:/home/oracle/AURORA_DAILY/4f15b84a-1adb-492a-820c-c0cedcaf1933/prod-aurora-inst-1.0>>/usr/local/bin/pgbadger  000000
[========================>] Parsed 739895503 bytes of 739895503 (100.00%), queries: 16745944, events: 3

here is the log data looks like 
2020-09-08T04:00:24.000Z 2020-09-08 04:00:24 UTC:ec2-52-xxx-xxx-000.us-xxx-west-1.compute.amazonaws.com(48501):fxs_api@xyz:[109708]:LOG:  duration: 1.370 ms

 Thanks a lot for your help!

**Comment by dzhang-fec** [comment]
Thanks a lot for your help!
Is there any workaround on this "extra  new column was added by Aurora at s3 logs?)?
Hope we can get a prefix to ignore the new column.
Use script to remove the first column in advance?

Have a good weekend!
Thanks!

**Comment by darold** [comment]
I don't know why Amazon is adding a useless extra timestamp at beginning of the log line but this is also the case with RDS Cloudwatch. Actually RDS, Cloudwatch and Aurora logs can all be handled by pgbadger using `-f rds` without specifying a prefix.

**Comment by dzhang-fec** [comment]
Thanks a lot.

Is it ok to do this now?
pgbadger --f rds postgresql_1234.log

**Comment by dzhang-fec** [comment]
This a a real log files looks like

**Comment by darold** [comment]
Yes it should works if you have valid entries but looks like you have enable `log_duration` and `log_statement_stats` in your postgresql.conf which is not what is required by pgbadger. You should disable these two directives and set `log_min_duration_statement` to 0.

**Comment by dzhang-fec** [comment]
Thanks a lot!
Could you please review the followings

I run 
pgbadger --f rds 000002
[>                        ] Parsed         0 bytes of 162073238 (0.00%), queries                      [>                        ] Parsed   3072104 bytes of 162073238 (1.90%), queries                      [>                        ] Parsed   6437734 bytes of 162073238 (3.97%), queries                      [=>                       ] Parsed   9666377 bytes of 162073238 (5.96%), queries                      [=>                       ] Parsed  12952240 bytes of 162073238 (7.99%), queries                      [==>                      ] Parsed  16317148 bytes of 162073238 (10.07%), querie                      [==>                      ] Parsed  19607076 bytes of 162073238 (12.10%), querie                      [===>                     ] Parsed  22593076 bytes of 162073238 (13.94%), querie                      [===>                     ] Parsed  26153901 bytes of 162073238 (16.14%), querie                      [====>                    ] Parsed  29559183 bytes of 162073238 (18.24%), querie                      [====>                    ] Parsed  32755628 bytes of 162073238 (20.21%), querie                      [=====>                   ] Parsed  36351718 bytes of 162073238 (22.43%), querie                      [=====>                   ] Parsed  39469736 bytes of 162073238 (24.35%), querie                      [======>                  ] Parsed  42718706 bytes of 162073238 (26.36%), querie                      [======>                  ] Parsed  45756411 bytes of 162073238 (28.23%), querie                      [=======>                 ] Parsed  48917729 bytes of 162073238 (30.18%), querie                      [=======>                 ] Parsed  52335774 bytes of 162073238 (32.29%), querie                      [========>                ] Parsed  55395581 bytes of 162073238 (34.18%), querie                      [========>                ] Parsed  58781186 bytes of 162073238 (36.27%), querie                      [=========>               ] Parsed  62304005 bytes of 162073238 (38.44%), querie                      [=========>               ] Parsed  65736121 bytes of 162073238 (40.56%), querie                      [==========>              ] Parsed  68966646 bytes of 162073238 (42.55%), querie                      [==========>              ] Parsed  72166931 bytes of 162073238 (44.53%), querie                      [===========>             ] Parsed  75296883 bytes of 162073238 (46.46%), querie                      [===========>             ] Parsed  78922173 bytes of 162073238 (48.70%), querie                      [============>            ] Parsed  82181241 bytes of 162073238 (50.71%), querie                      [============>            ] Parsed  85649491 bytes of 162073238 (52.85%), querie                      [=============>           ] Parsed  88902173 bytes of 162073238 (54.85%), querie                      [=============>           ] Parsed  92421761 bytes of 162073238 (57.02%), querie                      [==============>          ] Parsed  95969973 bytes of 162073238 (59.21%), querie                      [==============>          ] Parsed  99406426 bytes of 162073238 (61.33%), querie                      [===============>         ] Parsed 102820998 bytes of 162073238 (63.44%), querie                      [===============>         ] Parsed 106150418 bytes of 162073238 (65.50%), querie                      [================>        ] Parsed 109545274 bytes of 162073238 (67.59%), querie                      [================>        ] Parsed 112864834 bytes of 162073238 (69.64%), querie                      [=================>       ] Parsed 116387865 bytes of 162073238 (71.81%), querie                      [=================>       ] Parsed 119601735 bytes of 162073238 (73.79%), querie                      [==================>      ] Parsed 122866432 bytes of 162073238 (75.81%), querie                      [==================>      ] Parsed 126007730 bytes of 162073238 (77.75%), querie                      [===================>     ] Parsed 128861441 bytes of 162073238 (79.51%), querie                      [===================>     ] Parsed 131491996 bytes of 162073238 (81.13%), querie                      [===================>     ] Parsed 134201120 bytes of 162073238 (82.80%), querie                      [====================>    ] Parsed 137188654 bytes of 162073238 (84.65%), querie                      [====================>    ] Parsed 140470893 bytes of 162073238 (86.67%), querie                      [=====================>   ] Parsed 143777577 bytes of 162073238 (88.71%), querie                      [=====================>   ] Parsed 146669270 bytes of 162073238 (90.50%), querie                      [======================>  ] Parsed 150178119 bytes of 162073238 (92.66%), querie                      [======================>  ] Parsed 153314749 bytes of 162073238 (94.60%), querie                      [=======================> ] Parsed 156591114 bytes of 162073238 (96.62%), querie                      [=======================> ] Parsed 159989256 bytes of 162073238 (98.71%), querie                      [========================>] Parsed 162073238 bytes of 162073238 (100.00%), queri                      
es: 0, events: 0
LOG: Ok, generating html report...

But nothing displayed
![image](https://user-images.githubusercontent.com/62447258/93788779-107bc300-fbff-11ea-8255-f338c368a774.png)

**Comment by darold** [comment]
Can you post a part of your log please to try to debug pgbadger.

**Comment by dzhang-fec** [comment]
Thanks a lot for your quickest help, so professional. Appreciate it.
Please review attached
[000002.gz](https://github.com/darold/pgbadger/files/5256598/000002.gz)

**Comment by dzhang-fec** [comment]
[000002.gz](https://github.com/darold/pgbadger/files/5256630/000002.gz)

we have tried 
pgbadger -f rds 000002
pgbadger -000002
no difference

thanks a lot

**Comment by darold** [comment]
If you have change the configuration directives I've talked above you have not reloaded the configuration file. In psql execute `SELECT pg_reload_conf();` that should be enough.

**Comment by dzhang-fec** [comment]
![image](https://user-images.githubusercontent.com/62447258/93805590-f4375080-fc15-11ea-9bab-61d478475288.png)
![image](https://user-images.githubusercontent.com/62447258/93805689-0f09c500-fc16-11ea-9ef0-ed5d68b2652c.png)
![image](https://user-images.githubusercontent.com/62447258/93805893-598b4180-fc16-11ea-8209-8bcc168b2a16.png)

Please find the attached ones above. I don;t have permission on the SELECT pg_reload_conf();....
Please let me know if there is anything you need to more

**Comment by dzhang-fec** [comment]
BTW, it worked fine  before the extra column added.

**Comment by darold** [comment]
In your screenshots the log_duration and log_statement_stats are still enabled and log_min_duration_statement is set to 5 seconds. So you have not applied my recommendations, if you don't know how to change these settings please contact Aurora support service as I'm not an Amazon employee and can not help you. If you have any pgbadger issue feel free to open a new issue.

**Comment by dzhang-fec** [comment]
Thanks a lot.
To change to your recommendations, it needs downtime. We will do it at a window and let you know.

May I have a question?
why it worked before and works (IF we donwload from the aurora log file (not S3)  and in term of you can see the queries do showing in the log files?
      Could you please let me know if there is a workaround to get the pgbadger to get the queries result? (it is "0" nothing  to show up now.

(BTW, actually we set the  log_statement=none, we just want to see the DDL change.We are at Aurora PG 10.7 now )

Thanks again for your best help,

**Comment by darold** [comment]
Ok, I have not understood that it was working before. I do not have much time to work on this now but will try to look at this problem later. For the moment you can remove the first timestamp from your log file as follow:
```
 perl -p -i -e 's/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z //' 000002
```

**Comment by dzhang-fec** [comment]
That works perfectly. Thanks a lot! FYI, we have to use version 11.2 and -f rds works best.
Thanks a lot again!
