### ISSUE TITLE
out.html no dataset pgbadger 11.3

### ISSUE THREAD

**Issue by vanchezzz** [darold/pgbadger#610]
Im configured postgresql.con wit this params
`log_line_prefix = '< %m %t %r %d %u >'`

Log write 
` 2020-09-22 11:28:52.967 MSK 2020-09-22 11:28:52 MSK 127.0.0.1(53736) PA.SHD.qaX zbx_monitor >LOG:  duration: 15.855 ms
< 2020-09-22 11:28:52.967 MSK 2020-09-22 11:28:52 MSK 127.0.0.1(53736) PA.SHD.qaX zbx_monitor >LOG:  QUERY STATISTICS
< 2020-09-22 11:28:52.967 MSK 2020-09-22 11:28:52 MSK 127.0.0.1(53736) PA.SHD.qaX zbx_monitor >DETAIL:  ! system usage stats:
        !       0.003812 s user, 0.001998 s system, 0.015907 s elapsed
        !       [0.009268 s user, 0.003089 s system total]
        !       7396 kB max resident size
        !       0/0 [0/8] filesystem blocks in/out
        !       0/713 [0/1610] page faults/reclaims, 0 [0] swaps
        !       0 [0] signals rcvd, 0/0 [0/0] messages rcvd/sent
        !       1/0 [5/0] voluntary/involuntary context switches
< 2020-09-22 11:28:52.967 MSK 2020-09-22 11:28:52 MSK 127.0.0.1(53736) PA.SHD.qaX zbx_monitor >STATEMENT:  WITH T AS (
                SELECT
                        sum(CASE WHEN relkind IN ('r', 't', 'm') THEN pg_stat_get_numscans(oid) END) seq,
                        sum(CASE WHEN relkind = 'i' THEN pg_stat_get_numscans(oid) END) idx
                FROM pg_class
                WHERE relkind IN ('r', 't', 'm', 'i')
        )
        SELECT row_to_json(T)
        FROM T
< 2020-09-22 11:28:52.969 MSK 2020-09-22 11:28:52 MSK 127.0.0.1(53736) PA.SHD.qaX zbx_monitor >LOG:  disconnection: session time: 0:00:00.025 user=zbx_monitor database=PA.SHD.qaX host=127.0.0.1 port=53736
`
And request

[root@db noindex]# pgbadger --prefix '%m-%t-%d-%h-%u' /store/db/pg_log/postgresql-*.log -o /usr/share/httpd/noindex/index.html -f stderr
[========================>] Parsed 5171472767 bytes of 5171472767 (100.00%), queries: 0, events: 0: 0
LOG: Ok, generating html report...

What my problem?

**Comment by darold** [comment]
Why don't you use the same prefix?
```
pgbadger --prefix '< %m %t %r %d %u >' /store/db/pg_log/postgresql-*.log -o /usr/share/httpd/noindex/index.html -f stderr
```

**Comment by darold** [comment]
Ah and the problem with your prefix is that it doesn't contain the pid which is mandatory, you should include  `%p` in your log_line_prefix value.

**Comment by vanchezzz** [comment]
im add %p in log_line_prefix value? i   need restart postgres after this?

execute this script 
[root@db db]# pgbadger --prefix '< %m %t %r %d %u >' /store/db/pg_log/postgresql-*.log -o /usr/share/httpd/noindex/index.html -f stderr
[========================>] Parsed 5265204029 bytes of 5265204029 (100.00%), queries: 0, events: 1
LOG: Ok, generating html report...

After any data is present report html

**Comment by vanchezzz** [comment]
Data about connections present.
I dont see data in  Locks, Queries and Temp Files, no dataset.

**Comment by darold** [comment]
have you change the prefix option?

**Comment by vanchezzz** [comment]
yep, I need to run collection again? and no need to restart postgres?

**Comment by darold** [comment]
try.

**Comment by vanchezzz** [comment]
pgbadger --prefix '< %m %t %r %d %u %p >' /store/db/pg_log/postgresql-*.log -o /usr/share/httpd/noindex/index.html -f stderr
[========================>] Parsed 5308109927 bytes of 5308109927 (100.00%), queries: 0, events: 0
LOG: Ok, generating html report...

No dataset in connection and in others tabs

**Comment by darold** [comment]
What is the value of `log_line_prefix` and can you post a line of the PostgreSQL log file generated by this new prefix?

**Comment by vanchezzz** [comment]
i reload postgres daemon and now log is this format:
`< 2020-09-22 14:26:41.217 MSK 2020-09-22 14:26:41 MSK 127.0.0.1(59688) PA.SHD.qa zbx_monitor 10009 >LOG:  duration: 9.057 ms
< 2020-09-22 14:26:41.217 MSK 2020-09-22 14:26:41 MSK 127.0.0.1(59688) PA.SHD.qa zbx_monitor 10009 >LOG:  QUERY STATISTICS
< 2020-09-22 14:26:41.217 MSK 2020-09-22 14:26:41 MSK 127.0.0.1(59688) PA.SHD.qa zbx_monitor 10009 >DETAIL:  ! system usage stats:
        !       0.005699 s user, 0.003392 s system, 0.009069 s elapsed
        !       [0.006758 s user, 0.008689 s system total]
        !       8312 kB max resident size
        !       0/0 [0/8] filesystem blocks in/out
        !       0/888 [0/1788] page faults/reclaims, 0 [0] swaps
        !       0 [0] signals rcvd, 0/0 [0/0] messages rcvd/sent
        !       0/0 [4/0] voluntary/involuntary context switches
< 2020-09-22 14:26:41.217 MSK 2020-09-22 14:26:41 MSK 127.0.0.1(59688) PA.SHD.qa zbx_monitor 10009 >STATEMENT:  WITH T AS (
                SELECT
                        age(relfrozenxid),
                        current_setting('autovacuum_freeze_max_age')::integer fma
                FROM pg_class
                WHERE relkind IN ('r', 't'))
        SELECT row_to_json(T2)
        FROM (
                SELECT extract(epoch FROM now())::integer ts,
                (
                        SELECT ((1 - max(age)::double precision / current_setting('autovacuum_freeze_max_age')::integer) * 100)::numeric(9,6)
                        FROM T
                        WHERE age < fma
                ) prc_before_av,
                (
                        SELECT ((1 - max(age)::double precision / -((1 << 31) + 1)) * 100)::numeric(9,6)
                        FROM T
                ) prc_before_stop
        ) T2
< 2020-09-22 14:26:41.218 MSK 2020-09-22 14:26:41 MSK 127.0.0.1(59688) PA.SHD.qa zbx_monitor 10009 >LOG:  disconnection: session time: 0:00:00.017 user=zbx_monitor database=PA.SHD.qa host=127.0.0.1 port=59688`

config is ok

log_line_prefix = '< %m %t %r %d %u %p >'
 i not see    %p = process ID

**Comment by darold** [comment]
Why are you logging twice the timestamp `%m %t `. I think you'd better read the pgbadger documentation about the default prefix to use and PostgreSQL configuration to use.

**Comment by BambamSchmidt** [comment]
Which language are you using for messages? pgbader ist only working with 

lc_messages = 'en_US.UTF-8'

**Comment by darold** [comment]
Configuration issue, closing.
