### ISSUE TITLE
Doesn't work in postgresql 13?

### ISSUE THREAD

**Issue by kanwei** [darold/pgbadger#611]
I just upgraded to PG13, copying the same config as PG12's, but pgbadger now returns no datasets using the same config. Any compatibility issues there?

**Comment by darold** [comment]
You should post one or two line of you log and your pgbadger command otherwise I can not help. There could be some incompatibilities issues with PG13 but on some special logs like autovacuum for example.

**Comment by kmoppel** [comment]
Can confirm that v13 CSVLOG mode displays "NO DATASET". Seems to be caused by the freshly added "backend_type" column. This seemed to fix it:

```
diff --git a/pgbadger b/pgbadger
index 5ac4650..de877a2 100755
--- a/pgbadger
+++ b/pgbadger
@@ -3573,7 +3573,7 @@ sub process_file
                                last CSVLOOP if ($terminate);
 
                                # Number of columns in csvlog (22 before 9.0 and 23 from 9.0 to current)
-                           next if ( ($#{$row} != 22) && ($#{$row} != 21) );
+                         next if ( ($#{$row} < 21) && ($#{$row} > 23) );
 
                                # Set progress statistics
                                $cursize += length(join(',', @$row));

```

**Comment by darold** [comment]
Thanks for the patch, applied with commit bcdbe4f.
