### ISSUE TITLE
--ssh-option error

### ISSUE THREAD

**Issue by msartor92** [darold/pgbadger#615]
When i try to run over docker dalibo/pgbadger with flag --remote host "my-host" and --ssh-option "StrictHostKeyChecking=no" container fail with following logs

`ssh: Could not resolve hostname stricthostkeychecking=no: Name does not resolve
ssh: Could not resolve hostname stricthostkeychecking=no: Name does not resolve
`
I suppose on an error of parameter parsing

**Comment by darold** [comment]
I do not maintain this docker project, there is discussion about it here https://github.com/darold/pgbadger/pull/543 

Why not using perl instead of docker?
