### ISSUE TITLE
Wrong sort method in temp file queries

### ISSUE THREAD

**Issue by slardiere** [darold/pgbadger#616]
In the table listing Queries generating the most temporary files (#queries-generating-most-temporary-files), queries should be sorted by the number of query found (Count). But it seems that the count is not sorted on numerical reverse, but alphanumerical reverse, then we could get sort like that : 

.1 7
.2 643
.3 6
.4 578
.5 4

Instead of : 

.1 643
.2 578
.3 7
.4 6
.5 4

**Comment by darold** [comment]
Commit d321274 might fix this issue. Actually there was a try on a hybrid sort between count and file size which was stupid, I have limited the sort on the count.

**Comment by slardiere** [comment]
Thank you, I can confirm that the bug is corrected.
