### ISSUE TITLE
Missing Checkpoint info

### ISSUE THREAD

**Issue by MichaelDBA** [darold/pgbadger#618]
I am using PG 10 on RDS with default non-changeable log_line_prefix: '%t:%r:%u@%d:[%p]:'
I am running pgbadger 11.3 on CentOS 8.
I am parsing one 4 GB log file that I downloaded from RDS.  It contains 1 hour of time.
Here is the command:
`pgbadger postgresql.log.2020-11-09-21.log -j 6 -d  mydb -p '%t:%r:%u@%d:[%p]:'  -o /var/lib/pgsql/pgbadger_reports/pgbadger_2020-11-09-21.html`

I am missing everything on the Checkpoints page.  Everything else looks good on the pgbadger html output report.

Here are my config settings:
```
log_min_duration_statement = 0
log_duration = off
log_statement = 'none'
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
log_error_verbosity = default
```
I see checkpoint start and complete lines in the log file, but they are not being picked up by pgbadger.

**Comment by MichaelDBA** [comment]
I am wondering if specifying a specific database prevents some global things from being captured like checkpoints?

**Comment by darold** [comment]
Hi Michael,

Yes the checkpoint are not related to a specific database and as the lines parsed are filtered by database mydb the checkpoint statistics are not available. For autovaccum you will see only the information about tables from the database in the filter.
