### ISSUE TITLE
how to interpret "User(s) involved" in top queries

### ISSUE THREAD

**Issue by HeikoOnnebrink** [darold/pgbadger#619]
Hi
need a short advice how to interpret **User(s) involved** output in below example.
Times executed (here 44) is per session? is this some average or from where it is taken?
If it is per session how is the total duration calculated? If it is Times Executed * average duration the value should be different..

Thx for clarification 
cheers 
Heiko
(and thx for this great tool)

![image](https://user-images.githubusercontent.com/19688787/98778667-fc7c6280-23f2-11eb-935d-ce7ac7b021f3.png)

**Comment by darold** [comment]
Hi,

Users involved is the list of users that have executed the query, I guess that most of the time this is a single application user but there could be several. The Time executed information is for the full log or the day if you use the incremental mode and this is not an average, this is the total count of when the query was parsed in the log. The total duration is the sum of the statement duration found in the log. Additionally: Total duration / Times executed = Avg duration

cheers,

**Comment by HeikoOnnebrink** [comment]
Thx for answering..

but what about the Total Duration of 44s605ms of the User(s) involved stat..
Question was mainly referring to that one ..

**Comment by darold** [comment]
Well this is the total time and number of execution per user. When there is a single user reported the time and total number should be the same as the Total duration and Times executed report. Here it looks like there is a problem, I will double check the code. What was the pgbager command used?

**Comment by HeikoOnnebrink** [comment]
we call incremental but pass
pgBadger -I -R 13 -v --format STDERR --outdir somefoder /log/*.log

**Comment by darold** [comment]
What version of pgbadger are you using? I'm not able to reproduce the problem, even with several users on a query it reports the exact per user related time and the total correspond to the global duration time.

**Comment by HeikoOnnebrink** [comment]
we use 11.1 .. but we can try with 11.3 to reproduce the same ..

**Comment by HeikoOnnebrink** [comment]
just repeated with 11.3 and still the same..
as report is incremental I am not sure if this test is meaningful as previous data was already saved away in bin format ?

I also expanded in this test the hourly data and they look fine and their sum match the total value

![image](https://user-images.githubusercontent.com/19688787/98844270-5fe6ae80-244c-11eb-8a89-c6b6475cb49c.png)

**Comment by HeikoOnnebrink** [comment]
I also generated a non incremental report from same db from yesterday full day .. same issue here:

![image](https://user-images.githubusercontent.com/19688787/98844641-ebf8d600-244c-11eb-8aaa-fd508a286c35.png)

**Comment by HeikoOnnebrink** [comment]
is there a way how I can upload you a sample log, e.g. the one belonging to the above created report (do not want to paste something here).
Assume this would make debugging more easy.

**Comment by darold** [comment]
you can send it to my email address < gilles AT darold DOT net >

**Comment by HeikoOnnebrink** [comment]
sent out ..

**Comment by darold** [comment]
Ok, very helpful to find the source of the problem. Actually if you look at the report some queries reported doesn't have a user involved. This is not possible unless you are not logging users (`%u`) which you are doing because of some other queries reporting the right users executing them. The source of the problem is that you are not using the default prefix in your log or that you are not providing the prefix in the pgbadger command line. Likking at your log you should use the following command to parse the logs file:
```
pgbadger -p '%m [%p] %u@%d ' -I -R 13 -v --format stderr --outdir somefoder /log/*.log
```
You will see that everything will be solved.

**Comment by HeikoOnnebrink** [comment]
Will give it a try..
Up to now we did not touch it and relied on the defaults on PostgreSQL and pgBadger side.
As a conclusion we should explicitly set the log format on PostgreSQL side and inject the same setting also to pgBadger using --prefix option ?

**Comment by HeikoOnnebrink** [comment]
In between I ran a test with above log prefix and I can confirm that issue gets fixed in this way 👍

**Comment by darold** [comment]
I think the default PostgreSQL prefix you are talking about is the one provided by Ubuntu, the default prefix for pgbadger is explained in the documentation. If you have any doubt you can always safely add the value of the postgresql.conf `log_line_prefix` directive to the `-p` option of pgbadger.
