### ISSUE TITLE
no new entries in your log(s) since last run.

### ISSUE THREAD

**Issue by denis-argentin** [darold/pgbadger#620]
A use the command:
`pgbadger -v -f -J2 -I --exclude-query='^(COPY)' --exclude-appname pg_dump ssh://database01//pglog/postgresql-* -O /backup/pgbadger/database01/ --pid-file /tmp/database01'.pid'
`
It runs every hour on cron for al my databases.

Others databases generate several files every minute but this instance generate only 1 the whole day. Therefore he get stuck on the first execution and do not update the new entries as the error.

`no new entries in your log(s) since last run.`

**Comment by darold** [comment]
I think probably there is a difference between the log_line_prefix or the lc_messages? This is difficult to say what happen without a precise view of the log files parsed.

**Comment by denis-argentin** [comment]
```
log_line_prefix = '%t [%p]: [%l] user=%u,db=%d,app=%a,host=%h ' 
lc_messages = 'C'  
```

A view of log lines:

```
2020-11-16 23:59:54 -03 [24324]: [1] user=[unknown],db=[unknown],app=[unknown],host=127.0.0.1 LOG:  connection received: host=127.0.0.1 port=48390
2020-11-16 23:59:54 -03 [24324]: [2] user=zbx_monitor,db=cep,app=[unknown],host=127.0.0.1 LOG:  connection authorized: user=zbx_monitor database=cep
2020-11-16 23:59:54 -03 [24324]: [3] user=zbx_monitor,db=cep,app=psql,host=127.0.0.1 LOG:  disconnection: session time: 0:00:00.006 user=zbx_monitor database=cep host=127.0.0.1 port=48390
2020-11-16 23:59:55 -03 [22511]: [15] user=,db=,app=,host= LOG:  automatic vacuum of table "sometable": index scans: 0
        pages: 0 removed, 20185 remain, 0 skipped due to pins, 0 skipped frozen
        tuples: 0 removed, 714387 remain, 229153 are dead but not yet removable, oldest xmin: 1167151
        buffer usage: 18405 hits, 0 misses, 0 dirtied
        avg read rate: 0.000 MB/s, avg write rate: 0.000 MB/s
        system usage: CPU: user: 0.05 s, system: 0.03 s, elapsed: 5.67 s
2020-11-16 23:59:56 -03 [24354]: [1] user=[unknown],db=[unknown],app=[unknown],host=127.0.0.1 LOG:  connection received: host=127.0.0.1 port=48396
2020-11-16 23:59:56 -03 [24354]: [2] user=zbx_monitor,db=postgres,app=[unknown],host=127.0.0.1 LOG:  connection authorized: user=zbx_monitor database=postgres
2020-11-16 23:59:56 -03 [24354]: [3] user=zbx_monitor,db=postgres,app=psql,host=127.0.0.1 LOG:  disconnection: session time: 0:00:00.003 user=zbx_monitor database=postgres host=127.0.0.1 port=48396
```

**Comment by darold** [comment]
I don't see any problem here, can you provide the debug output of the command:
```
pgbadger -v -f -J2 -I --exclude-query='^(COPY)' --exclude-appname pg_dump ssh://database01//pglog/postgresql-* -O /backup/pgbadger/database01/ --pid-file /tmp/database01'.pid'
```
Also which version of pgbadger are you using?

**Comment by denis-argentin** [comment]
Version 11.3

```
DEBUG: Looking for remote filename using command: ssh database01 "ls '/pglog/'postgresql-*"
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-08_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 35674186
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-09_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 42799324
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-10_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 48040667
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-11_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 42338138
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-12_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 39562174
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-13_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 44946048
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-14_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 37124681
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-15_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 34746772
DEBUG: Looking for file size using command: ssh database01 "ls -l '/pglog/postgresql-2020-11-16_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 31217243
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-08_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-08_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-08_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-08_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-09_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-09_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-09_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-09_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-10_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-10_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-10_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-10_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-11_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-11_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-11_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-11_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-12_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-12_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-12_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-12_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-13_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-13_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-13_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-13_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-14_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-14_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-14_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-14_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-15_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-15_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-15_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-15_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-16_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://database01//pglog/postgresql-2020-11-16_000000.log
DEBUG: Retrieving log entries using command: ssh database01 "cat '/pglog/postgresql-2020-11-16_000000.log'" |
DEBUG: this file has already been parsed: ssh://database01//pglog/postgresql-2020-11-16_000000.log, there no new lines in this file
DEBUG: the log statistics gathering took: 3 wallclock secs ( 0.01 usr  0.05 sys +  0.37 cusr  0.21 csys =  0.64 CPU)
DEBUG: no new entries in your log(s) since last run.
DEBUG: building reports took:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
DEBUG: the total execution time took:  3 wallclock secs ( 0.01 usr  0.05 sys +  0.37 cusr  0.21 csys =  0.64 CPU)

```

**Comment by denis-argentin** [comment]
Just for better understand, the cron job runs every hour:50, starting after 4AM so it runs at 4:50 an keep the LAST_PARSED file:

`2020-11-17 04:50:10     5693780 2020-11-17 04:50:10 -03 [20590]: [3] user=zbx_monitor,db=postgres,app=psql,host=127.0.0.1 LOG:  disconnection: session time: 0:00:00.008 user=zbx_monitor database=postgres host=127.0.0.1 port=40814`

**Comment by denis-argentin** [comment]
`[root@backup-pro-02 db-fisco-pro-02]# sudo -u postgres pgbadger -v -f stderr  -J2 -I --exclude-query='^(COPY)' --exclude-appname pg_dump ssh://db-login-pro-01//pglog/postgresql-* -O /backup/pgbadger/db-login-pro-01/ --pid-file /tmp/db-login-pro-01'.pid'
DEBUG: Looking for remote filename using command: ssh db-login-pro-01 "ls '/pglog/'postgresql-*"
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-16_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 53189800
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-17_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 67109221
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-17_143115.log'" | awk '{print $5}'
DEBUG: Remote file size: 18659623
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-18_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 46693931
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-19_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 48934014
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-20_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 39113542
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-21_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 37034200
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-22_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 35330881
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-23_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 41971408
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-24_000000.log'" | awk '{print $5}'
DEBUG: Remote file size: 67148234
DEBUG: Looking for file size using command: ssh db-login-pro-01 "ls -l '/pglog/postgresql-2020-11-24_094439.log'" | awk '{print $5}'
DEBUG: Remote file size: 17755143
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-16_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-16_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-16_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-16_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-17_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-17_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-17_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-17_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-17_143115.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-17_143115.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-17_143115.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-17_143115.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-18_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-18_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-18_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-18_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-19_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-19_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-19_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-19_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-20_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-20_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-20_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-20_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-21_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-21_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-21_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-21_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-22_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-22_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-22_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-22_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-23_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-23_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-23_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-23_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-24_000000.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-24_000000.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-24_000000.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-24_000000.log, there no new lines in this file
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-24_094439.log'" |
DEBUG: Autodetected log format 'default' from ssh://db-login-pro-01//pglog/postgresql-2020-11-24_094439.log
DEBUG: Retrieving log entries using command: ssh db-login-pro-01 "cat '/pglog/postgresql-2020-11-24_094439.log'" |
DEBUG: this file has already been parsed: ssh://db-login-pro-01//pglog/postgresql-2020-11-24_094439.log, there no new lines in this file
DEBUG: the log statistics gathering took: 5 wallclock secs ( 0.02 usr  0.03 sys +  0.44 cusr  0.25 csys =  0.74 CPU)
DEBUG: no new entries in your log(s) since last run.
DEBUG: building reports took:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
DEBUG: the total execution time took:  5 wallclock secs ( 0.02 usr  0.03 sys +  0.44 cusr  0.25 csys =  0.74 CPU)
`

Still the same. :?

**Comment by darold** [comment]
How about if you add the following to the pgbadger command line: `--prefix '%t [%p]: [%l] user=%u,db=%d,app=%a,host=%h '` ?

**Comment by denis-argentin** [comment]
I tried. And I also tried to remove the `-f`, with the `-L new_last`. 

Basically what i see is that pgbadger can't read the same log more the once.

Also im getting a new error:
`Magic number checking on storable file failed at /usr/lib64/perl5/vendor_perl/Storable.pm line 399, at /bin/pgbadger line 13429. `

**Comment by darold** [comment]
I guess you have copied the incremental data on a new server or you have upgraded the machine? In incremental mode this is expected that a log file is read only once. Any log entry older than the one registered in the history file will be skipped.

**Comment by darold** [comment]
Should this issue be closed?
