### ISSUE TITLE
Unable to see duration of queries using rds logs

### ISSUE THREAD

**Issue by mubarak1988** [darold/pgbadger#621]
We have set the following values for our RDS database given below. However, the report generates no duration for the queries
.  (pgbadger V 11.3)
![Screenshot from 2020-11-18 11-52-22](https://user-images.githubusercontent.com/18236753/99495531-9e242680-2994-11eb-8120-84200d43ebf6.png)
![Screenshot from 2020-11-18 11-56-34](https://user-images.githubusercontent.com/18236753/99495930-3fab7800-2995-11eb-9ea3-1c61fbf678f9.png)

            log_statement: all
            log_duration: 1
            log_checkpoints: on
            log_connections: on
            log_disconnections: on
            log_lock_waits: on
            log_temp_files: 0
            log_autovacuum_min_duration: 0
            log_error_verbosity: DEFAULT
            log_min_duration_statement: 0
            rds.force_autovacuum_logging_level: log

**Comment by darold** [comment]
you must set `log_statement: none`

**Comment by mubarak1988** [comment]
Thank you Darold. After this change i am able to see the duration of the queries now.
