### ISSUE TITLE
Unknown syslog line format for multiline logs

### ISSUE THREAD

**Issue by jdockerty** [darold/pgbadger#624]
When running `pgbadger` against the syslog file I have received, I only see errors on the multi-line query lines as it seems to not be able to parse it properly, my assumption is this is because the `log_line_prefix` isn't present on those lines?

There are a number of connections which are received/disconnected too, but these do not seem to display errors when using a verbose output. Although they are not present in the output report.

An example snippet from the log file is
```
Nov 24 16:38:58 my-db-8 postgresql-11: [901-1] user=fusion,db=intelligence,app=[unknown],client=[local] LOG:  duration: 19623.550 ms  execute pdo_stmt_00006117: select <QUERY>
Nov 24 16:38:58 my-db-8 postgresql-11: [901-2] user=fusion,db=intelligence,app=[unknown],client=[local] DETAIL:  parameters: $1 = <params>
Nov 24 16:38:58 my-db-8 postgresql-11: [8-1] user=,db=,app=,client= LOG:  temporary file: path "base/pgsql_tmp/pgsql_tmp1489068.0", size 42500096
Nov 24 16:38:58 my-db-8 postgresql-11: [8-2] user=,db=,app=,client= STATEMENT:  select
Nov 24 16:38:58 my-db-8 postgresql-11: [8-3] 	               <Query-line-1>,
Nov 24 16:38:58 my-db-8 postgresql-11: [8-4] 	                <Query-line-2>,
Nov 24 16:38:58 my-db-8 postgresql-11: [8-5] 	               <Query-line-3>,
Nov 24 16:38:58 my-db-8 postgresql-11: [8-6] 	               <Query-line-4> 
Nov 24 16:38:58 my-db-8 postgresql-11: [8-7] 	             <Query-line-5>
```

The returned verbose output would then be
```
DEBUG: Unknown syslog line format: Nov 24 16:38:58 my-db-8 postgresql-11: [8-3] <Query-line-1>,
...
```

The `log_line_prefix` on the database is set to `user=%u,db=%d,app=%a,client=%h ` with `log_destination` as `syslog`.

The command I am running has moved between using the prefix and not, whilst also trying different variations, although the issues still persist.

`pgbadger --prefix "user=%u,db=%d,app=%a,client=%h " -v -f syslog <log_file>`

and have attempted others like

`pgbadger --prefix "[%p-%l] user=%u,db=%d,app=%a,client=%h " -v -f syslog <log_file>`

Is this an issue which needs to be fixed or am I missing something with my prefix indication?

**Comment by darold** [comment]
What operating system or cloud system produce these logs? Actually this is not a common syslog format. You have the following prefix:
```
Nov 24 16:38:58 my-db-8 postgresql-11: [901-1] user=fusion,db=intelligence,app=[unknown],client=[local] LOG: ...
```
where the expecting format would:
```
Nov 24 16:38:58 my-db-8 postgresql-11[32456]: [901-1] user=fusion,db=intelligence,app=[unknown],client=[local] LOG: ...
```
outside the format the trace seems to not include the pid (`[32456]` in my example) which prevent pgbadger to build statistics.

**Comment by jdockerty** [comment]
The logs are generated from Digital Ocean, so their managed DB service.

Do you think there is anyway to transform the logs into a usable state? Or is it a dead end to be able to analyse these logs they've sent, as they're not in the appropriate format to do so in the first place?

**Comment by darold** [comment]
If you can change the log_line_prefix value set it like that: `'user=%u,db=%d,app=%a,client=%h,pid=%p '` I will train the badger to support more exotic format. Please post some log lines with this change so that I will have a working sample.

**Comment by jdockerty** [comment]
Since the database is managed by Digital Ocean, I don't have access to alter the `log_line_prefix` setting itself unfortunately. I believe without that, it could be a dead end?

**Comment by darold** [comment]
Unfortunately but you should report this discussion to Digital Ocean, being a cloud solution provider that can not support pgBadger is not a good point. I think they can do something.

**Comment by jdockerty** [comment]
I shall definitely do that, much appreciated for taking a look at my issue Darold, thank you.
