### ISSUE TITLE
Report on sessions' idle times

### ISSUE THREAD

**Issue by gleu** [darold/pgbadger#626]
It doesn't seem easy to do, but it would definitely be helpful. I'd like to see a report on idle times of sessions. I guess it could work as "session duration - sum(queries duration)" for a specific session. Of course, the user would have to log all queries, otherwise it wouldn't be reliable. Anyway, this would help to know how much idle time is lost, and if a pooler transaction mode would be interesting.

It would be even better if it could recognize "idle" times and "idle in transaction" times, but that seems a bit harder to do reliably.

That report would go in the Sessions tab.

**Comment by darold** [comment]
Commit 9782683 adds this feature. Reports available in the "Sessions" tab of the "Global Stats" and in the "Sessions" tab of the "General Activity" report (per hour).

**Comment by gleu** [comment]
Looks good!
