### ISSUE TITLE
AWS S3 sync LAST_PARSED break Incremental mode using a k8s pod

### ISSUE THREAD

**Issue by julianodba** [darold/pgbadger#629]
Running `pgbadger -I` (--incremental) using a Kubernetes pod it works until the pod is restarted (recreated from scratch) where all files are deleted (postgres.log, index.html, LAST_PARSED, bin files, etc). 

In order to continue to parse the logs by the same point I am downloading the LAST_PARSED file from S3 before run `pgbadger -I ` then uploading the new parsed files (HTML and LAST_PARSED) to s3 again. 

But, the new index.html uploaded is broken and displaying only the minute from the current day where when pgbadger was executed. 

download LAST_PARSED from s3 to clean pod:
`aws s3 sync --exclude "*" --include "LAST_PARSED" s3://$bucket_name/$bucket_prefix/$rds_id $pgbadger_html `

run pgbadger incremental:
`pgbadger -I $temp_logs/postgresql.log.* -f stderr --prefix='%t:%r:%u@%d:[%p]:' --jobs 4 -O $pgbadger_html`

upload files to HTML and LAST_PARSED to s3:
`aws s3 sync --exclude "*" --include "*.html" $pgbadger_html s3://$bucket_name/$bucket_prefix/$rds_id --acl bucket-owner-full-control`

Not sure if it is a bug so sorry for posting it here, but I have been searching this on the internet for days and did so many tests without success. Please let me know if you need more info. My set up is below:

Postgres Aurora v11.8
pgbadger v 11.4
Debian GNU/Linux 10 (buster)
kubectl Client Version: v1.19.2
kubectl Server Version: v1.17.12-eks-7684af
helm v3.3.1+g249e52

The objective is to set up a Kubernetes job so every time I run pgbadger job the pod is created/deleted.

**Comment by darold** [comment]
Binary files (*.bin) are needed too. Have you tried using some local mount of your S3 drive? You can use s3fs-fuse (https://github.com/s3fs-fuse/s3fs-fuse) for example, it could simplify your process.

**Comment by julianodba** [comment]
Oh, the binary files... that explains a lot!
Wow, this s3fs is a great idea! Thank you so much sir
This issue can be closed :)
