### ISSUE TITLE
Issue parsing Heroku log format/logplex

### ISSUE THREAD

**Issue by rossng** [darold/pgbadger#631]
When running pgBadger on my Heroku logs, I found that it couldn't parse them as 'logplex' format entries.

It seems that my logs were slightly different from the ones that pgBadger expects. Rather than:

```
2021-01-20T00:06:12+00:00 app[postgres.19897]: [NAVY] [1072-4]
```

they were:

```
2021-01-20T00:06:12.000000+00:00 app[postgres.19897]: [NAVY] [1072-4]
```

I have no idea if this is a universal change, but I guess it might be a good idea to update the regexes to handle this possibility.

**Comment by darold** [comment]
Commit 941779a add support to this log line prefix including microseconds, please give a try to latest development code.

**Comment by rossng** [comment]
This seems to work great ☺

Thanks for your support and for this useful tool!
