### ISSUE TITLE
Use of uninitialized value in pattern match

### ISSUE THREAD

**Issue by arlt** [darold/pgbadger#636]
pgBadger version 11.5

`Use of uninitialized value in pattern match (m//) at /usr/bin/pgbadger line 20247.`

I am not sure, but probably the problem did not exist in version 11.4.

I don't know how to provide more useful information.

**Comment by darold** [comment]
Commit 92cc2dc might solve this issue introduced by pgFormatter code update.

**Comment by arlt** [comment]
works - thanks a lot for your support!
