### ISSUE TITLE
MS Windows - Wrong content for extracted resource file 'pgbadger.min.js'

### ISSUE THREAD

**Issue by bbourgier** [darold/pgbadger#639]
Hi,

Environment:
MS Windows Server 2016
Strawberry Perl v5.32.1
pgBadger v11.5

On Windows when doing the "gmake install", there is a call to 'pl2bat.bat' perl utility to create 'pgbadger.bat' from the release 'pgbadger' perl module.
'pl2bat.bat' will automatically add the following footer to the 'pgbadger.bat' file:

```
__END__
:endofperl
@set "ErrorLevel=" & @goto _undefined_label_ 2>NUL || @"%COMSPEC%" /d/c @exit %ErrorLevel%
```

This footer is problematic when the __DATA__ resources are writen to files or inline because the parse and write loop in:
sub write_resources
does not take it into account.

For instance, when picking external resource files, the 'pgbadger.min.js' file content will be:
```
function create_download_button(a,b){if(b==undefined){ ...
__END__
:endofperl
@set "ErrorLevel=" & @goto _undefined_label_ 2>NUL || @"%COMSPEC%" /d/c @exit %ErrorLevel%
```

And this makes this '.js' file wrong, which causes multiple javascript errors when loading the pgbadger html pages and no graph displayed.

The fix is very simple:

In '/pgbadger':

Replace:
```
sub write_resources
{
	# Write resource file to report directory or return resources in and array of lines
	my $rscfh;
	my @contents = ();
	my $endfile = '';
	my $file = '';
	my $major_version = $VERSION;
	$major_version =~ s/\..*//;

	my $rscdir = $html_outdir || $outdir;
	while (my $l = <DATA>) {
		if ($l =~ /^WRFILE: ([^\s]+)/) {
			$file = $1;
...
```

With:
```
sub write_resources
{
	# Write resource file to report directory or return resources in and array of lines
	my $rscfh;
	my @contents = ();
	my $endfile = '';
	my $file = '';
	my $major_version = $VERSION;
	$major_version =~ s/\..*//;

	my $rscdir = $html_outdir || $outdir;
	while (my $l = <DATA>) {
		last if $l =~ /^__END__$/;
		if ($l =~ /^WRFILE: ([^\s]+)/) {
			$file = $1;
...
```
("last if" line added)

For postgreSQL / pgBadger MS Windows compatibility, this seems to me quite important since without this fix, pgBadger doesn't display any graph at all.

Thanks in advance.

Bertrand

**Comment by darold** [comment]
Interesting, I was not aware of that. Commit e245f36 applies your patch, please test it and let me know if the portability problem is fully solved.

**Comment by bbourgier** [comment]
Yes thanks. Commit e245f36 fixes the portability issue.
With the '--extra-files' flag:
The 'pgbadger.min.js' file is properly generated.
Without the '--extra-files' flag:
The <pre><script>...</script></pre> block content is correct.
Thanks.
Bertrand

**Comment by darold** [comment]
Good news, closing.
