### ISSUE TITLE
MS Windows - Calendar view broken because POSIX::strftime("%u") not supported on MS Windows

### ISSUE THREAD

**Issue by bbourgier** [darold/pgbadger#640]
Hi,

Environment:
MS Windows Server 2016
Strawberry Perl v5.32.1
pgBadger v11.5 + commit e245f36

On MS Windows implementation (is it perl or pure windows, I'm not sure), the "%u" tag for POSIX::strftime is not supported.
Whereas the "%w" tag is working properly.
See tests:
```
c:\pgbadger>perl -MPOSIX -e " print POSIX::strftime ('%u',1,1,1,23,01,121)"

c:\pgbadger>perl -MPOSIX -e " print POSIX::strftime ('%w',1,1,1,23,01,121)"
2
c:\pgbadger>
```
As you can see, the "%u" call returns nothing.

And this compatibility issue completely breaks the calendar view.

I searched a bit and fixed it.
So here is the fix.

Replace the current "get_day_of_week" implementation:
```
# Returns day number of the week of a given days
sub get_day_of_week
{
	my ($year, $month, $day) = @_;

#       %w     The day of the week as a decimal, range 0 to 6, Sunday being 0.

	my $weekDay = '';
	if (!$week_start_monday) {
		# Start on sunday = 0
		$weekDay = POSIX::strftime("%w", 1,1,1,$day,--$month,$year-1900);
	} else {
		# Start on monday = 1
		$weekDay = POSIX::strftime("%u", 1,1,1,$day,--$month,$year-1900);
		$weekDay--;
	}

	return $weekDay;
}
```

with:
```
# Returns day number of the week of a given days
sub get_day_of_week
{
	my ($year, $month, $day) = @_;

#       %w     The day of the week as a decimal, range 0 to 6, Sunday being 0.

	my $weekDay = '';
	if (!$week_start_monday) {
		# Start on sunday = 0
		$weekDay = POSIX::strftime("%w", 1,1,1,$day,--$month,$year-1900);
	} else {
		# Start on sunday = 0
		$weekDay = POSIX::strftime("%w", 1,1,1,$day,--$month,$year-1900);
		$weekDay = (($weekDay+7)-1) % 7;
	}

	return $weekDay;
}
```
So I modified the "else" part to use the "%w" flag instead of the "%u" flag.

I tested it and it works.
The calendar view is back in order.

And here again this is blocking when using pgBadger on MS Windows.

Thanks in advance.

Bertrand

**Comment by darold** [comment]
Are you using `--start-monday` option?

**Comment by bbourgier** [comment]
yes. I was using "start-monday".
and after fixing the source code, I tried with and without the "start-monday" option and I get the proper calendar views for both mode.

**Comment by darold** [comment]
Commit 895480f applies your patch.

**Comment by bbourgier** [comment]
Thanks. Commit 895480f tested and working.
Bertrand
