### ISSUE TITLE
LAST_PARSED offset wrong when Log File EOL pattern is on 2 bytes (Windows case: 0D0A)

### ISSUE THREAD

**Issue by bbourgier** [darold/pgbadger#641]
Hi,

This one was not so simple.
I was wondering why the incremental mechanism did not trigger whereas my log files were growing with new lines.
So I debugged the code and I saw that the LAST_PARSED offset stored in the LAST_PARSED file was not correct.
After some analysis, it appeared it was missing the exact count of EOL in the Log File until the last parsed line.

So I looked at the line that the **process_file** routine reads from the log file.
I cannot attach pictures so here is text explanation:

My Windows EOL convention log file looks like this (in hexa editor):
(part of it in hex string format)
```
...455250443156303136312E696E2E6964656D69612E636F6D20706F72743D35343839380D0A
```
I have put traces in the **process_file** routine, after it reads the line from the log file:
```
while (my $line = <$lfile>)
{
```
And for the same line, the $line variable contains:
(part of it in hex string format)
```
...455250443156303136312E696E2E6964656D69612E636F6D20706F72743D35343839380A
```
As you can see, and as pointed out by other Perl forums, the PerlIO file reading routine get rid of the 0x0D byte to keep only the Unix convention EOL: 0x0A

And the problem it leads to is on the following lines of the **process_file** routine (at 2 different places):
```
			# Get current size/offset in the log file
			$cursize += length($line);
			$current_offset += length($line);
```
The length($line) call will in fact return 1 less than the real line in the Log File because the 0x0D byte is missing.
And this is why in the end when the offset is written in the LAST_PARSED file, it is not the proper offset.
And since it is less than the real correct offset, the next time the incremental parsing is triggered, it will say "already parsed" and do nothing. Until a new Log File is created.

So I have implemented a fix which is working well and here is the simple idea:
add a simple method to detect the EOL pattern and return its length: 2 in case of 0x0D0A (Windows), 1 in case of 0x0A (Unix), 1 in case of 0x0D (Mac)
and instead of doing just `+= length($line)`, do `+= length($line) + (EOL_Pattern_Length - 1)`

I provide you with the code I wrote and you'll do as you wish (of course).

EOL Pattern Detection rountines:
```
# End Of Line Pattern Detection - Get EOL Pattern Length
sub get_file_end_of_line_chars_length
{
	my ($logfile) = @_;

	my $logfileEOLchars = &get_file_end_of_line_chars($logfile);
	if ( length($logfileEOLchars) == 0 )
	{
		# Error case - Pattern not detected
		# Let's default to Unix convention
		return 1;
	}
	return length($logfileEOLchars);
}

# End Of Line Pattern Detection - Get EOL Pattern
sub get_file_end_of_line_chars
{
	my ($logfile) = @_;

	my $strEolResult = "";
	my $logfilesize = -s $logfile;
	if ( open(IN, $logfile) )
	{
		binmode(IN);
		
		# EOL possibilities are:
		# Windows convention: XX0D0A XX\r\n
		# Unix convention: XXYY0A XXYY\n
		# Mac convention: XXYY0D XXYY\r
		for ( my $i = $logfilesize; $i >= 0; --$i )
		{
			seek(IN, $i, SEEK_SET);
			read IN, my $curchar, 1;
			if( $curchar eq "\r" )
			{
				# Mac XXYY0D or Windows XX0D0A - In any case termination case
				$strEolResult = $curchar . $strEolResult;
				last;
			}
			elsif( $curchar eq "\n" )
			{
				# Unix XXYY0A or Windows XX0D0A
				# First LF \n found in byte seq XXYY0A
				# We need to check prev byte (YY) to conclude
				$strEolResult = $curchar;
			}
			else
			{
				if ( $strEolResult eq "\n" )
				{
					# Unix XXYY0A
					last;
				}
			}
		}
		close(IN);
	}
	return $strEolResult;
}
```

And modified code in the process_file routine:

At the beginning (before the `# Get a filehandle to the log file` comment), I call the EOL Pattern Length computation routine:
```
	# Log File End of Line detection
	my $logfileEOLcharslength = &get_file_end_of_line_chars_length($logfile);
	
	# Get a filehandle to the log file
	my $lfile = &get_log_file($logfile, $totalsize);
	if ($logfile ne '-')
	{
```

And at the 2 places where there is the block:
```
			# Get current size/offset in the log file
			$cursize += length($line);
			$current_offset += length($line);
```
I replace it with:
```
			# Get current size/offset in the log file
			$cursize += length($line);
			$current_offset += length($line);

			# Take into account 2 byte EOL pattern (Windows 0x0D0A convention)
			$cursize += ( $logfileEOLcharslength - 1 );
			$current_offset += ( $logfileEOLcharslength - 1 );
```

Doing these few modifications, the offset is correct in the LAST_PARSED file and the next time the incremental parsing is triggered, it starts parsing at the right location and take into account the new lines.

Best Regards.

Bertrand

**Comment by darold** [comment]
Good catch! Last two commit applies your patch with some adjustments. The EOL char detection is done differently (see get_eol_type) and only called on regular files. Compressed file, stdin or input from command are excluded from this detection they are not concerned by the offset position. Please give a try to latest development code and let me know.

**Comment by bbourgier** [comment]
Hi,

Commit e2b2827 working well now with CRLF log files.

Debug output:
```
DEBUG: Start parsing postgresql log at offset 0 of file "C:\pgbadger\__test_last_parsed_e2b2827\postgresql-2021-02-25_114911.log" to 846527
[========================>] Parsed 846527 bytes of 846527 (100.00%), queries: 0, events: 0
```

LAST_PARSED file content (beginning):
```
2021-02-25 11:50:59	846527	2021-02-25 11:50:59.730 ...
```

Thank you very much.


Just an additional remark regarding CR only files (Mac convention):
This is NOT directly related to this bug/fix because CR only means 1 byte EOL char and this case was already properly handled regarding offset increment.
Besides I'm not sure it is relevant in postgreSQL / recent MacOS since CR only files may be old format.
However when I tested 2 days ago with a log file for which I had replaced all EOL by CR (1 byte) char, the traces I had put show that the file line by line reading is not happening properly.
In fact, when reading the first line (in 'process_file', when nlines = 0), the first line read operation reads -- starting at the LAST_PARSED file offset -- the full remaining of the log file till the end.
I had put a trace on the equivalent of line 3732 of commit e2b2827, just after the offset increment to trace the line content, and I got:
```
DEBUG: Start parsing postgresql log at offset 0 of file "C:\pgbadger\__test_last_parsed_OK_Mac\postgresql-2021-02-25_114911_CR.log" to 842448
INFO: process_file - nlines=[0] - cursize=[842448] - current_offset=[842448] - line=[2021-02-25 11:49:11.690 CET [2128]: [2-1] ...
2021-02-25 11:49:11.699 CET [8592]: [2-1] ...
...
2021-02-25 11:50:59.730 CET [7964]: [1-1] ...
] - pgb_last_line_orig=[] - last_line_current_pos=[842448] - pgb_last_line_current_pos=[]
```
Only 1 reading in the loop which got the whole file as 1 line, as you can see in the "line=[...]" output.

Just to tell you there is an issue with CR-only log files reading BUT once again I'm not sure this is relevant considering it.

Thks.

Bertrand

**Comment by darold** [comment]
Thanks, yes I have kept the CR end of line for the logic but I think too this is totally obsolete. Let's see if the problem is reported in the future.
