### ISSUE TITLE
Azure Postgres

### ISSUE THREAD

**Issue by abulfat-masimov** [darold/pgbadger#642]
Hello,

Can anyone confirm if pgbadger supports Azure Postgres 11 logs? I cannot get it working with either this:
`--prefix '%t-%c-' -f stderr`
or this format:
`--prefix 'ts=%m,db=%d,user=%u,app=%a,client=%h,cmdtag=%i,statecode=%e,vtxid=%v,txid=%x' -f stderr`

Thanks

**Comment by darold** [comment]
Can you post a log line please so that we can see the log format used by Azure.

**Comment by abulfat-masimov** [comment]
Hi @darold ,

Here is the extract from server logs (sorry, quoting did not work for me):


ts=2021-03-07 13:18:15.900 UTC,db=mydb1,user=adminuser,app=[unknown],client=192.168.0.1,cmdtag=,statecode=00000,vtxid=7/44116,txid=0LOG:  QUERY STATISTICS
ts=2021-03-07 13:18:15.900 UTC,db=mydb1,user=adminuser,app=[unknown],client=192.168.0.1,cmdtag=,statecode=00000,vtxid=7/44116,txid=0DETAIL:  ! system usage stats:
        !       0.000000 s user, 0.000000 s system, 0.015613 s elapsed
        !       [50052.093750 s user, 16724.093750 s system total]
ts=2021-03-07 13:18:15.900 UTC,db=mydb1,user=adminuser,app=[unknown],client=192.168.0.1,cmdtag=,statecode=00000,vtxid=7/44116,txid=0STATEMENT:  SELECT optimisation_parameter.id AS optimisation_parameter_id, optimisation_parameter.definition_id AS optimisation_parameter_definition_id, 
....logn query
optimisation_parameter_def_1_description, optimisation_parameter_def_1.visibility AS optimisation_parameter_def_1_visibility 
        FROM optimisation_parameter JOIN optimisation_parameter_def AS optimisation_parameter_def_1 ON optimisation_parameter_def_1.id = optimisation_parameter.definition_id LEFT OUTER JOIN optimisation_parameter AS optimisation_parameter_1 ON optimisation_parameter_def_1.id = optimisation_parameter_1.definition_id AND optimisation_parameter_1.is_allowed_value_definition = true 
        WHERE EXISTS (SELECT 1 
        FROM optimisation_parameter_run, optimisation_run 
        WHERE optimisation_parameter.id = optimisation_parameter_run.optimisation_parameter_id AND optimisation_run.run_id = optimisation_parameter_run.optimisation_run_id AND optimisation_run.run_id = '229ebedf257047c5b0ae642221c6ef34')
ts=2021-03-07 13:18:15.900 UTC,db=mydb1,user=adminuser,app=[unknown],client=192.168.0.1,cmdtag=,statecode=00000,vtxid=9/49279,txid=0LOG:  QUERY STATISTICS


And this is pgbadger command:
`pgbadger -I -R 4 --start-monday --dbname seagate --anonymize --log-duration -f stderr --prefix 'ts=%m,db=%d,user=%u,app=%a,client=%h,cmdtag=%i,statecode=%e,vtxid=%v,txid=%x' /tmp/pgbadger/postgresql_test.log -O /tmp/pgbadger/pg_reports/ -v`

and its output:

DEBUG: pgBadger version 11.5.
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Autodetected log format 'stderr' from /tmp/pgbadger/postgresql_test.log
DEBUG: Autodetected log format 'stderr' from /tmp/pgbadger/postgresql_test.log
DEBUG: pgBadger will use log format stderr to parse /tmp/pgbadger/postgresql_test.log.
DEBUG: timezone not specified, using 0 seconds
DEBUG: Starting progressbar writer process
DEBUG: Processing log file: /tmp/pgbadger/postgresql_test.log
DEBUG: Starting reading file "/tmp/pgbadger/postgresql_test.log"...
DEBUG: Start parsing postgresql log at offset 0 of file "/tmp/pgbadger/postgresql_test.log" to 3595
DEBUG: Unknown stderr log line format:  !ytes of0.000000 s user, 0.000000 s system, 0.015613 s elapsed
DEBUG: Unknown stderr log line format:  !       [50052.093750 s user, 16724.093750 s system total]
DEBUG: Unknown stderr log line format:  FROM optimisation_parameter JOIN optimisation_parameter_def AS optimisation_parameter_def_1 ON optimisation_parameter_def_1.id = optimisation_parameter.definition_id LEFT OUTER JOIN optimisation_parameter AS optimisation_parameter_1 ON optimisation_parameter_def_1.id = optimisation_parameter_1.definition_id AND optimisation_parameter_1.is_allowed_value_definition = true 
DEBUG: Unknown stderr log line format:  WHERE EXISTS (SELECT 1 
DEBUG: Unknown stderr log line format:  FROM optimisation_parameter_run, optimisation_run 
DEBUG: Unknown stderr log line format:  WHERE optimisation_parameter.id = optimisation_parameter_run.optimisation_parameter_id AND optimisation_run.run_id = optimisation_parameter_run.optimisation_run_id AND optimisation_run.run_id = '229ebedf257047c5b0ae642221c6ef34')
DEBUG: Saving last parsed line into /var/folders/k5/zmczphpn5k5g1y66_0ts57v40000gn/T/tmp_LAST_PARSED (2021-03-07 13:18:15       3595)
DEBUG: the log statistics gathering took: 2 wallclock secs ( 0.00 usr  0.00 sys +  0.00 cusr  0.01 csys =  0.01 CPU)
DEBUG: Building incremental report for 2021-03-07
LOG: Ok, generating HTML daily report into /tmp/pgbadger/pg_reports//2021/03/07/...
LOG: Ok, generating HTML weekly report into /tmp/pgbadger/pg_reports//2021/week-10/...
LOG: Ok, generating global index to access incremental reports...
DEBUG: writing global index into /tmp/pgbadger/pg_reports//index.html
DEBUG: building reports took:  0 wallclock secs ( 0.01 usr +  0.02 sys =  0.03 CPU)
DEBUG: the total execution time took:  2 wallclock secs ( 0.01 usr  0.02 sys +  0.00 cusr  0.01 csys =  0.04 CPU)

log_line_prefix is set to:
`ts=%m,db=%d,user=%u,app=%a,client=%h,cmdtag=%i,statecode=%e,vtxid=%v,txid=%x`

Thank you

**Comment by darold** [comment]
Looks like the log entries are produced by `log_statement_stats = on`, this is not supported. I don't know if you have control of what his logged on your Azure instance but you should disable this and look at README file about the parameters that should be set. You value for `--prefix` is good, this is the information logged that is not processed by pgbadger.

**Comment by abulfat-masimov** [comment]
Hi @darold, apologies for the delay and thank you for the hints. I have quickly tried with the recommended parameters and still no luck. I will spend a bit more time on this and will report back.

**Comment by abulfat-masimov** [comment]
Hi,

I think I got it working, it still fails on some records but the majority of log get parsed. Here are Postgres 11 parameters in case anyone needs it:
`
log_line_prefix = '%t [%p]: ts=%m,db=%d,user=%u,app=%a,client=%h,cmdtag=%i,statecode=%e,vtxid=%v,txid=%x'
log_duration = ON
log_min_duration_statement=-1
log_statement=ALL
log_statement_stats=OFF
`

Thanks for the awesome tool @darold
