### ISSUE TITLE
Wrong parsing of lines with query result info

### ISSUE THREAD

**Issue by panatamann** [darold/pgbadger#646]
After upgrading pgbadger from 10.3 to 11.4 I see in "Top" section entries looks like (some info anonymized):
![image](https://user-images.githubusercontent.com/56341191/111291618-21dddf00-8626-11eb-81d1-36daab9d7427.png)

but at same time some queries looks normally
![image](https://user-images.githubusercontent.com/56341191/111291774-4a65d900-8626-11eb-8aff-75b5f148acac.png)
(I think that queries returns no rows)

Log parameters of my database are:
![image](https://user-images.githubusercontent.com/56341191/111292140-a3ce0800-8626-11eb-8947-39b27b51846d.png)
![image](https://user-images.githubusercontent.com/56341191/111292226-ba745f00-8626-11eb-95fa-a4d342c2deff.png)

I have not found any similar cases, so what to do?

**Comment by darold** [comment]
I think you have not just upgraded pgbadger but also change the log_line_prefix. Please use `-p` to set the log line prefix accordingly to your log_line_prefix value. Some statements are well reported because there is some queries with the old format in your log.

**Comment by panatamann** [comment]
Thank you for answer, but no.
I made pure case. I extracted one line from log file as it is and added its copy without info about rows and size. I attach this example here as pgsql_log_test.log
Then I got my log_line_prefix from test DB:

```
-bash-4.4$ psql -c 'show log_line_prefix'
              log_line_prefix
--------------------------------------------
 %t [%p]: [%l-1] us=%u,db=%d,app=%a,cli=%h
```
And ran pgbadger with these options:
`/usr/bin/pgbadger -f stderr --prefix '%t [%p]: [%l-1] us=%u,db=%d,app=%a,cli=%h' ./pgsql_log_test.log -o ./pgbadger-test.html`

[pgsql_log_test.log](https://github.com/darold/pgbadger/files/6148653/pgsql_log_test.log)

Result on screenshot. 

![image](https://user-images.githubusercontent.com/56341191/111304806-ee568100-8634-11eb-923e-31ffd6c428fd.png)

**Comment by darold** [comment]
What is the version of PostgreSQL? Looks like this is not an official version, where did you get it?

**Comment by panatamann** [comment]
Yes, it's PostgresPro 11 Enterprise.
But it's strange that old version of pgbadger (as I remember it was 10.3) worked properly with these logs, observed effect began after upgrade to 11.4

**Comment by darold** [comment]
Ok, commit 2273d73 add compatibility with the PostgresPro log file. This is a quick fix to parse correctly the lines that have the additional rows and size information, but @postgrespro it could be interesting to have additional reports like "Top most returning rows" and  "Top most size" statement.

**Comment by panatamann** [comment]
Great! It works! Thank you so much for support.
