### ISSUE TITLE
Wrong timezone in graphs. -Z option does not affect

### ISSUE THREAD

**Issue by panatamann** [darold/pgbadger#647]
Hi @darold !

Here's my script for report creation:
```
#!/bin/bash

BIN=/usr/bin
REP=/tmp/pg_reports
LOG=/PGDATA/pgpro/ent-11/data/log
export TZ=Europe/Moscow

$BIN/pgbadger -j 2 -Z +03 -p '%t [%p]: [%l-1] us=%u,db=%d,app=%a,cli=%h ' -f stderr $LOG/postgresql-$(date +%Y-%m-%d_)* -o $REP/pgbadger-$(hostname)-$(date +%Y-%m-%d).html

```
Here's first lines of today log:
```
2021-03-24 00:00:00 MSK [13447]: [137-1] us=user,db=ern,app=PostgreSQL JDBC Driver,cli=10.250.35.28 LOG:  duration: 193.911 ms  execute S_2: COMMIT
2021-03-24 00:00:00 MSK [13447]: [138-1] us=user,db=ern,app=PostgreSQL JDBC Driver,cli=10.250.35.28 LOG:  duration: 157.375 ms  execute S_2: COMMIT
```
But graphs in report use timezone UTC-3. So, there's 6-hour lag between graphs and reality. Where does javascript find "minus 3"? I've tried some different values of -Z option but had no difference.

![image](https://user-images.githubusercontent.com/56341191/112305287-90b6da00-8caf-11eb-8db7-ff114630c299.png)

**Comment by darold** [comment]
Which version of pgbadger are you using? I do not have this problem with latest release.

**Comment by panatamann** [comment]
I use latest release 11.5
I've made some tests. It depends of browser. When using Chrome or Firefox all ok. In Edge I've got it.
So it looks like it is not pgbadger bug, thank you.

**Comment by darold** [comment]
Yes Edge is not supported, but who use it ;-)
