### ISSUE TITLE
Issue and Enhancement with normalize_query

### ISSUE THREAD

**Issue by jeffreybeale** [darold/pgbadger#648]
I have recently started using pgbadger and found a couple issues with the normalize_query subroutine.

Line 4833:
`  $orig_query =~ s/=\s*NULL/= \?/gs;`

This is after the orig_query has been converted to lowercase, so this never removes nulls.  Also, the extra space after the equals sign prevents a match with other versions of the same query.   Recommend:
`  $orig_query =~ s/=\s*null/=\?/gs;`

I also had some mismatches between prepare, bind, and exec due to some whitespace at the beginning of a query and before the ending semicolon.  I recommend adding these to the end of that method:

```
  # Remove any leading whitespace
  $orig_query =~ s/^\s+//;

  # Remove any trailing whitespace
  $orig_query =~ s/\s+$//;

  # Remove any whitespace before a semicolon
  $orig_query =~ s/\s+;/;/;
```

I tried to submit these as a pull request on a branch, but it appears you have the repo locked down against changes. :-(

Thank you so much for sharing this utility.  It is extremely helpful!

Best regards,
Jeffrey Beale

**Comment by darold** [comment]
Commit 6dd6ddf applies your patch. I don't see any problem to submit a PR, don't know what happen.
