### ISSUE TITLE
Bug: Use of uninitialized value in substitution iterator at /opt/pgbadger/pgbadger line 18917.

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgbadger#649]
With pgBadger v 11.5:
```
$ pgbadger -f syslog2 log
[========================>] Parsed 11606 bytes of 11606 (100.00%), queries: 1, events: 1
LOG: Ok, generating html report...
Use of uninitialized value in substitution iterator at /opt/pgbadger/pgbadger line 18917.
```
This fails with master  too.

The log file has gone through syslog. pgBadger fails with `-f syslog`, `-f syslog2`, or nothing.

The report is okay at first sight, but Top/Time Consuming queries and everything below are missing.

It seems that a query containing this is the culprit (excerpt):
```
Apr  6 23:03:08 BDD postgres[26883]: [62-3] 2021-04-06 23:03:08 CEST [26883-22] app @192.168.xxx.xxx-> DETAIL:  parameters: $1 = '2021-04-06 22:59:22.926', $2 = '40', ... $53 =
Apr  6 23:03:08 BDD postgres[26883]: [62-4]  '\x32373836313336323236203236373038373531...2323631
Apr  6 23:03:08 BDD postgres[26883]: [62-5] 303234323130333136414d49202030313030303432303031303030303331353030303133323331...03060305a4331
...
Apr  6 23:03:08 BDD postgres[26883]: [62-9] 1506035504030c0e41432d4641435455524154494f4e0202086b300d06092a86488...00000000000000000000000000000000000000000000000000000000000000000', $54 = NULL, $55 =
Apr  6 23:03:08 BDD postgres[26883]: [62-10]  NULL, $56 = NULL, $57 = '\x04561d0930303030303130363901310c32303231303430353...3030303030', $58 = NULL, $59 = NULL, $60 = '84081037', $61 = '39'
```

I can send you the full 11 lines log files in private.

**Comment by darold** [comment]
Yes please Christophe, I can not reproduce.

**Comment by Krysztophe** [comment]
Sent

**Comment by darold** [comment]
Got it thanks, commits 6b26e9a and 315b1e2 fix this issue. I have also applied the fix in pgFormatter code which was the source of the problem.

While looking at the result I found that pgbadger is not well handling bind parameters over multiple lines in the log, it need to be fixed too but will take more time. I'm opening a new issue.

**Comment by Krysztophe** [comment]
Thanks!

**Comment by julianodba** [comment]
Hi, I'm getting the same error. Will it be fixed on PR #655 ?


Not sure if it related but for me this issue happen because I have temporarily changed the parameter `log_statement=ddl` to `log_statement=mod` to log a few more queries, and then I have rollbacked the change after a couple of minutes.

Summary:

```
sw_vers 
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241

AWS RDS:
SELECT version();
PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

Setup:
brew install pgbadger
pgbadger --version
pgBadger version 11.5

Run:
pgbadger -I postgresql.log.2021-05-18 -f stderr --prefix='%t:%r:%u@%d:[%p]:' --jobs 4 -O ~/Downloads/
[========================>] Parsed 937294099 bytes of 937294099 (100.00%), queries: 2502374, events: 99
LOG: Ok, generating HTML daily report into /Users/juliano/Downloads//2021/05/18/...
Use of uninitialized value in substitution iterator at /usr/local/bin/pgbadger line 18917.
```

**Comment by darold** [comment]
This have already been fixed, please use latest development code.

**Comment by phiresky** [comment]
I have the same issue still with the development code (version 5bb17be27c9d7e9ab2798fd7d90fa2dd9cc9d988), different line than the above report:

`Use of uninitialized value in pattern match (m//) at pgbadger line 20574.`

**Comment by darold** [comment]
Commit 5d60f53 might fix this one. Thanks.
