### ISSUE TITLE
Doesn't look good when there's not enough place to put the menu

### ISSUE THREAD

**Issue by gleu** [darold/pgbadger#651]
If I look at the report on the whole screen, it displays great. The menu has every item on a line. But if I make the browser window smaller, so that the menu can't be displayed in one line, it may end up like this :

![Screenshot from 2021-04-19 14-53-08](https://user-images.githubusercontent.com/223410/115239600-36c6fa00-a11f-11eb-89c1-5f3cee079155.png)

And that doesn't help to read the report. There's a big bunch I can't read unfortunately.

It would probably be better to change the display so that it shows the usual hamburger icon with the various menu items.

Thanks :)

**Comment by darold** [comment]
Fixed by commit efe7dbc.
