### ISSUE TITLE
Wide character in print at /usr/bin/pgbadger line 13371.

### ISSUE THREAD

**Issue by cthart** [darold/pgbadger#652]
Sorry to keep on opening this issue but I'm still getting
Wide character in print at /usr/bin/pgbadger line 13371.

Yes, I *am* running with the -W option.

**Comment by darold** [comment]
This is just a warning, it should not be problematic. Does it breaks something?

**Comment by cthart** [comment]
Well it’s very annoying to get emails from cron if this doesn’t break anything. And if character sets are done correctly this should never happen. Finally, why not make the whole app work in unicode? Then you won’t have this problem at all.

**Comment by darold** [comment]
Yes I've not though about the cron notification and agree that it can be annoying. I will look to fix that.

**Comment by darold** [comment]
I have tried several changed on input/output encoding to try to avoid this warning message without success. If you still have the problem with latest development code please send a sample of log file that's generates this failure and the output of the `locale` command.
