### ISSUE TITLE
ERROR: Use of uninitialized value in substitution iterator at /usr/local/bin/pgbadger line 19057.

### ISSUE THREAD

**Issue by MichaelDBA** [darold/pgbadger#656]
```
LOG: Ok, generating html report...
Use of uninitialized value in substitution iterator at /usr/local/bin/pgbadger line 19057.
```
Here is the line 19057 in pgbadger:
```
    while ( $self->{ 'content' } =~ s/AAKEYWCONST(\d+)AA/$self->{ 'keyword_constant' }{$1}/s ) {
            delete $self->{ 'keyword_constant' }{$1};
    };
```
I am using the latest master.zip file from this Monday, this week.  v11.5.  I am running against Aurora for PostgreSQL v 11.
I am getting the logs indirectly from CloudWatch (CloudWatch ships to s3, and I pull from s3).

Again, see more information in my other outstanding issue, https://github.com/darold/pgbadger/issues/654

So I have tried 3 separate cases, each pulling 4 separate log files from s3.  It works for one of them as noted in #654, but not in the other 2 cases.

**Comment by wsdookadr** [comment]
Hey @MichaelDBA Can this be reproduced with the test data in #654 ?  If not, could you please share these log files so the error can be reproduced? Thanks !

**Comment by MichaelDBA** [comment]
Look at my last comment i #654
About how cloudwatch gathers these logs

**Comment by wsdookadr** [comment]
@MichaelDBA I used the logs from #654 , placed them in separate files, used pgbadger from commit 98b3816 with the parameters you mentioned in #654 , and was able to get back reports. I'm attaching [an archive with all the files here](https://www77.zippyshare.com/v/0emCPFsE/file.html).

I wasn't able to reproduce the error you mentioned here:

> Use of uninitialized value in substitution iterator at /usr/local/bin/pgbadger line 19057.

**Comment by MichaelDBA** [comment]
Are you kidding me?  Those aren't logs.  Please read again what I said.  That was just a grep snippet to show the overlapping of time across the logs.

**Comment by MichaelDBA** [comment]
I can run pgbadger successfully against all the 4 logs individually, but not together.

Here is list of logs before running pgbadger:
```
-rw-rw-r--. 1 centos centos 14916892 May 14 18:46 pg_20210512_000000_1.log
-rw-rw-r--. 1 centos centos 15343266 May 14 18:46 pg_20210512_000000_2.log
-rw-rw-r--. 1 centos centos 15326793 May 14 18:46 pg_20210512_000000_3.log
-rw-rw-r--. 1 centos centos 14615869 May 14 18:46 pg_20210512_000000_4.log
```

Here are the commands to run pgbadger successfully against each log individually:

```
PG@5432>pgbadger /home/centos/pglogs/pg_20210512_000000_1.log -j 2 -p '%t:%r:%u@%d:[%p]:'  -o ./pg_20210512_000000_1.html
[========================>] Parsed 14916892 bytes of 14916892 (100.00%), queries: 9485, events: 5
LOG: Ok, generating html report...

PG@5432>pgbadger /home/centos/pglogs/pg_20210512_000000_2.log -j 2 -p '%t:%r:%u@%d:[%p]:'  -o ./pg_20210512_000000_2.html
[========================>] Parsed 15343266 bytes of 15343266 (100.00%), queries: 9354, events: 7
LOG: Ok, generating html report...

PG@5432>pgbadger /home/centos/pglogs/pg_20210512_000000_3.log -j 2 -p '%t:%r:%u@%d:[%p]:'  -o ./pg_20210512_000000_3.html
[========================>] Parsed 15326793 bytes of 15326793 (100.00%), queries: 9410, events: 10
LOG: Ok, generating html report...

PG@5432>pgbadger /home/centos/pglogs/pg_20210512_000000_4.log -j 2 -p '%t:%r:%u@%d:[%p]:'  -o ./pg_20210512_000000_4.html
[========================>] Parsed 14615869 bytes of 14615869 (100.00%), queries: 9400, events: 5
LOG: Ok, generating html report...

```
Here is the final pgbadger against all of them which generates the uninitialized value error:
```
PG@5432>pgbadger /home/centos/pglogs/pg_20210512*.log -j 2 -p '%t:%r:%u@%d:[%p]:'  -o ./pg_20210512.html
[========================>] Parsed 60202820 bytes of 60202820 (100.00%), queries: 37649, events: 27
LOG: Ok, generating html report...
Use of uninitialized value in substitution iterator at /usr/local/bin/pgbadger line 19057.

```
Here is the final listing of files:

-rw-rw-r--. 1 centos centos 14916892 May 14 18:46 pg_20210512_000000_1.log
-rw-rw-r--. 1 centos centos 15343266 May 14 18:46 pg_20210512_000000_2.log
-rw-rw-r--. 1 centos centos 15326793 May 14 18:46 pg_20210512_000000_3.log
-rw-rw-r--. 1 centos centos 14615869 May 14 18:46 pg_20210512_000000_4.log
-rw-rw-r--. 1 centos centos  3465420 May 15 11:36 pg_20210512_000000_1.html
-rw-rw-r--. 1 centos centos  3739545 May 15 11:37 pg_20210512_000000_2.html
-rw-rw-r--. 1 centos centos  3599257 May 15 11:37 pg_20210512_000000_3.html
-rw-rw-r--. 1 centos centos  3849843 May 15 11:38 pg_20210512_000000_4.html
-rw-rw-r--. 1 centos centos  1381537 May 15 11:39 pg_20210512.html

**Comment by MichaelDBA** [comment]
Again to be clear,  CloudWatch creates these s3 logs in an unusual way, with timestamps within each file not in sequential order:

grep '2021-05-12 07:34:' pg_20210512_000000_2.log
-->
```
2021-05-12 07:34:46 UTC::@:[30708]:LOG:  automatic vacuum of table "rdsadmin.public.rds_heartbeat2": index scans: 0
2021-05-12 07:34:25 UTC:10.100.11.166(52457):entityservices_app@conceptdb:[18151]:LOG:  duration: 6139.617 ms  execute <unnamed>: select
2021-05-12 07:34:25 UTC:10.100.11.166(52457):entityservices_app@conceptdb:[18151]:DETAIL:  parameters: $1 = '4270764503', $2 = '0.6'
```

Furthermore, the time is overlapping in each log file for the same minute, but not for the same second:

```
pg_20210512_000000_1.log:2021-05-12 07:34:36 UTC::@:[30368]:LOG:  automatic analyze of table "rdsadmin.public.rds_heartbeat2" system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
pg_20210512_000000_1.log:2021-05-12 07:34:12 UTC:10.1.11.249(63190):[unknown]@[unknown]:[29226]:LOG:  connection received: host=10.1.11.249 port=63190

pg_20210512_000000_2.log:2021-05-12 07:34:46 UTC::@:[30708]:LOG:  automatic vacuum of table "rdsadmin.public.rds_heartbeat2": index scans: 0
pg_20210512_000000_2.log:2021-05-12 07:34:25 UTC:10.1.11.166(52457):services_app@mydb:[18151]:LOG:  duration: 6139.617 ms  execute <unnamed>: select

pg_20210512_000000_3.log:2021-05-12 07:34:41 UTC:10.1.11.166(52457):services_app@mydb:[18151]:LOG:  disconnection: session time: 0:04:32.079 user=services_app database=mydb host=10.1.11.166 port=52457
pg_20210512_000000_3.log:2021-05-12 07:34:58 UTC:10.1.11.50(49751):bulke_app@mydb:[26841]:LOG:  duration: 7021.685 ms  execute <unnamed>: WITH BASE_SQL AS ( SELECT * FROM (
pg_20210512_000000_3.log:2021-05-12 07:34:16 UTC::@:[29335]:LOG:  automatic vacuum of table "rdsadmin.public.rds_heartbeat2": index scans: 0

pg_20210512_000000_4.log:2021-05-12 07:34:01 UTC:10.1.31.121(59063):[unknown]@[unknown]:[28917]:LOG:  connection received: host=10.1.31.121 port=59063
pg_20210512_000000_4.log:2021-05-12 07:34:31 UTC:10.1.21.158(52442):[unknown]@[unknown]:[30196]:LOG:  connection received: host=10.1.21.158 port=52442
pg_20210512_000000_4.log:2021-05-12 07:34:51 UTC:10.1.11.191(49451):myreviewtool_app@mydb:[27061]:LOG:  disconnection: session time: 0:25:00.815 user=review_app database=mydb host=10.1.11.191 port=49451

Putting these in time order you got this order of log files:
pg_20210512_000000_4.log:2021-05-12 07:34:01 UTC:10.1.31.121(59063):[unknown]@[unknown]:[28917]:LOG:  connection received: host=10.1.31.121 port=59063
pg_20210512_000000_1.log:2021-05-12 07:34:12 UTC:10.1.11.249(63190):[unknown]@[unknown]:[29226]:LOG:  connection received: host=10.1.11.249 port=63190
pg_20210512_000000_3.log:2021-05-12 07:34:16 UTC::@:[29335]:LOG:  automatic vacuum of table "rdsadmin.public.rds_heartbeat2": index scans: 0
pg_20210512_000000_2.log:2021-05-12 07:34:25 UTC:10.1.11.166(52457):services_app@mydb:[18151]:LOG:  duration: 6139.617 ms  execute <unnamed>: select
pg_20210512_000000_4.log:2021-05-12 07:34:31 UTC:10.1.21.158(52442):[unknown]@[unknown]:[30196]:LOG:  connection received: host=10.1.21.158 port=52442
pg_20210512_000000_1.log:2021-05-12 07:34:36 UTC::@:[30368]:LOG:  automatic analyze of table "rdsadmin.public.rds_heartbeat2" system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
pg_20210512_000000_3.log:2021-05-12 07:34:41 UTC:10.1.11.166(52457):services_app@mydb:[18151]:LOG:  disconnection: session time: 0:04:32.079 user=services_app database=mydb host=10.1.11.166 port=52457
pg_20210512_000000_2.log:2021-05-12 07:34:46 UTC::@:[30708]:LOG:  automatic vacuum of table "rdsadmin.public.rds_heartbeat2": index scans: 0
pg_20210512_000000_4.log:2021-05-12 07:34:51 UTC:10.1.11.191(49451):myreviewtool_app@mydb:[27061]:LOG:  disconnection: session time: 0:25:00.815 user=review_app database=mydb host=10.1.11.191 port=49451
pg_20210512_000000_3.log:2021-05-12 07:34:58 UTC:10.1.11.50(49751):bulke_app@mydb:[26841]:LOG:  duration: 7021.685 ms  execute <unnamed>: WITH BASE_SQL AS ( SELECT * FROM (

```

**Comment by wsdookadr** [comment]
@MichaelDBA Regarding what you wrote
> Again to be clear, CloudWatch creates these s3 logs in an unusual way, with timestamps within each file not in sequential order

Yup, from [the CW User Manual](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/acw-ug.pdf):
> It's possible that events might be duplicated or out of order. To determine the order of events, use thetime property.

[A user is suggesting](https://stackoverflow.com/a/64563622/827519) using Elastic to store and sort them upon retrieval:
> No, I don't believe you can do this with CloudWatch. CloudWatch guarantees delivery, not timely delivery. You could set up a Dynamo or ElasticSearch [..]  On retrieval you can sort by the timestamp

A user [is recommending sorting them by time or sequence number](https://stackoverflow.com/a/32947579/827519) and using a sequence number. A commentor asks why timestamps down to second resolution aren't enough but he's reminded that multiple messages can arrive for that second, and there's also network latency involved and clock deviations.

In terms of sequence numbers, I've had a quick look in the official PostgreSQL docs and was only able to find [`syslog_sequence_numbers`](https://www.postgresql.org/docs/11/runtime-config-logging.html#GUC-LOG-LINE-PREFIX) and I'm not really sure if it's applicable, and according to [the official Aurora documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-ug.pdf) this parameter is missing in Aurora.

---

Having skimmed through the links mentioned above, to me it seems like CloudWatch is suboptimal for this. In [this post on the AWS blog](https://aws.amazon.com/blogs/database/working-with-rds-and-aurora-postgresql-logs-part-2/) commands are available to allow downloading the logs with AWS CLI. Maybe this is a solution, because if I understand correctly these would be regular PostgreSQL logs.

**Comment by MichaelDBA** [comment]
Ok, so the gist of this is that Cloudwatch to s3 to download is not a viable option since Cloudwatch mangles the log entry order within individual stream files and across stream files.  

The AWS CLI is also broken because it truncates logs over 1MB and the --starting-token parameter is not used.
Even the AWS SDK is broken because of bugs with the underlying boto3 python extension for AWS.

**Comment by MichaelDBA** [comment]
Here is what AWS said when I opened a ticket with them for CloudWatch...

```
"From the case notes I understand you noticed that when CloudWatch logs are exported to S3 they are not ordered properly - that is the  timestamps within each file not in sequential order. Do kindly correct me if I misunderstood the query.
Note that this is a known issue the CloudWatch service team is aware of... There is already a feature request raised for the same which is currently being worked on by the internal team. Further, I have also echoed your voice to our internal team on this regard. 
I cannot provide an ETA at this point in time, however, rest assured that AWS is continuously improving its services..."
```

**Comment by wsdookadr** [comment]
> The AWS CLI is also broken because it truncates logs over 1MB

You could try setting [`log_rotation_size=1000`](https://www.postgresql.org/docs/11/runtime-config-logging.html#GUC-LOG-ROTATION-SIZE) in Aurora ([this parameter they do have](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_LogAccess.Concepts.PostgreSQL.html#USER_LogAccess.Concepts.PostgreSQL.log_rotation)), the downside being that you'll have a lot more log files.

> What a bummer that AWS has no working API interface to extract PG Log files for processing by tools such as PGBADGER

I agree

**Comment by MichaelDBA** [comment]
I am closing this issue since it cannot be resolved.  I have created another issue as an informational one that perhaps you can get into pgbadger docs so folks don't spend endless hours trying to use PGBadger with AWS.
https://github.com/darold/pgbadger/issues/657

**Comment by darold** [comment]
Same here @MichaelDBA  I don't think there is problem with your log, give me a link to download them I will have a look. Sorry for being late to answer but I'm really busy this month.
