### ISSUE TITLE
--dbname parameter ignored with "explode" option (-E) in incremental mode regarding reports/folders generation?

### ISSUE THREAD

**Issue by lrevest** [darold/pgbadger#659]
According to the README --dbname, when set, allows restricting the report only to the entries matching with the database passed as parameter.

Executing pgbadger with -E option in incremental mode (+ output) with --dbname set seems to result in logs successfully filtered from entries related to other databases, although output files and folders are generated for them anyway.

"postgres" db getting a normal index.html with every metric zeroed, while other databases (which were not explicitly targeted by --dbname) get an "empty" one (only header+footer+background).

I would have expected reports (and associated folders) being generated only for databases explicitly named with the --dbname parameter.

Tests have been performed using pgbadger 11.5 (on OpenBSD 6.6, connecting via SSH to a remote host storing logs in "stderr" format).

After some (very superficial) digging into the code, I understand postgres database gets a special treatment since it acts as a "catch-all" of some sort for lone entries, and therefore can't be excluded.

On the other hand I couldn't figure out why DBLIST is not intersected with dbname (+DBALL) so that the user gets the reports only for the database she explicitly specified (+postgres).

(Regarding the  README entry for --dbname, I found it to lack the mention this option may be specified multiple times, as specified in the sub compute_arg_list() header comment, plus the ability to pass a comma-separated list. You may want that described in a separate ticket though).

Edit: adding the simultaneous use of "-E" option.

**Comment by darold** [comment]
Thanks for the report, commit 63e3fb9 might fix this issue.
