### ISSUE TITLE
pgbackrest log parsing

### ISSUE THREAD

**Issue by dpiscitelli** [darold/pgbadger#661]
Hi,

I have a problem to parse postgresql log with pgbackrest active. pgbackest log format is quite different from PG 
My PG log format:
_2021-02-21 20:11:13 CET [7926]: [46-1] db=mydb,user=user1,app=myapp - 127.0.0.1:34738 LOG:  duration: 0.197 ms  statement: SELECT......_
pgBackrest log format:
_2021-02-21 20:11:13.833 P00   INFO: pushed WAL file '0000000D000C350E00000052' to the archive asynchronously_

Maybe I'm missing something but I don't see any parameter in pgbackrest to change log format. How to manage this with pgbadger ?

Thx

David

**Comment by dpiscitelli** [comment]
pgbackrest log appears in query text. For example
_SELECT ua.* FROM log.user_action AS ua WHERE ua.common_account_id = ? AND ua.data ->> ? = ? ORDER BY ua.id DESC LIMIT ? OFFSET ? ? - 05 - 25 ? : ? : ?.? p00 info: archive - push command BEGIN ?.? :[pg_xlog / ? d000d3f810000003c] --archive-async --log-level-console=info --log-level-file=info --log-path=/space/logs/pgbackrest --pg1-path=/space/postgresql/data/?.?/main --process-max=? --repo1-host=lengow.v3.archive-0[...];_

**Comment by darold** [comment]
Yes excluding the lines at command line is a workaround for old pgbadger version. Commit 110d46e solves this issue without the need to use `--exclude-line`.
