### ISSUE TITLE
Wildcard chars or regex for exclude appname

### ISSUE THREAD

**Issue by alessaro92** [darold/pgbadger#664]
I'm asking this as a feature request.
I think it could be useful to have an option to specify application names to be excluded with wildcards characters or even a regex like it can be already done for queries.
The main reason I'm asking this is because pgAdmin 4 set as application name a string like "pgAdmin 4 - CONN:9645366" where the number at the end is always random, and I would like to have queries from pgAdmin 4 to be excluded from the pgbadger report.
Thanks in advance.

**Comment by darold** [comment]
Have you tried using `--exclude-line "pgAdmin 4 - CONN:"` ?

**Comment by alessaro92** [comment]
My bad, I had tried with "--exclude-query" but it was matching only the query part and I didn't see the "--exclude-line" option, sorry! Thanks a lot!
