### ISSUE TITLE
Stuck at make command in MSYS2

### ISSUE THREAD

**Issue by sharma-kunal** [darold/pgbadger#671]
I am installing pgBadger on Windows 10. So I installed MSYS2 to `make` file, but when I do `make` in MSYS2 terminal, it gets stuck,

```
GNU Make 4.3
Built for x86_64-pc-cygwin
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
```

P.S: I also tried with CYGWin, but the same issue. 

P.S: I tried using MinGW and it worked fine now, `make && make install` ran sucessfully. 

How should I run pgBadger now ?

**Comment by darold** [comment]
Just copy pgbadger file where you want or execute it where it is, you don't need to run make if it doesn't work.

**Comment by sharma-kunal** [comment]
How should I execute it. It is a `.File` extension ?

**Comment by darold** [comment]
I guess that in a powershell  this should work: perl pgbadger

**Comment by sharma-kunal** [comment]
Ran this command, but nothing. No output.

**Comment by sharma-kunal** [comment]
Shouldn't it had created a `pgbadger.bat` file ?

**Comment by darold** [comment]
Instead of using CygWin you might prefer using a Linux distribution, if you have no luck you should not use CygWin for Perl but install a binary version like Strawberry Perl. Sorry I'm not a great help on this platform.

**Comment by wsdookadr** [comment]
The closest environment to a native Linux distro on Windows is [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), and then CygWin. On either of those pgbadger should work just fine.

**Comment by sharma-kunal** [comment]
Actually I installed Strawberry Perl and used MinGW, using these the installation process worked fine, without any errors. (I used CygWin and MSYS2 but the make command was not running on these. It was always stuck at `Reading makefile 'Makefile'...`), but now even after everything worked fine using Strawberry Perl and MinGW, still I don't see any `.bat` file.

**Comment by wsdookadr** [comment]
I think on Strawberry `gmake` is the make tool that [should be used](https://github.com/darold/pgbadger/issues/480#issuecomment-476125360). There's also a bit of confusion here because the Strawberry toolchain comes with its own make tool, CygWin has one too, MSYS2 also. So you have to decide between: 1) use MSYS2's Perl and its make ; 2) use CygWin's Perl and its make ; 3) use Strawberry Perl and its gmake.

**Comment by sharma-kunal** [comment]
Ok. So I'll go with Strawberry perl Gmake. So, the gmake command in Strawberry Perl, outputs,

```
process_begin: CreateProcess(NULL, which pod2markdown, ...) failed.
gmake: Makefile: 921: pipe: No error
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e cp -- pgbadger blib\script\pgbadger
pl2bat.bat blib\script\pgbadger
```

and gmake install
```
process_begin: CreateProcess(NULL, which pod2markdown, ...) failed.
gmake: Makefile: 921: pipe: No error
Installing C:\STRAW~1\perl\site\bin\pgbadger.bat
Appending Installation info to C:\STRAW~1\perl\lib/perllocal.pod
```

Is this the expected output ?
and I think this is the `.bat` file, I'll need to run pgbadger `C:\STRAW~1\perl\site\bin\pgbadger.bat`

**Comment by sharma-kunal** [comment]
Thanks @wsdookadr @darold . It's working fine now. The problem was I was combining Strawberry perl and MSYS2 make. Using Strawberry Perl and it's gmake, solved the problem.
