### ISSUE TITLE
--explode option make the weekly reports not generated

### ISSUE THREAD

**Issue by thomasLeclaire** [darold/pgbadger#672]
Hello, 

when using the --explode option, the weekly reports sounds not to be generated in incremental mode. is it the expected behavior? 
I would expect to have some weekly reports for each database (and ideally an index to provide list of database, but can easily be managed in nginx for this part). 

thx!

**Comment by darold** [comment]
What is your pgbadger command?

**Comment by thomasLeclaire** [comment]
full one is pgbadger --explode --format=jsonlog --outdir=/usr/share/nginx/html/reports --incremental --jobs 4 --retentio
n=0 --exclude-db=postgres --exclude-user=postgres --exclude-user=cloudsqladmin --wide-char --extra-files *json
which don't create the weekly reports. 

just remove --explode will trigger the creation of daily and weekly reports

**Comment by thomasLeclaire** [comment]
in fact, I think it is something which could be linked to this already corrected : https://github.com/darold/pgbadger/commit/63e3fb959eddbc10113e5833d6c248b7795a9f4a

I was using the "official" package available with apk. but using the last one available in github master, can"t reproduce the issue. therefore it is fine.
