### ISSUE TITLE
--exclude-db option create anyway the related report

### ISSUE THREAD

**Issue by thomasLeclaire** [darold/pgbadger#673]
Hello, 

the --exclude-db option sounds correctly considered during parsing of logs, however, there will be a final report created for these db when using the option --explode, an empty useless one therefore. 

regards

**Comment by darold** [comment]
Not reproducible, please give a try to latest development code and let me know if you still have the issue. And in this case please provide the pgbadger command.

```
$ perl pgbadger --dbname=bench --explode /data/pglog/postgresql-Fri-pg13.log
[========================>] Parsed 67781668 bytes of 67781668 (100.00%), queries: 548, events: 0
LOG: Ok, generating html report for database bench...
$ ls *.html
bench_out.html
$ rm *.html
```
```
$ perl pgbadger --exclude-db=bench --explode /data/pglog/postgresql-Fri-pg13.log
[========================>] Parsed 67781668 bytes of 67781668 (100.00%), queries: 11285635, events: 3
LOG: Ok, generating html report for database gilles...
LOG: Ok, generating html report for database postgres...
LOG: Ok, generating html report for database template1...
$ ls *.html
gilles_out.html  out.html  template1_out.html
```

**Comment by darold** [comment]
Or perhaps you are talking about the out.html file generated? This report correspond to the messages that can not be associated to a DB and to the postgres database report.

**Comment by thomasLeclaire** [comment]
I use the last one available on master.
and pretty strange...
![image](https://user-images.githubusercontent.com/43581346/126487051-02cfe804-0e2e-468e-be0f-ad66fa1508df.png)

**Comment by darold** [comment]
Perhaps it is related to json log, I will check that.

**Comment by darold** [comment]
Got it, commit ed7c407 might solve this issue.

**Comment by thomasLeclaire** [comment]
yes I confirm it's ok now! thx!
