### ISSUE TITLE
report generation could be multi processing when --explode

### ISSUE THREAD

**Issue by thomasLeclaire** [darold/pgbadger#674]
Hello, 

the --jobs setting is used for the log parsing part but not during report generation where only one core considered. When reporting several databases thanks to --explode, we could take advantage of multi processing. 

(probably also some interest with the --rebuild command, but more complex to implement I think)

**Comment by darold** [comment]
Commit 48dbd97 adds this feature.

**Comment by thomasLeclaire** [comment]
thx I confirm it's working!
