### ISSUE TITLE
"last" file always parsed even if it was already done in incremental mode

### ISSUE THREAD

**Issue by thomasLeclaire** [darold/pgbadger#675]
Hello, 

in incremental mode, when running again the same command on same file, the last one is always parsed again, even if no modifications were done : 
![image](https://user-images.githubusercontent.com/43581346/126556999-aece3a90-2ca3-4321-8e4d-e1f1c86d89c4.png)

Checking the script, the issue sounds related to this code : `$more_lines++;`  on line 4685
when the log file is not modified, the last timestamp equal the saved one in LAST_PARSED, therefore the test on line 4678 on 		`if ($saved_date gt $prefix_vars{'t_timestamp'})` is nok which result in a final more_lines variable wrongly set to 1. 

I can understand the fact we could have some new lines on the same timestamp but like the file size is exactly same than the saved one, we shouldn't consider here. 

regards

**Comment by darold** [comment]
Commit a95cc19 might solve this issue.
