### ISSUE TITLE
PG14 introduces globally queryid for normalized queries

### ISSUE THREAD

**Issue by fljdin** [darold/pgbadger#677]
With PostgreSQL 14, a new wildcard `%Q` will be available through `log_line_prefix` parameter. See [Move pg_stat_statements query jumbling to core.][1]

This query identifier could be a great alternative to internal `normalize_query` function in pgBadger, roughly more accurate. Could it be possible to group queries from this identifier?

Regards

[1]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=5fd9dfa5f50e4906c35133a414ebec5b6d518493

**Comment by darold** [comment]
Hi, commit 808d22f adds the detection of this new placeholder in the log line prefix. For the moment it does nothing, I don't see a real use of this value in pgbadger outside perhaps being displayed with the Top sample queries for log search.
