### ISSUE TITLE
Use of uninitialized value in substitution iterator at pgbadger line 19178

### ISSUE THREAD

**Issue by thomasLeclaire** [darold/pgbadger#678]
Hello! 
using last version on git with incremental mode on some GCP cloudsql logs I get this error : 
"Use of uninitialized value in substitution iterator at pgbadger line 19178". 

Trying to understand it, it is related to function print_tempfile_report : 
it firstly loop on all normalyzed_info to grab all queries which have temp files, next during creation of report : 
we have this line : (line 11326)
`$details .= "<b>Info:</b> $top_tempfile_info{$curdb}[$i]->[7]" if ($top_tempfile_info{$curdb}[$i]->[7]);`
which lead to a top_tempfile_info{$curdb} initially set to 20 elements like prerequisite to be upsized to the number of queries with temp files, but with only "empty" elements added. 
These empty elements are next responsible of the substitution error. 

I'm not perl expert and don't really understand why we observe this upsizing of the array and I only found this with some basic print debugging, and therefore I'm not sure on the best way to really fix it. 
For now, I simply modified the line to `$details .= "<b>Info:</b> $top_tempfile_info{$curdb}[$i]->[7]" if ($i<20 && $top_tempfile_info{$curdb}[$i]->[7]);` 

but it's probably not the best way!

**Comment by darold** [comment]
I think you are not using latest development code, ine 19178 is not related to what you are pointing at all. To get this code use git clone or
```
wget https://github.com/darold/pgbadger/archive/refs/heads/master.zip
unzip master.zip
cd pgbadger-master/
perl Makefile.PL
make && sudo make install
```

**Comment by thomasLeclaire** [comment]
I'm using the last one. And yes, line 19178 is directly related to `while ( $self->{ 'content' } =~ s/AAKEYWCONST(\d+)AA/$self->{ 'keyword_constant' }{$1}/s ) { };`
But I investigated about the real cause and it sounds to lead to what I said about function print_tempfile_report. (in particular like with my "fix" it works well).

**Comment by darold** [comment]
Ok got it, commit 20c0093 might fix this issue.
