### ISSUE TITLE
No times for SQL 

### ISSUE THREAD

**Issue by mgogala** [darold/pgbadger#684]
I ran pgbadger on one of my logs like this:
bash-4.4$ pgbadger postgresql-Tue.log -o /tmp/pg_17-AUG-2021.html -j 2
[========================>] Parsed 7112864191 bytes of 7112864191 (100.00%), queries: 26951043300, events: 68
LOG: Ok, generating html report...
bash-4.4$

The HTML report  is attached.
[pg_17-AUG-2021.zip](https://github.com/darold/pgbadger/files/7000969/pg_17-AUG-2021.zip)

I am looking into time consuming queries. All times are 0 and there are no details for any query.

**Comment by mgogala** [comment]
This is happening ever since the upgrade to 13.4. It looks like pgbadger is in need of an upgrade.

**Comment by darold** [comment]
Can you post a line of your log file where there is a query?

**Comment by mgogala** [comment]
The log file is attached. It doesn't contain any valuable data.
[log.zip](https://github.com/darold/pgbadger/files/7001773/log.zip)

**Comment by darold** [comment]
You must disable log_duration in your postgresql.conf actually it erase the pgbadger statistics collected though log_min_duration.

**Comment by mgogala** [comment]
It is disabled:
# - What to Log -

#debug_print_parse = off
#debug_print_rewritten = off
#debug_print_plan = off
#debug_pretty_print = on
log_checkpoints = on
#log_connections = off
#log_disconnections = off
#log_duration = off
#log_error_verbosity = default          # terse, default, or verbose messages
#log_hostname = off
log_line_prefix = '%m [%p] ' 

I didn't change that parameter. Log_min_duration is disabled as well. I have set it through "ALTER USER" parameter for one particular user.

**Comment by mgogala** [comment]
You are right. After setting log_min_duration_statement to 0, the whole thing works again. I was too smart for my own good.
