### ISSUE TITLE
Most frequent errors/events bloated by "`WARNING: database "..." must be vacuumed within 6455639 transactions`"

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgbadger#687]
Hi

We have 4,7 millions of lines such as these in postgresql.log (from 11 millions down to 1 million) :

`WARNING: database "..." must be vacuumed within 6455639 transactions`

The "Most frequent errors/events" report is bloated because it does not recognize that this is the same message with another value.

Is there any chance to aggregate all messages in a single report line ?

(I can provide the report and some logs in private.)

**Comment by darold** [comment]
Commit ba91381 should fix this issue.

**Comment by Krysztophe** [comment]
That works beautifully!
The report is much better with 4,7 millions lines less, and the OOM does not kill pgbadger anymore.
Thanks!
