### ISSUE TITLE
Corrupted storable file

### ISSUE THREAD

**Issue by thomasLeclaire** [darold/pgbadger#690]
Hello, 

I have this recurrent error : 
`Corrupted storable file (binary v2.11) at /usr/lib/perl5/core_perl/Storable.pm line 443, at /usr/bin/pgbadger line 14164.`

debugging locally, I am able to identify this problematic file : https://u.pcloud.link/publink/show?code=XZdIRdXZJvJ9XXfUD1j9euu5x7gOjkoD4eGX   (p assword : pgbadger)
but doesn't see what can be the issue. 

_Like it's a recent behavior, it could be linked to the update of Google cloud SQL from PG 13.2 to PG 13.3 but can't be really sure._

Storable version : 3.21
perl version : v5.32.1
pgbadger : last one on master branch

regards

**Comment by darold** [comment]
A simple script:
```
#!/usr/bin/perl
use Storable qw(retrieve);
retrieve(shift);
```
can reproduce your issue:
```
$ perl test.pl 2021-08-31-481.bin 
Corrupted storable file (binary v2.11) at /usr/lib/x86_64-linux-gnu/perl/5.30/Storable.pm line 421, at test.pl line 4.
```
I don"t know what happen, Storable lack of debug solution but a possible reason is that the binary file have not be generate with the current Storable version and the the internal storage has changed. Does the binary file has been produced with the same storable version?

**Comment by thomasLeclaire** [comment]
yes, it was same storable version 3.21. 
and I continue to get such recurrent errors and still on version 3.21

**Comment by darold** [comment]
Won't be fixed, I don't know how i can fix that.
