### ISSUE TITLE
Week numbers mixed in incremental reports

### ISSUE THREAD

**Issue by hansgv** [darold/pgbadger#698]
Using pgbadger 11.6 latest with the --iso-week-number and --incremental options.

Clicking week numbers in the global index page opens the week's index page but the dates and data in that page are from the previous week.

**Comment by darold** [comment]
Yes there is no backward compatibility with previous weeks reports. If you want to fix that you will have to change the week number in the old sub directory names.

**Comment by hansgv** [comment]
@darold For clarity, this bug occurs even when I produce reports from scratch (no old reports sub-directories exist)

**Comment by darold** [comment]
Ok finallly I have understood the problem and was able to reproduce it. Commit 202050f fixes this issue.

**Comment by hansgv** [comment]
@darold I can confirm that this issue appears fixed when using the latest code.

**Comment by darold** [comment]
Great, thanks for the feedback, a new release is coming.
