### ISSUE TITLE
Problems with GCP CloudSQL Postgresql logs

### ISSUE THREAD

**Issue by uLcL** [darold/pgbadger#699]
Hi,

I'm having problems with the format of GCP CloudSQL Postgresql logs. Even with `-f jsonlog` option no information is returned by pgbadger.

pgbadger was performed both with and without the `-p` option.

Log configuration :

```
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
log_line_prefix = '%m [%p]: [%l-1] db=%d,user=%u '
lc_messages = en_US.UTF8
log_min_duration_statement = 5s
log_error_verbosity = default
```

I have the log that caused the problem and I can send it to you privately.

Thanks !

**Comment by darold** [comment]
Sorry for the response delay, but yes please send me the log if you still have the issue.

**Comment by darold** [comment]
Commit fc96fdd should fix this issue.

**Comment by darold** [comment]
And commit 8ddd029 fixes the auto detection of cloudsql log, option -f should not be necessary.
