### ISSUE TITLE
Wrong progress bar formating, missing parameter to disable

### ISSUE THREAD

**Issue by seidlmic** [darold/pgbadger#702]
Hello, in case of forwarding output pf pgbadger into the file I get wrong, ugly formatting and there is also no parameter to turn it off.
<pre>DEBUG: Start parsing postgresql log at offset 0 of file "/home/vyvojar/pgbadger_pg_log/shkndb-rsd/postgresql-2021-11.log" to 1104637
[>                        ] Parsed       0 bytes of 1104637 (0.00%), queries: 0, events: 0^M[>                        ] Parsed    1567 bytes of 1104637 (0.14%), queries: 0, events: 0^M[>                        ] Parsed   15542 bytes of 1104637 (1.41%), queries: 0, events: 1^M[====>                    ] Parsed  211500 bytes of 1104637 (19.15%), queries: 0, events: 1^M[========================>] Parsed 1104637 bytes of 1104637 (100.00%), queries: 0, events: 11^M
DEBUG: the log statistics gathering took: 2 wallclock secs ( 0.08 usr  0.02 sys +  0.45 cusr  0.00 csys =  0.55 CPU)
</pre>

**Comment by darold** [comment]
Use `-q` to disable the progress bar.

**Comment by seidlmic** [comment]
But `-q` param disables all output. I would like to disable only progress bar that causes bad formatted output into the file as shown above

**Comment by darold** [comment]
Commit fee7644 prints debug message (`-v`) when `-q` or `--quiet` is used.

**Comment by seidlmic** [comment]
Thanks for solution. Still some parameter like --no-progress-bar that will disable only progress bar will be useful for logging output.

**Comment by darold** [comment]
Commit f34d912 adds the `--no-progressbar` option.

**Comment by seidlmic** [comment]
you are great, thanks very much
