### ISSUE TITLE
Docker setup?

### ISSUE THREAD

**Issue by fahadshery** [darold/pgbadger#709]
Hi,

thank you for the project. I think its great for monitoring postgres

I have a postgres server running on FreeBSD.
I also have a Kubernetes cluster running on top of Ubuntu Server.

Is there a `docker version` available where I could install it using docker and then point it to the `postgres` server running over `FreeBSD`?

Cheers,

**Comment by darold** [comment]
pgBadger is a standalone Perl script it should works perfectly on freeBSD or you can use pgbadger on any other server/computer and use the remote log parsing feature of pgbadger. There is no official docker version available from pgbadger maintainer.
