### ISSUE TITLE
suggestion: sample output report

### ISSUE THREAD

**Issue by MichaelDBA** [darold/pgbadger#719]
I deal with customers that want to see what an output pgbadger report looks like.  Be nice to have a generic one here to reference that has most of the drill downs filled in with data.

**Comment by darold** [comment]
Sorry for the response delay, there is a sample log output on the pgbadger web site through the "Examples" menu. Direct link is https://pgbadger.darold.net/samplev7.html

**Comment by MichaelDBA** [comment]
Sweet!  Thanks so much!  My customers will appreciate it.  Can you add this to the official documentation for reference as well?
