### ISSUE TITLE
Commit 6a4750b fixes this issue.

### ISSUE THREAD

**Issue by kevser2761** [darold/pgbadger#725]
Commit 6a4750b fixes this issue.

_Originally posted by @darold in https://github.com/darold/pgbadger/issues/720#issuecomment-1079646019_

hi,
ı tried with -r optıon and my pgbadger verison is 11.7
but ı stıll taking this error code in below and there are new data my log file

no new entries in your log(s) since last run.

**Comment by darold** [comment]
See @fluca1978 answer https://github.com/darold/pgbadger/issues/720#issuecomment-1081581226 I agree that you may not have an HEAD up to date installation.
