### ISSUE TITLE
DDL reporting, specifically temp tables

### ISSUE THREAD

**Issue by lewismichaelr** [darold/pgbadger#728]
When log_statement = ddl or all, we get all create temp table statements in log and pgbadger is already analyzing. It would be awesome to show the number of temp tables created per hour/application name. Probably showing all other DDL as well (optionally) would be awesome for some other users.

For me, it would be very helpful to find what app name is abusing the system catalog by thrashing through temp tables. I can check sample pg_class on a regular basis, but that only gives me temp table name and not app name. So, it would be amazing to just have that info visualized in pgbadger reports at some point in the future.

Note- I didn't see if/where I could submit a feature request rather than an issue.

**Comment by darold** [comment]
If possible please post a log file sample it will save time to know if it is doable and implementing the report. If you prefer you can send it to my private email gilles AT darold DOT net
