### ISSUE TITLE
PgBadger html file showing No Dataset

### ISSUE THREAD

**Issue by aviralsingh21** [darold/pgbadger#732]
Hi,
Everytime I run pgbadger query, it runs successfully but when I open html file, it shows No Dataset. I tried tweaking logs configuration but there is no positive outcome I can get. Please Help.

My essential log configuration for pgbadger are:

log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_min_duration_statement = 100
log_statement = ddl (required in my environment but also tried with 'none')
log_autovacuum_min_duration = 0
log_error_verbosity = default
log_line_prefix = <time=%m app=%a host=%h user=%u db=%d pid=%p line=%l trx=%x>

**Comment by gilles-migops** [comment]
Sorry for responding so late. What is your pgbadger command line?

**Comment by aviralsingh21** [comment]
> Sorry for responding so late. What is your pgbadger command line?

Hi, sorry for not replying as I was hospitalised in a life n death situation for a long time. Though the issue was solved already but still thank you for taking out time for my query.
