### ISSUE TITLE
Sessions info is incorrect

### ISSUE THREAD

**Issue by vitalca** [darold/pgbadger#733]
Hello,

pgBadger 11.8

Yesterday I updated `autovacuum_vacuum_scale_factor` and `autovacuum_vacuum_threshold` for a few large tables. As a result, vacuums began to behave more aggressively and efficiently. At the same time the "Simultaneous sessions" report became incorrect:

![image](https://user-images.githubusercontent.com/18269327/167858728-9c835140-4cd0-434b-8c00-e4bb215d6494.png)

Next logfile (daily rotation):
![image](https://user-images.githubusercontent.com/18269327/167858965-fb41cc2a-2ff5-42dd-988d-01788188a770.png)

Besides, there is another issue with Sessions, not sure if this is related.

![image](https://user-images.githubusercontent.com/18269327/167855522-88f13ba8-1e32-46ce-80c0-fa43e132e43a.png)

At the same time the Chart tab looks much better:

![image](https://user-images.githubusercontent.com/18269327/167855455-70c5d058-8ca0-4b40-8426-20dc3590f598.png)

**Comment by darold** [comment]
Commit c3ad6ab fixes the second issue, I'm working on the first one.

**Comment by vitalca** [comment]
Great, thanks for quick response, Gilles!

**Comment by darold** [comment]
Commit 7b8b28a might fix this issue.
