### ISSUE TITLE
postgresql-14.3 html report doesn't produce

### ISSUE THREAD

**Issue by kevser2761** [darold/pgbadger#735]
Hello,
our cluster running postgresql-14.3 version.
But when we try to take a pgbadger report, html report doesn't produce.
Does pgbadger have support in this version?

/usr/bin/pgbadger -v  --retention 2 -I -q $REMOTE_PG/$LOG_DIR/$LOG_FILE -O $OUTDIR -f stderr --prefix "[%m pid=%p] app=%a user=%u db=%d host=%h sessid=%c txid=%x"

**Comment by darold** [comment]
Please post the version of pgbadger you are using and a line of the log file you are trying to parse so that I can verify the prefix.

**Comment by kevser2761** [comment]
I upgrade  to pgbadger 11.8 version.
the problem still continues

**Comment by darold** [comment]
Can you send to my private email gilles@darold.net a part of your log file to try to reproduce?

**Comment by darold** [comment]
Thanks for the log file I was able to reproduce.

Actually the problem is that you have a space character before each log line so your prefix must include it. You command should be:
```
/usr/bin/pgbadger -v --retention 2 -I -q $REMOTE_PG/$LOG_DIR/$LOG_FILE -O $OUTDIR -f stderr \
                                   --prefix " [%m pid=%p] app=%a user=%u db=%d host=%h sessid=%c txid=%x"
```
Note the space just after the starting double quote.
