### ISSUE TITLE
Pgbadger does not show queries and logs info.

### ISSUE THREAD

**Issue by patriciopincas** [darold/pgbadger#739]
![20220710_172748](https://user-images.githubusercontent.com/58085105/178563132-8dce1cbe-d07f-44f4-8eb1-cb4aca370347.jpg)
![20220710_172109](https://user-images.githubusercontent.com/58085105/178563186-6662de8b-a50f-4373-9365-39ba2a80249a.jpg)

**Comment by darold** [comment]
Well screenshot are not very helpful, can you copy/past here some log lines to be able to reproduce.
