### ISSUE TITLE
Explain link depesz "too big"

### ISSUE THREAD

**Issue by hvisage** [darold/pgbadger#740]
The explain link create a "get" request that looks like: 
```
http://explain.depesz.com/?is_public=0&is_anon=0&plan=%09Aggregate%20%20%28cost%3D1114961.18..1114961.19%20rows%3D1%20width%3D8%29%0A%09%20%20Output%3A%20count%28DISTINCT<snip>
```
and could be ... very very big :(=)

This errs with various errors (depending on browser and time of day). Would it be possible/easy to change that to a `POST` request?

**Comment by darold** [comment]
Commit 332a155 change the submit method to POST, please give it a try and let me know the result.
