### ISSUE TITLE
Document pgBadger exit codes

### ISSUE THREAD

**Issue by jsabater** [darold/pgbadger#745]
Dear Gilles,

First of all, merci beaucoup for your amazing pgBadger. Truly.

Second, I've been trying to find the exit codes of pgBadger in the documentation pages of pgBadger but I have not been able to. I was so sure I had read about it in the past that I was not sure whether to post this request or not. It's just to control exit codes in the script called from a cron job that runs pgBadger daily with all the required parametres (nothing out of the ordinary).

Could you please point me at the right direction?

Thanks in advance.

**Comment by darold** [comment]
pgBadger exit code:

- 0: on success.
- 1: die on error.
- 2:  if it has been interrupted using ctr+c for example.
- 3:  the pid file already exists, maybe another process is already started, or can not be created.
- 4: no log file was given at command line.

Commit 2a99d51 fixes the documentation about return codes and also some wrong return code at some places.

**Comment by jsabater** [comment]
Excellent. Thank you very much. :-)
