### ISSUE TITLE
Can pgbadger generate report in 2 formats in a single run?

### ISSUE THREAD

**Issue by purefan** [darold/pgbadger#746]
hi! 

I tried with `--extension html --extension json` but it only produces a single report (in json), am I missing something obvious?

**Comment by darold** [comment]
Hi,

No it cannot generate several reports format at the same time. If you don't want to parse the log file twice you must proceed as follow:

* generate an output in binary format from your log files: `pgbadger -o filename.bin postgresql.log`
* generate an HTML report from the binary file: `pgbadger -o report.html filename.bin`
* and a json report from the binary file too: `pgbadger -o report.html filename.json`
