### ISSUE TITLE
"Max. recursion depth with nested structures exceeded" with a tar.xz archive

### ISSUE THREAD

**Issue by OrioQuezac** [darold/pgbadger#751]
Hi darold,

We have an issue when generating a report with a tar.xz archive. 
```
$ pgbadger -j 4 -f stderr -p '%t:%r:%u@%d:[%p]:' logs.tar.gz -o /tmp/out.html
Max. recursion depth with nested structures exceeded at /usr/lib64/perl5/vendor_perl/Storable.pm line 328, at /bin/pgbadger line 15537.

can not load incompatible binary data, binary file is from version < 4.0.
LOG: Ok, generating html report...
```
The generated report is blank. 
The archive contains 31 log files (~ 100MB per file). The system was updated (Rocky Linux 8).

```
$ perl -v 

This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi
(with 57 registered patches, see perl -V for more detail)

$ perl -E 'use Storable qw(dclone); say "version=",$Storable::VERSION; say "limit=",$Storable::recursion_limit; my @tt; for (1..1_000_000) { my $t = [[[]]]; push @tt, $t } dclone @tt' 

version=3.11
limit=14271
```

If I extract the archive and generate a report with all 31 files, we have no errors. 

Kind Regards.

**Comment by darold** [comment]
This is normal, there is no place where it is said that pgBadger supports tar archives. pgBadger is able to parse any log compressed single file but not an archive, compressed or not. You must untar your archive.
