### ISSUE TITLE
Option --outdir does not seem to work

### ISSUE THREAD

**Issue by fguiet** [darold/pgbadger#756]
Salut Gilles,

L'option suivante avec le tag v12 ne semble pas fonctionner

-O | --outdir path     : directory where out files must be saved.

Le rapport HTML est enregistré dans le répertoire de lancement de pgbadger (il ne tient pas compte de l'option -O)

Voici un exemple de ce que je lance comme commande:

```bash
pgbadger -f stderr -p '%t [%p]: db=%d,user=%u,app=%a,client=%h ' --outdir /tmp -o postgresql-2022-11-xxx.html /applications/projets/pgbadger/pg_log/postgresql-2022-10-11-xxx.log
```

Si je met un répertoire qui n'existe pas (exemple /tmpxxx) PgBadger m'indique bien l'erreur

Merci
frederic

**Comment by darold** [comment]
Commit 3212e28 fixes this issue.
