### ISSUE TITLE
JSON format file can't be parsed correctly

### ISSUE THREAD

**Issue by sszhao1020** [darold/pgbadger#757]
we exported the Postgres logs from Azure Log Analytics Workspaces to JSON format, then it can't be parsed correctly.
[1.json.zip](https://github.com/darold/pgbadger/files/9782836/1.json.zip)

`❯ ./pgbadger -f jsonlog 1.json -o 1.html
[========================>] Parsed 299891 bytes of 299891 (100.00%), queries: 0, events: 0
LOG: Ok, generating html report...
~/pgbadger master !1 ?8 ❯`

If we export the logs to CSV format, then it could work well. However, CSV has some limitation.
So is there any method to resolve the JSON format parsing issue?

**Comment by darold** [comment]
Some people at Microsoft could have the good idea to sponsor pgbadger which could help their users to use it with their products, but ...

**Comment by robinportigliatti** [comment]
Hello,

A workaroud would be to execute this command:

```
jq -r '.properties | .message ' PT1H.json > PT1H.json
```

But unfortunately with this method we don't have access to the detail of and the parameter of the query.

````
{
   "properties":{
      "timestamp":"2023-08-17 10:00:08.450 UTC",
      "processId":28218,
      "errorLevel":"LOG",
      "sqlerrcode":"00000",
      "message":"<log_line_prefix> LOG: SELECT * FROM human WHERE firstname = '$1' AND lastname = '$2"",
      "detail":"parameters: $1 = 'GILLES', $2 = 'DAROLD'"
   },
   "time":"2023-08-17T10:00:08.452Z",
   "resourceId":"XXX",
   "location":"XXX",
   "category":"PostgreSQLLogs",
   "operationName":"LogEvent"
}
```

And then you execute pgbadger
