### ISSUE TITLE
trying to understand daily reports connection section

### ISSUE THREAD

**Issue by Inrap** [darold/pgbadger#765]
pgbadger 11.8, PostgreSQL 14

In pgbadger, what is exactly an **established connection** in comparison with connections found in pg_stat_activity in PostgreSQL?
For example what does the peak exaclty mean in the picture close to 14:00?
![image](https://user-images.githubusercontent.com/32261793/211329513-4e4841eb-8351-4537-be9d-410303f8282b.png)

At the begininng, I was trying to find the maximum number of connections in a day i.e. the maximum of users connected.
Thanks

**Comment by gleu** [comment]
You won't be able to the maximum number of connected users. What pgbadger has is log of connections on a period of time. It doesn't know how much connections were done before. It can only tell you how much connections happened, and logged during that period of time.
