### ISSUE TITLE
Running out of memory when generating monthly reports

### ISSUE THREAD

**Issue by jsabater** [darold/pgbadger#766]
Good day!

I am having trouble generating monthly reports in a 12 GB RAM container for the month of december of 2022, and it was a _slow_ month. Only two things that changed from previous months were:

1. I updated `pgbadger` to version 12.0.
2. Four very small databases were added, and only one of them was actually in production.

In the end I managed to allow the job to finish by giving it 16 GB of RAM (it usually has 8 GB). The command was this:

```
/usr/bin/pgbadger --extra-files --month-report 2022-12 --incremental --jobs 6 --start-monday --verbose /var/www/pg_reports
```

I checked the documentation and there seems to be nothing to be done here, as [all binary files are loaded before generating the HTML output](https://github.com/darold/pgbadger#parallel-processing).

Is there any way to prevent `pgbadger` to use so much RAM, maybe operating in a much slower manner? Also I am not sure whether using less jobs would make a difference, but I think not as per the documentation. Also running the monthly report every day or week instead of waiting for the end of the month seems that would not make a difference either, as per the documentation:

> The report for a current month can be run every day, it is entirely rebuilt each time. 

Any hints?

Thanks in advance.

**Comment by darold** [comment]
Monthly report uses lot of memory, I do not recommend it. Weekly report should be enough. Maybe I can based monthly report on weekly stats instead of daily stats but I'm not convinced that it will me more efficient.
