### ISSUE TITLE
pgbadger 12.0 : Fail to normalize query with ::tsrange

### ISSUE THREAD

**Issue by grib0** [darold/pgbadger#768]
The following request fails to bind correctly with pgbadger 12.0
It's ok with pgbadger 11.8

`select public.t_plage_cloturee_utilisateur.pcu_utilisateur_nni_fk, public.t_plage_cloturee_utilisateur.pcu_range_cloture from public.t_plage_cloturee_utilisateur where (public.t_plage_cloturee_utilisateur.pcu_utilisateur_nni_fk in ($1, $2, $3, $4, $5, $6, $7) and (public.t_plage_cloturee_utilisateur.pcu_range_cloture && $8::tsrange))`

`pgbadger -f stderr postgresql_pb_range.log` 
output 1 query with 3 examples in time consuming normalized with pgbadger 11.8 
output 3 queries with 1 example each with pgbadger 12.0

**pgbadger 11.8 OK**
![image](https://user-images.githubusercontent.com/6506822/223387232-7c88e3d4-d38b-4a05-8922-54f4911a9237.png)

**pgbadger 12.0 KO**
![image](https://user-images.githubusercontent.com/6506822/223387428-99025141-1c20-40ea-9138-e63de9b3eff0.png)

postgresql_pb_range.log attached 
[postgresql_log_pb_range.log](https://github.com/darold/pgbadger/files/10908132/postgresql_log_pb_range.log)

**Comment by darold** [comment]
Commit b163e52 fix this issue.
