### ISSUE TITLE
pgbadger 12.1 installation issue

### ISSUE THREAD

**Issue by bagafoot** [darold/pgbadger#769]
Hello,
I downloaded source code the nevest version of pgbadger 12.1, 
removed 12.0 by dnf remove pgbadger and installed from source code but when check version it still says version is 12.0

even when run ./pgbadger --version that in source code give me 12.0

```
[root@POSTGRESQL06F001 pgbadger-12.1]# ./pgbadger --version
pgBadger version 12.0
```

what am I missing?

**Comment by systequ** [comment]
Also in footer - is version 12.0 - Report generated by [pgBadger 12.0.]

**Comment by darold** [comment]
Right, I forgot to change the version in pgbadger script. Thanks for the report.

**Comment by bagafoot** [comment]
> Right, I forgot to change the version in pgbadger script. Thanks for the report.

It means it doesnt affect output, it is parsing with new patches, right?  I get some errors I think it is relate to old version.  

Max. recursion depth with nested structures exceeded at /usr/lib64/perl5/vendor_perl/Storable.pm line 328, <$lfile> line 723144, at /bin/pgbadger line 15472.
DEBUG: Reading temporary last parsed line from /tmp/tmp_LAST_PARSED
DEBUG: the log statistics gathering took:42 wallclock secs ( 0.00 usr  0.00 sys + 41.26 cusr  0.37 csys = 41.63 CPU)
DEBUG: Building incremental report for 2023-03-20
can not load incompatible binary data, binary file is from version < 4.0.
can not load incompatible binary data, binary file is from version < 4.0.
LOG: Ok, generating HTML daily report into /var/lib/pgsql/12/pgbadger//2023/03/20/...
can not load incompatible binary data, binary file is from version < 4.0.
can not load incompatible binary data, binary file is from version < 4.0.
LOG: Ok, generating HTML weekly report into /var/lib/pgsql/12/pgbadger//2023/week-13/...
Wide character in print at /bin/pgbadger line 11634.
Wide character in print at /bin/pgbadger line 11668.
Wide character in print at /bin/pgbadger line 11668.
Wide character in print at /bin/pgbadger line 11668.
Wide character in print at /bin/pgbadger line 11668.
Wide character in print at /bin/pgbadger line 11668.
Wide character in print at /bin/pgbadger line 11668.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 11732.
Wide character in print at /bin/pgbadger line 12272.
Wide character in print at /bin/pgbadger line 12272.
Wide character in print at /bin/pgbadger line 12272.
Wide character in print at /bin/pgbadger line 12272.
LOG: Ok, generating global index to access incremental reports...
DEBUG: writing global index into /var/lib/pgsql/12/pgbadger//index.html
DEBUG: building reports took:  9 wallclock secs ( 8.70 usr +  0.12 sys =  8.82 CPU)
DEBUG: the total execution time took: 51 wallclock secs ( 8.70 usr  0.12 sys + 41.26 cusr  0.37 csys = 50.45 CPU)

**Comment by darold** [comment]
Yes, the release contains latest fixes.
