### ISSUE TITLE
Is it possible to extract Query Plans generated by auto_explain?

### ISSUE THREAD

**Issue by rdnkrkmz** [darold/pgbadger#771]
In our environment, we use auto_explain to see query plans. Plans are logged in postgressql.log file. We want to extact this query plans via pgBadger, if it is possible. Later on for examining.
There may be new tab or link in the report.

**Comment by gleu** [comment]
pgBadger already does that.

**Comment by darold** [comment]
Right, auto_explain plan in log file are atomatically detected by pgbadger. You will also have a link in the report to see the explain plan on [Explain Depesz](https://explain.depesz.com/) web site.

**Comment by rdnkrkmz** [comment]
It is great. So, where the plans are located?

**Comment by darold** [comment]
In the Top queries reports through the Examples button if I recall well.

**Comment by rdnkrkmz** [comment]
Yes, see them in report, in the examples section. Thank you very much for your guidane.
