### ISSUE TITLE
Odd session statistics

### ISSUE THREAD

**Issue by KaiHanne** [darold/pgbadger#774]
With our SQL off-loading instance we see odd session statistics in the Global Stats overview:
e.g. 
557 total sessions
7,068 session peak
I'm wondering how a total of 557 session could result in a peak of 7,068  sessions.
![image](https://user-images.githubusercontent.com/87374030/233296958-29397906-a4d2-45bc-a87a-93d473a8d644.png)
We have 5 production instances for which we collect and generate daily statistics with PGBadger. All instances show "normal" global session stats but this one always reports odd stats. I cannot add the log file in case of further analysis because of it's size (195MB gzipped).

**Comment by darold** [comment]
Hi, can you send a link to download the file to  < pgbadger AT darold DOT net >?

**Comment by KaiHanne** [comment]
Hi Darold,

Send through Wetransfer.

Regards | Met vriendelijke groet,


Gert Jan Willems






www.itassist.nl
***@***.***

(+31) 06 43210361

**Comment by darold** [comment]
Got it, thanks.

**Comment by darold** [comment]
Running pgbadger on your log give me the following results:
```
Sessions:
      61,821 Total number of sessions
    3,631 sessions at 2023-04-18 12:32:23 Session peak
```
Are you running pgbadger in incremental mode or just on this single log file? What version are you using?

**Comment by KaiHanne** [comment]
I’m running pgbadger in single log file mode and i’ve just ran it with the 12.1 version:


 

We are running Centos 7.9 on  VMWARE VM WITH 36GB MEM AND 2 CPU’S.

If you need more info please let me know.

Kind regards | Met vriendelijke groet,


Gert Jan Willems






www.itassist.nl
***@***.***

(+31) 06 43210361

**Comment by darold** [comment]
yes, please post here your pgbadger command.

**Comment by KaiHanne** [comment]
e.g.

pgbadger -v postgresql-2.log -U postgres -U pgadmin -b 06:00:00 -e 20:00:00 -o geopub-w16-tue-16-04.html

Kind regards | Met vriendelijke groet,


Gert Jan Willems






www.itassist.nl
***@***.***

(+31) 06 43210361

**Comment by KaiHanne** [comment]
When i run pgbadger without the optional switches (-U and -b -e) then i get the following results:

61,821
Total number of sessions
7,068 sessions at 2023-04-18 19:12:14
Session peak

**Comment by KaiHanne** [comment]
Our logline prefix:
log_line_prefix = '%t [%p]: user=%u,db=%d,app=%a,client=%h '

**Comment by darold** [comment]
Not reproducible or fixed with latest development code. Closing.
