### ISSUE TITLE
GCP Cloudsql postgres log not recognized

### ISSUE THREAD

**Issue by tanujbolisetty** [darold/pgbadger#780]
Hi,

we understand that postgres log should be recognized by the pgbadger. 

We downloaded the postgres cloudsql 14.x log in json format from cloud logging using gcloud

ran the pgbadger against the downloaded json cloudsql postgres error log.

report is empty.

how do we troubleshoot

**Comment by darold** [comment]
Hi, please post the pgbadger command line and a sample of the log to be able to see what's going wrong
