### ISSUE TITLE
wrong report generation

### ISSUE THREAD

**Issue by jcasanov** [darold/pgbadger#784]
Hi,

I'm trying to generate a report (pgbadger 12.1) for the queries of only one database, but keeps getting the sentence of another database appended to the end of a valid query for the report. I'm attaching a sample of the log causing the problem and the generated html.

You can find the offending query in "Slowest individual queries" first position, and can look for "itx_cdr_unique".

The command I'm using is: 
pgbadger --prefix='%t %a [%p]: [%l-1] xid=%x,user=%u,db=%d,host=%r ' --dbname radius --include-query "(insert|update|delete)" -o file.html postgres.log

[file.html.gz](https://github.com/darold/pgbadger/files/11977232/file.html.gz)
[postgres.log.gz](https://github.com/darold/pgbadger/files/11977233/postgres.log.gz)

**Comment by darold** [comment]
Commit f577f2f fixes this issue.
