### ISSUE TITLE
Error - Can't call method "seek"

### ISSUE THREAD

**Issue by vp-lab** [darold/pgbadger#787]
Hello,

Last week I installed pgbadger on 2 environments but sometimes I get this error only on one environment (beta), on prod everything it's fine.
Both environments have same settings.

OS: AlmaLinux 8.8 (Sapphire Caracal)
postgres: 14
pgbadger: pgBadger version 12.0
cron: `*/37 * * * * root /usr/bin/pgbadger -f stderr -q -j 8 --ssh-identity /xxx/ ssh://postgres@192.168.16.16//var/lib/pgsql/14/data/log/postgresql-* -O /var/www/html/pgbadger/`
error: `Can't call method "seek" on an undefined value at /usr/bin/pgbadger line 3905, <DATA> line 122.`

I don't understand why we get this error, maybe I'm missing something?

Thank you.

**Comment by darold** [comment]
Apparently pgbadger can not open a file handle on one remote file. Commit 13cf720 will throw and error when such problem occurs with the path of the file concerned. Can you give a try to last development and report the error message.

**Comment by vp-lab** [comment]
I just installed the new version and I'll come back when I get new errors.
