### ISSUE TITLE
Database beginning with uppercase letters are not shown on the graphs Connections

### ISSUE THREAD

**Issue by robinportigliatti** [darold/pgbadger#792]
Hello,

I have this data that is not shown on my graph.

![image](https://github.com/darold/pgbadger/assets/6468984/05334b1e-362f-48cd-afb1-45760c150ea1)

The graph:

![image](https://github.com/darold/pgbadger/assets/6468984/b3ecf56d-9915-4d1e-ba66-e5f5a5ef6def)

Is this a limitation ? or is this because the amount of connections is so low we can't see it ?

I remember seeing lower number of connections shown in the graph, but maybe I don't remember correctly.

Robin,

**Comment by darold** [comment]
Hi,

This is not a question of upper or lower case, I think the probleme here is that the database connections represent less than 2% of the total and in this case it is aggregated in the "Sum connections < 2%" databases. If you think 2% is too high you can adjust this aggregation limit value using `--pie-limit`
