### ISSUE TITLE
Is pgbadger compatible with PostgreSQL latest version like 13,14,15 and 16?

### ISSUE THREAD

**Issue by wasiualhasib** [darold/pgbadger#796]
I found sometimes pgbadger not capturing from postgresql log file. Because of that I am thinking what happen to this? Is it ok or not for latest version?

**Comment by darold** [comment]
Yes it is PG16 ready, most of the time it can not parse you log file because you have a wrong log_line_prefix or you must specify it to pgbadger, see documentation.
