### ISSUE TITLE
LOG events presented as ERROR entries

### ISSUE THREAD

**Issue by MattiL** [darold/pgbadger#807]
LOG events are shown as ERROR entries in Events - Events distribution graph and legend by pgbadger 12.2. That is misleading.

**Comment by MattiL** [comment]
> LOG: could not receive data from client: Vastapää sulki yhteyden
> LOG:  process ... still waiting for RowExclusiveLock on relation ... of database ... after ... ms

**Comment by darold** [comment]
Commit 6412413 might fix this issue. Can you confirm, please?

**Comment by darold** [comment]
Commit 518d6bc fixes the HTML error report.

**Comment by darold** [comment]
Right, I have decide to rewrite this part and made some changes in the reports. Commit c05d599 fixes this issue.
```
    Change the way LOG level events reported in the Events reports are
    stored. Some of them was still reported and counted as errors instead
    as LOG level entries. The fix is to stored and report them as EVENTLOG
    to differentiate them from queries. This change introduce a backward
    compatibility break when pgbadger is used in incremental mode. You will
    just have the double behavior during the week of the upgrade.
```
