### ISSUE TITLE
Having issues with POST requests to private PEV2 site from pgBadger reports

### ISSUE THREAD

**Issue by kmoradha** [darold/pgbadger#810]
I've set up a private installation of the [PEV2 demo](https://github.com/dalibo/pev2), using their provided index.html file, so that I can visualize explain plans using this excellent tool without have to upload details outside of my network.

I've configured my pgBadger reports to send the explain plans (generated via auto_explain) to my private PEV2 demo installation (via POST requests) using the --explain-url argument, but the demo install doesn't seem to be accepting the parameters, i.e. when I click "Explain Plan" from the pgBadger report, I just get the blank "New Plan" form in PEV2.

I'm using latest pgBadger and latest PEV2 (1.8.0), and I've used my browser dev panel to confirm that the request parameters are being sent in the POST request. I've also tried this with both Firefox and Chrome.

Any ideas what I'm doing wrong here? I know I can just copy-and-paste the explain plan from the pgBadger report to the "New Plan" form, but I was hoping for a little integration magic. :)

(I know this is more likely to be a PEV2 question, and I've asked it there as well...but I thought the community here might have relevant experience with how to get this working.)

**Comment by darold** [comment]
Does it works if you use https://explain.dalibo.com/ instead of your local installation?

**Comment by kmoradha** [comment]
> Does it works if you use https://explain.dalibo.com/ instead of your local installation?

No, when I try that using --explain-url, clicking on an explain plan link results in a "Method Not Allowed" error page.  I was getting the same thing with my private install when I initially used Nginx to host the PEV2 index.html (which seems to be a common outcome with Nginx, based on Google search)...when I switched to Apache HTTP Server, that error was eliminated, but the explain plan data was not posted to the form (I did use the browser Dev tools to confirm that the data was being sent via the POST request, though).

**Comment by kmoradha** [comment]
This issue was answered by the PEV2 owner: [https://github.com/dalibo/pev2/issues/619](https://github.com/dalibo/pev2/issues/619).

**Comment by chaosong** [comment]
<img width="780" alt="image" src="https://github.com/user-attachments/assets/c23032b0-f252-4d02-b88d-1637bab2815f" />
"Explain Plan"  is not clickable and there is html error in "Explain plan" outer block

pgbadger: 12.2
pev2: self-hosted lastest dalibo/explain.dalibo.com
