### ISSUE TITLE
pgBouncer 1.21 logs parsing isssue

### ISSUE THREAD

**Issue by aleszeleny** [darold/pgbadger#811]
Hello,

I've found the logs for pgBouncer 1.21 are not parsed properly.
Partially it is due to stats format change - workaround and a test file included as attached patch:
[0001-Allow-better-parsing-of-pgbouncer-1.21-logs.patch.gz](https://github.com/darold/pgbadger/files/13721371/0001-Allow-better-parsing-of-pgbouncer-1.21-logs.patch.gz)
But it is still an incomplete solution:

- Report sections: *Histogram of session times*, *Sessions per database*, *Sessions per user*, and *Sessions per host* still lacks data,
- So far I have not attempted to put the newly parsed data (related to prepared statements support) to present them in the generated report(s),
- Tests needed to be enhanced as the file to test pgBouncer 1.21 log lacks tests (at least now it checks that parsing did not crash unexpectedly).

I hope the sample pgBouncer 1.21 included in the attached patch will help, potentially also the parsing of stats in the new format.

Thanks for this great tool!
Aleš Zelený

**Comment by darold** [comment]
Commit b396f8e applies your patch with additional fixes on tests and pgbouncer session detection.

**Comment by aleszeleny** [comment]
Many thanks!
