### ISSUE TITLE
question:  Set log_min_duration_statement = '-1' and auto_explain.log_min_duration='2s' will report slowest queries ?

### ISSUE THREAD

**Issue by bagafoot** [darold/pgbadger#814]
Hello,
I am using auto_explain extension and realize that auto_explain reporting queries  as "Query Text" so there were duplicate log entries for one specific query . So I set log_min_duration_statement = '-1'  to eliminate duplicate logging and set auto_explain.log_min_duration='2s'.
So in this case pgbadger will report slowest queries anyway ?

**Comment by darold** [comment]
I don't think so, but I have never tested. Can you update the issue if you have given a try?
