### ISSUE TITLE
Broken link on https://pgbadger.darold.net/#download

### ISSUE THREAD

**Issue by julienc256** [darold/pgbadger#818]
Hi,

I am looking forward a RPM package for pgbadger, but I unfortunately don't find it.

On you website https://pgbadger.darold.net/#download there is a link for the pgbadger package, but the link is broken !!!

Here is the broken link : http://yum.postgresql.org/packages.php

Will it be possible for you to correct this?

Thanks !

**Comment by darold** [comment]
Thanks for the report, the link is fixed and point now to https://yum.postgresql.org/packages/

**Comment by julienc256** [comment]
Thank-you for your prompt response !

The link works, but unfortunately the pgbadger RPM package is not available :(

Do you plan to add it?
