### ISSUE TITLE
No queries or events detected in stderr log

### ISSUE THREAD

**Issue by andyparsons** [darold/pgbadger#82]
Similar questions have been asked before, but none of the resolutions seem to apply for my case. I'm using PgBadger 3.1 on a production Posgres 9.1 instance. The log options in my conf are as follows:

```
log_destination = 'stderr'
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 0
client_min_messages = notice
log_min_messages = warning
log_min_error_statement = error
log_min_duration_statement = 0
log_checkpoints = on
log_connections = on
log_disconnections = on
log_duration = off
log_error_verbosity = verbose
log_hostname = on
log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u '
log_lock_waits = on
log_statement = 'none'
log_temp_files = 0
```

And when I run there are no events or queries detected:

```
ubuntu@db:/data/postgresql/pg_log$ pgbadger -v -f stderr -p -g postgresql-2013-03-27.log 
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Starting to parse log file: postgresql-2013-03-27.log
DEBUG: Starting reading file postgresql-2013-03-27.log...
[==================>      ] Parsed  905078048 bytes of 1164689450 (77.71%), queries: 0, events: 0
```

I'm guessing I am making a noob mistake, but I'm not sure what to try here. Thanks. pgbadger is fantastic and I cannot wait to analyze my logs on this machine!

**Comment by pcav** [comment]
Thanks. I have:
#log_duration = off
#log_statement = 'none'                 # none, ddl, mod, all
log_min_duration_statement = 0

**Comment by Trivedi-Vacha** [comment]
I have the same problem, my log file format is like:
2018-06-04 07:51:33,171 5712 DEBUG db_21_5 openerp.sql_db: SQL LOG from:
2018-06-04 07:51:33,171 5712 DEBUG db_21_5 openerp.sql_db: table: bus_bus: 0:00:00.000285/1
2018-06-04 07:51:33,171 5712 DEBUG db_21_5 openerp.sql_db: SUM from:0:00:00.000285/1 [3411]
2018-06-04 07:51:33,171 5712 DEBUG db_21_5 openerp.sql_db: SUM into:0:00:00/1 [3411]
2018-06-04 07:51:33,171 5712 DEBUG db_21_5 openerp.sql_db: ConnectionPool(used=2/count=6/max=64) Give back connection to 'dbname=db_21_5'
2018-06-04 07:51:33,171 5712 DEBUG db_21_5 openerp.sql_db: ConnectionPool(used=1/count=6/max=64) Put connection to 'dbname=db_21_5' in pool

I have used log_line_prefix = '%t [%p]: [%l-1] ' in .conf file.

Thanks in advance.

**Comment by zombiekillaa** [comment]
I ran the following command to parse my log file-
```./pgbadger --prefix '%t - %h - %d - %a ' -f stderr -x json --prettify-json /Users/postgre.log```
It's output is as shown below - 
```[========================>] Parsed 282332144 bytes of 282332144 (100.00%), queries: 0, events: 1```

When i parsed in HTML format it does not show the actual query distribution on the HTML page, but it is showing the query time histogram of the various queries.

Sample of logfile -
2019-07-20 08:46:29 PDT - 10.163.33.30 - dbname - [unknown] LOG:  duration: 1045.242 ms  statement: SELECT COUNT(*) FROM "builder_build"
2019-07-20 08:45:55 PDT - 10.163.33.30 - dbname - [unknown] LOG:  duration: 2328.279 ms  statement: SELECT "builder_deliverable"."vmodl_id", "builder_deliverable"."targetchangeset" FROM "builder_deliverable"
2019-07-20 08:45:55 PDT - 10.163.33.30 - dbname - [unknown] LOG:  duration: 3370.267 ms  statement: SELECT "tester_testrun"."location_id", "tester_testrun"."imagefilename"FROM "tester_testrun" 

What should be done so that the different queries can also be identified by pgbadger.

Thanks in advance.

**Comment by darold** [comment]
Where is the `%p` placeholder in your prefix? Documentation says:
```
    pgBadger supports any custom format set into the log_line_prefix
    directive of your postgresql.conf file as long as it at least specify
    the %t and %p patterns.
```

**Comment by zombiekillaa** [comment]
Thanks @darold , i changed the log_line prefix directive of postgresql.conf and new logs with %p placeholder worked fine for me.

**Comment by cp76-badger** [comment]
When I ran pgbadger to my log. it is giving events but not queries. Attaching log file
[postgress.log](https://github.com/darold/pgbadger/files/4685534/postgress.log)

**Comment by macfredd** [comment]
It is probably something obvious but in case you have your logs  in languages ​​other than English, it will not work, I had mine in Spanish so I have to change it to English

# locale for system error message
lc_messages = 'en_US.utf8'

**Comment by ajaimesb** [comment]
Hi, 
I am trying to parse my log file and I am getting 0 Queries:

pgbadger.bat -p "%t:%r:%u@%d:[%p]:" -o C:\temp\Performance2.html C:\temp\postgresql.log.2021-02-01-15
[========================>] Parsed 399 bytes of 399 (100.00%), queries: 0, events: 0


This is an example of the log file

2021-02-01 15:22:21 UTC:10.4.1.97(53581):dbuser@dbname:[18449]:LOG:  duration: 7463.050 ms  bind <unnamed>: SELECT * FROM MyTable WHERE field1 = $1 and field2 = $2 and field3 = $3 and field4 = $4 and field5 = $5
2021-02-01 15:22:21 UTC:10.4.1.97(53581):dbuser@dbname:[18449]:DETAIL:  parameters: $1 = '4118000000003184216', $2 = '4118000000003184146', $3 = '1', $4 = '4118000000003185789', $5 = '8'


This is the configuration of the server:

log_line_prefix   %t:%r:%u@%d:[%p]:
log_min_duration_statement   3s
log_min_error_statement  ERROR
log_duration   OFF
log_statement  NONE

Thanks in advance

**Comment by darold** [comment]
I think there is too few log entries in your log file and bind statement are not taken in account if there is no execute trace following.

**Comment by ajaimesb** [comment]
Am I missing a configuration parameter? the only thin I see in the log is this :
2021-02-01 16:24:06 UTC:10.4.1.97(53625):user@dbname:[21465]:LOG:  duration: 7497.559 ms  bind <unnamed>: SELECT  
... (Query)
2021-02-01 16:24:06 UTC:10.4.1.97(53625):user@dbname:[21465]:DETAIL:  parameters: $1 = '4118000000003184416', $2 = '4118000000003184371', $3 = '1', $4 = '4118000000003185964', $5 = '13'

I can't see an execute log line

Thank in advance

**Comment by darold** [comment]
Yes, actually you have only this bind statement that takes more then 3 seconds, you can try to decrease the log_min_duration_statement configuration directive to 1s for example to see if there is more statements logged.

**Comment by nisha-11-A** [comment]
Hi, I got this log error can you resolve it



INIT_REPORT Init Duration: 10001.79 ms	Phase: init	Status: timeout
[>                        ] Parsed        0 bytes of 14940414 (0.00%), queries: 0, events: 0
[>                        ] Parsed    62534 bytes of 14940414 (0.42%), queries: 0, events: 0
[>                        ] Parsed   601913 bytes of 14940414 (4.03%), queries: 0, events: 0
[=========>               ] Parsed  6175143 bytes of 14940414 (41.33%), queries: 1, events: 0
[========================>] Parsed 14940414 bytes of 14940414 (100.00%), queries: 29, events: 0
LOG: Ok, generating txt report...
/tmp/slack_sdk/web/client.py:3532: UserWarning: Although the channels parameter is still supported for smooth migration from legacy files.upload, we recommend using the new channel parameter with a single str value instead for more clarity.
warnings.warn(
Contents of /tmp/ directory:
['pandas', 'slack_sdk', 'six.py', 'pip-build-tracker-hszykz3q', 'slack_sdk-3.27.1.dist-info', 'pip-unpack-rekzwihv', 'numpy.libs', 'pytz', 'pip-unpack-4_v0fc25', 'pandas-2.0.3.dist-info', 'pip-unpack-i6fb29_1', 'tzdata-2024.1.dist-info', 'pip-unpack-2wtm5bfl', 'python_dateutil-2.9.0.post0.dist-info', 'slack', '__pycache__', 'numpy-1.24.4.dist-info', 'bin', 'pip-target-sb8t8h0t', 'numpy', 'pytz-2024.1.dist-info', 'pip-unpack-_60nn367', 'pip-ephem-wheel-cache-jitzkmi7', 'pip-install-4o0q7fuk', 'dateutil', 'six-1.16.0.dist-info', 'tzdata', 'pip-unpack-uv9s74nd', 'pip-unpack-vr0vi9zd', 'pip-unpack-xo9lbc1m']
Combined slow queries posted successfully to Slack!
INIT_REPORT Init Duration: 83821.15 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
START RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60 Version: $LATEST
RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60 Error: Runtime exited without providing a reason
Runtime.ExitError
END RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60
REPORT RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60	Duration: 83840.03 ms	Billed Duration: 83841 ms	Memory Size: 300 MB	Max Memory Used: 300 MB

**Comment by nisha1uto** [comment]
Hi i got this log error can you resolve it
INIT_REPORT Init Duration: 10001.79 ms	Phase: init	Status: timeout
[>                        ] Parsed        0 bytes of 14940414 (0.00%), queries: 0, events: 0
[>                        ] Parsed    62534 bytes of 14940414 (0.42%), queries: 0, events: 0
[>                        ] Parsed   601913 bytes of 14940414 (4.03%), queries: 0, events: 0
[=========>               ] Parsed  6175143 bytes of 14940414 (41.33%), queries: 1, events: 0
[========================>] Parsed 14940414 bytes of 14940414 (100.00%), queries: 29, events: 0
LOG: Ok, generating txt report...
/tmp/slack_sdk/web/client.py:3532: UserWarning: Although the channels parameter is still supported for smooth migration from legacy files.upload, we recommend using the new channel parameter with a single str value instead for more clarity.
warnings.warn(
Contents of /tmp/ directory:
['pandas', 'slack_sdk', 'six.py', 'pip-build-tracker-hszykz3q', 'slack_sdk-3.27.1.dist-info', 'pip-unpack-rekzwihv', 'numpy.libs', 'pytz', 'pip-unpack-4_v0fc25', 'pandas-2.0.3.dist-info', 'pip-unpack-i6fb29_1', 'tzdata-2024.1.dist-info', 'pip-unpack-2wtm5bfl', 'python_dateutil-2.9.0.post0.dist-info', 'slack', '__pycache__', 'numpy-1.24.4.dist-info', 'bin', 'pip-target-sb8t8h0t', 'numpy', 'pytz-2024.1.dist-info', 'pip-unpack-_60nn367', 'pip-ephem-wheel-cache-jitzkmi7', 'pip-install-4o0q7fuk', 'dateutil', 'six-1.16.0.dist-info', 'tzdata', 'pip-unpack-uv9s74nd', 'pip-unpack-vr0vi9zd', 'pip-unpack-xo9lbc1m']
Combined slow queries posted successfully to Slack!
INIT_REPORT Init Duration: 83821.15 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
START RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60 Version: $LATEST
RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60 Error: Runtime exited without providing a reason
Runtime.ExitError
END RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60
REPORT RequestId: 7f0ec700-d116-4d27-a460-d67fbb644a60	Duration: 83840.03 ms	Billed Duration: 83841 ms	Memory Size: 300 MB	Max Memory Used: 300 MB
