### ISSUE TITLE
auto_explain parsing broken on postgresql 16

### ISSUE THREAD

**Issue by thedolphin** [darold/pgbadger#821]
When using stderr format:
![image](https://github.com/darold/pgbadger/assets/1102063/fa0dc985-09a3-4a4c-bd80-d9c6c58c7e14)

When using jsonlog format it appears as sql expression

Or, maybe, some advices needed in README to confugure auto_explain module so its output should be suitable for pgbadger

**Comment by darold** [comment]
This was not supported wit csv and json log format. It is now with commit dab9e97.
