### ISSUE TITLE
log_min_duration_statement set to 0 - records all the parameters 

### ISSUE THREAD

**Issue by tejaswikt** [darold/pgbadger#823]
Hi , we have set log_min_duration_statement = 0 , 
this is causing to record all values of ,

1) select * from table where id =**<value>**
2) update table set id = **<value2>** where id = **<value1>**
3) delete from table where id = **<value1>**

I want to mask all these values for the complete database and not to be printed in the logs, as this will have security issue . 

is there any statement to be set to mask the values and pass as literals ?

**Comment by darold** [comment]
For pgbadger you can use the dedicated command line option to obfuscate the values:
```
    --anonymize : obscure all literals in queries, useful to hide confidential data.
```
In PostgreSQL logs, there is no way to do that.
