### ISSUE TITLE
Different ranges for histogram of session times?

### ISSUE THREAD

**Issue by JosefMachytkaNetApp** [darold/pgbadger#824]
Hello guys, thank you very much for your tool. It is really helpful! Great work!

I have one use case for which I would like to set more granular ranges for histogram of session times. 
But I did not find any settings for it. Is there some way to do it from command line? 
Or modifying some internal parameters in code?

Thank you very much.

**Comment by darold** [comment]
Commit ec792bb add two option to be able to do that:
```
       --histogram-query VAL   : use custom inbounds for query times histogram.
                                 Default inbounds in miliseconds:
                             0,1,5,10,25,50,100,500,1000,10000
       --histogram-session VAL : use custom inbounds for session times histogram.
                                 Default inbounds in miliseconds:
                             0,500,1000,30000,60000,600000,1800000,3600000,28800000
```

**Comment by JosefMachytkaNetApp** [comment]
:medal_sports: :1st_place_medal: Thank you very much! Great job! You are :superhero: !
