### ISSUE TITLE
Unexpected EOF Errors on Client Connections Not Recorded in pgbadger Report

### ISSUE THREAD

**Issue by dottle** [darold/pgbadger#826]
Overview:
I am using pgbadger (version 12.2) tool to analyze PostgreSQL logs and generate reports. I frequently encounter error messages like "unexpected EOF on client connection" in the logs, but these are not appearing in the reports generated by pgbadger.

Expected Behavior:
I expect pgbadger to correctly record and display these unexpected EOF errors in the Most Frequent Errors/Events.

**Comment by darold** [comment]
Commit 65bb127 fixes this issue.
