### ISSUE TITLE
Parse don't work

### ISSUE THREAD

**Issue by eric-maletras** [darold/pgbadger#827]
Even I put the form of prefix line, the file is empty

**Comment by darold** [comment]
Well, if you can provide the pgbadger command line you are using and some lines of your log we could help.

**Comment by eric-maletras** [comment]
Sorry for the inconvenient.
The issue form that i'm french and seems taht as the 'lc_messages is "fr_FR", pg_bader can't parse the file.
I have modify 2 lines in conf files:
`log_line_prefix = '%t [%p]: ' `
`lc_messages = 'C' `
With line :
`pgbadger -v -p '%t [%p]: ' /var/log/postgresql/postgresql-15-main.log`
And its work !!
