### ISSUE TITLE
csv separator not working

### ISSUE THREAD

**Issue by hettie-d** [darold/pgbadger#831]
Hello @darold , I am not sure when this happened, but somehow the csv-separator stopped working. pgBudger still recognizes it as a valid option, but it does not change the output - the separator is still a semicolon, and also the strings are not enclosed into double quotes. 

I had these things working in prod for several months, and now we need to migrate to the new server, and everything is falling apart! Please help!

**Comment by vkaplan40** [comment]
WE have this pgbadger ver 12.4 working properly on Oracle Linux 8.7 and not working on Oracle linux 8.9

**Comment by hettie-d** [comment]
We were able to rebuild and now pgBadger is working with no problem - apologies for the false alarm!
