### ISSUE TITLE
Pgbadger throws error while running on Windows OS.

### ISSUE THREAD

**Issue by PremSahooESL** [darold/pgbadger#832]
`Attempt to call undefined import method with arguments ("tmpdir") via package "File::Spec" (Perhaps you forgot to load the package?) at pgbadger line 46.`

**Comment by darold** [comment]
What are the name and version of your operating system?

**Comment by PremSahooESL** [comment]
```
OS: 
   Windows 11
```

**Comment by darold** [comment]
I don't know which Perl distribution you use on your Windows box but package File::Spec is missing.

**Comment by PremSahooESL** [comment]
Strawberry Perl (Version:   5.40.0.1)

**Comment by darold** [comment]
I can't help much more on Windows OS, I would recommend you to use Linux instead.

**Comment by PremSahooESL** [comment]
ok. Thanks for your kind reply.
