### ISSUE TITLE
rotation by day doesn't work any more

### ISSUE THREAD

**Issue by Inrap** [darold/pgbadger#834]
_OS : Windows Server 2012 ; pgbadger 11.8 ; PostgreSQL 14_

I have created a scheduled task with these commands : 

`perl.exe pgbadger C:/datapg14/log/postgresql-0.log -I --retention 2 -b "08:00:00" -e "18:00:00" -d activite -d 3rg --exclude-query "^FETCH FORWARD" -O C:/ms4w/Apache/site/pgbadger/2023 

...`

There are 7 lines like those above from `C:/datapg14/log/postgresql-0.log` to `C:/datapg14/log/postgresql-6.log`.

All was fine until 23 June : there was a file per day.
Now I have juste one log file  `C:/datapg14/log/postgresql-1.log` containing all logs from 24 June to today i.e. over 500 Mo !

What could be the reasons for this sudden behaviour ?

**Comment by darold** [comment]
This is not a problem of pgbadger, this is you postgresql.conf configuration or the way you rotate file under Windows OS.
