### ISSUE TITLE
Unknown database ,User,queries section under Queries option

### ISSUE THREAD

**Issue by kbharathdba28** [darold/pgbadger#835]
we have observed that unknow information under Queries by database, queries by user , duration by user, queries by host and queries by application.  Please find the snap for reference purpose.

Below are the current settings related to logging.

log_destination = 'stderr' 
logging_collector = on
log_checkpoints = on
log_connections = on
log_statement = 'none'
log_line_prefix = '%m [%p] '
log_lock_waits = on 
<img width="503" alt="pgbadger_snap" src="https://github.com/user-attachments/assets/eedcd906-6fb8-4c7c-a803-51d90c009bdb">

**Comment by darold** [comment]
Sorry for the response delay. You may have a parsing issue. Can you post a line of your log file and the pgbadger prefix you are using?

**Comment by kbharathdba28** [comment]
2024-12-04 00:00:01.371 GMT [2099221] LOG:  00000: duration: 4.444 ms  statement: SELECT system_identifier FROM pg_catalog.pg_control_system()

we are using below statement in our script to generate pgbadger report on every day.

pgbadger --exclude-query="SELECT take_sample()" --exclude-query="pg_catalog" --exclude-query="pg_*" $LogFile -o "$RepFile"

**Comment by darold** [comment]
Ok, to have accurate information about users/database/application you must use the following log prefix:
```
log_line_prefix = '%m [%p] usr=%u,db=%d,app=%a '
```
if you don't trace these information that mean that you don't need it, pgbadger use 'unknown' in this case.
