### ISSUE TITLE
Undefined import method warning with Perl 5.39.1 or newer

### ISSUE THREAD

**Issue by kmoradha** [darold/pgbadger#836]
When using Perl 5.39.1 or newer, the following line generates the warning shown below:

`use File::Spec qw/ tmpdir /;`
`Attempt to call undefined import method with arguments ("tmpdir") via package "File::Spec" (Perhaps you forgot to load the package?)`

I believe this is related to this change: https://perldoc.perl.org/5.39.1/perldelta#Calling-the-import-method-of-an-unknown-package-produces-an-error

This does not cause any failure, as the `tmpdir()` method is later called using the proper module-qualified syntax (`File::Spec->tmpdir()`), but the warning can be noisy.

**Comment by darold** [comment]
Commit 3197881 solves this issue. Thanks!
